### ISSUE TITLE
rpc 传输过程中msg中的body数据被修改，尾部增加了length，parent等等信息

### ISSUE THREAD

**Issue by Aresky** [NetEase/pomelo-cn#10]
请问为什么要加这些信息，可不可以拿掉

**Comment by changchang** [comment]
rpc中应该不会对传输的内容进行修改的。可以提供一下具体的消息内容吗？

**Comment by Aresky** [comment]
我传的数据大致是这样的：
msg{id:"1",route:"xxx.xxx.xxx",body:<Buffer> }
关键就是这个body，这个body是一个Buffer，我发现rpc传过去之后全部给我转成json了，并且尾部加了length，parent等数据。我调试了很久，确定是forwardMessage之后数据被改了。就是server.js中的doForward函数里的，代码如下：
var doForward = function(app, msg, session, routeRecord, cb) {
    var finished = false;
    //should route to other servers
    try {
        app.sysrpc[routeRecord.serverType].msgRemote.forwardMessage(
            session,
            msg, 
            session.export(), 
            function(err, resp) {
                if(err) {
                    logger.error('fail to process remote message:' + err.stack);
                }
                finished = true;
                cb(err, resp);
            }
        );
    } catch(err) {
        if(!finished) {
            logger.error('fail to forward message:' + err.stack);
            cb(err);
        }
    }
};

**Comment by changchang** [comment]
forwardMessage是前端服务器转发客户端请求给后端服务器时使用的方法。你传输的msg是页面端的消息吗？页面端应该不会有Buffer对象吧？

如果是服务器端的rpc调用的话，因为需要对参数做序列化，只支持普通的js对象。目前我们的序列化是直接用json做的，传Buffer的话在做json转换的时候是会出现你描述的情况。

另外rpc建议是做小的消息通讯，尽量避免传输Buffer这样大块的对象。如果实在要传Buffer的内容的话，可以先将Buffer转成String再传，之后再将String转成Buffer。

**Comment by Aresky** [comment]
嗯！我将pomelo修改了一下，让前段服务器直接能接收二进制数据，并原样传给后端服务器处理！
谢谢你的回复，看来我只能再将String转为Buffer来使用了。
