### ISSUE TITLE
hybridconnector通信协议是怎么样的，有没有c语言的协议部分的库？

### ISSUE THREAD

**Issue by peiweippww** [NetEase/pomelo-cn#102]
我们客户端是c++的代码，是移动设备上的游戏，所以不希望有太大的库。我们打算用pomelo的hybridconnector进行通信，现在问题是有没有协议部门的c的库，谢谢~

**Comment by demon0925** [comment]
通信协议见文档：
https://github.com/NetEase/pomelo/wiki/Pomelo-%E9%80%9A%E8%AE%AF%E5%8D%8F%E8%AE%AE

C语言版本的库现在正在开发，预计最近一两周就会放出来了。
