### ISSUE TITLE
NPM更新出错

### ISSUE THREAD

**Issue by jn5414** [NetEase/pomelo-cn#107]
> v8-profiler@3.6.2-1 install C:\Program Files\nodejs\node_modules\pomelo\node_m
> odules\pomelo-admin\node_modules\v8-profiler
> node-gyp rebuild

C:\Program Files\nodejs\node_modules\pomelo\node_modules\pomelo-admin\node_modul
es\v8-profiler>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\
....\node_modules\node-gyp\bin\node-gyp.js" rebuild
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  profile_node.cc
  heap_profiler.cc
  cpu_profiler.cc
C:\Users\sk.node-gyp\0.8.17\deps\v8\include\v8.h(183): warning C4506: 内联函数
“v8:
:Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)”没有定义 [C:\Program Files
\nod
ejs\node_modules\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\buil
d\profiler.vcxproj]
          with
          [
              T=v8::Object
          ](..heap_profiler.cc)
  graph_edge.cc
C:\Users\sk.node-gyp\0.8.17\deps\v8\include\v8.h(183): warning C4506: 内联函数
“v8:
:Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)”没有定义 [C:\Program Files
\nod
ejs\node_modules\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\buil
d\profiler.vcxproj]
          with
          [
              T=v8::Object
          ](..cpu_profiler.cc)
  snapshot.cc
  graph_node.cc
..\graph_node.cc(76): warning C4244: “参数”: 从“uint64_t”转换到“uint32_t”
，可能丢失数据 [C:\
Program Files\nodejs\node_modules\pomelo\node_modules\pomelo-admin\node_modules
\v8-profiler\build\profiler.vcxproj]
..\graph_node.cc(84): warning C4244: “参数”: 从“uint64_t”转换到“uint32_t”
，可能丢失数据 [C:\
Program Files\nodejs\node_modules\pomelo\node_modules\pomelo-admin\node_modules
\v8-profiler\build\profiler.vcxproj]
  profiler.cc
..\snapshot.cc(90): warning C4244: “参数”: 从“uint64_t”转换到“v8::SnapshotO
bjectId”，可
能丢失数据 [C:\Program Files\nodejs\node_modules\pomelo\node_modules\pomelo-admi
n\no
de_modules\v8-profiler\build\profiler.vcxproj]
C:\Users\sk.node-gyp\0.8.17\deps\v8\include\v8.h(183): warning C4506: 内联函数
“v8:
:Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)”没有定义 [C:\Program Files
\nod
ejs\node_modules\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\buil
d\profiler.vcxproj]
          with
          [
              T=v8::Object
          ](..snapshot.cc)
  profile.cc
C:\Users\sk.node-gyp\0.8.17\deps\v8\include\v8.h(178): warning C4506: 内联函数
“v8:
:Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)”没有定义 [C:\Program Files
\nod
ejs\node_modules\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\buil
d\profiler.vcxproj]
          with
          [
              T=v8::Object
          ](..profiler.cc)
     正在创建库 C:\Program Files\nodejs\node_modules\pomelo\node_modules\pomelo-
admi
  n\node_modules\v8-profiler\build\Release\profiler.lib 和对象 C:\Program Files\
no
  dejs\node_modules\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\b
  uild\Release\profiler.exp
graph_node.obj : error LNK2001: 无法解析的外部符号 "public: class v8::HeapGraphN
ode cons
t \* __thiscall v8::HeapGraphNode::GetDominatorNode(void)const " (?GetDominatorN
ode@HeapGraphNode@v8@@QBEPBV12@XZ) [C:\Program Files\nodejs\node_modules\pomelo
\node_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vcxproj]
graph_node.obj : error LNK2001: 无法解析的外部符号 "public: class v8::HeapGraphE
dge cons
t \* __thiscall v8::HeapGraphNode::GetRetainer(int)const " (?GetRetainer@HeapGra
phNode@v8@@QBEPBVHeapGraphEdge@2@H@Z) [C:\Program Files\nodejs\node_modules\pom
elo\node_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vcxproj]
graph_node.obj : error LNK2001: 无法解析的外部符号 "public: int __thiscall v8::H
eapGraph
Node::GetRetainersCount(void)const " (?GetRetainersCount@HeapGraphNode@v8@@QBEH
XZ) [C:\Program Files\nodejs\node_modules\pomelo\node_modules\pomelo-admin\node
_modules\v8-profiler\build\profiler.vcxproj]
graph_node.obj : error LNK2001: 无法解析的外部符号 "public: int __thiscall v8::H
eapGraph
Node::GetRetainedSize(void)const " (?GetRetainedSize@HeapGraphNode@v8@@QBEHXZ)
[C:\Program Files\nodejs\node_modules\pomelo\node_modules\pomelo-admin\node_mod
ules\v8-profiler\build\profiler.vcxproj]
C:\Program Files\nodejs\node_modules\pomelo\node_modules\pomelo-admin\node_modu
les\v8-profiler\build\Release\profiler.node : fatal error LNK1120: 4 个无法解析
的外部命令
 [C:\Program Files\nodejs\node_modules\pomelo\node_modules\pomelo-admin\node_mo
dules\v8-profiler\build\profiler.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:256:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\pomelo\node_modules\pomelo-adm
in\node_modules\v8-profiler
gyp ERR! node -v v0.8.17
gyp ERR! node-gyp -v v0.8.5
gyp ERR! not ok
npm WARN optional dep failed, continuing v8-profiler@3.6.2-1

NPM更新的时候报错

**Comment by py8765** [comment]
v8-profile 在windows安装会出现问题，所以在pomelo中是optional，中间有些错误不影响。在windows下安装pomelo可以参考[pomelo快速使用指南](https://github.com/NetEase/pomelo/wiki/pomelo%E5%BF%AB%E9%80%9F%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)

**Comment by jn5414** [comment]
虽然不影响,pomelo也确实已经安装,但是命令无法使用

**Comment by py8765** [comment]
最新版本我们在win7下测试过（win8还没有测试），安装没有问题，测试环境是vs2010 express， python 2.7，vs2012可能有问题。

**Comment by jn5414** [comment]
嗯,没办法, 我去装个vs2010了,windows平台各种不合适,还是换linux平台好
