### ISSUE TITLE
npm install pomelo -g出错

### ISSUE THREAD

**Issue by peiweippww** [NetEase/pomelo-cn#108]
我在window下安装pomelo出错，代码如下：

npm http 304 https://registry.npmjs.org/socket.io/0.9.13
npm http 304 https://registry.npmjs.org/pomelo-admin/0.1.0
npm WARN package.json pomelo-admin@0.1.0 No README.md file found!
npm http 304 https://registry.npmjs.org/pomelo-monitor/0.3.5
npm http 304 https://registry.npmjs.org/pomelo-loader/0.0.4
npm http 304 https://registry.npmjs.org/pomelo-logger/0.0.2
npm http 304 https://registry.npmjs.org/toobusy/0.2.2
npm http 304 https://registry.npmjs.org/ws/0.4.25
npm http 304 https://registry.npmjs.org/pomelo-protobuf/0.3.0
npm http GET https://registry.npmjs.org/log4js
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http GET https://registry.npmjs.org/v8-profiler/3.6.2-1
npm http GET https://registry.npmjs.org/pomelo-monitor/0.3.7
npm http GET https://registry.npmjs.org/socket.io-client/0.9.11
npm http GET https://registry.npmjs.org/pomelo-schedule/0.3.4
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/redis/0.7.3
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/socket.io-client
npm http GET https://registry.npmjs.org/stream-pkg/0.0.4
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/log4js
npm http 304 https://registry.npmjs.org/pomelo-schedule/0.3.4
npm http 304 https://registry.npmjs.org/bindings/1.0.0
npm http GET https://registry.npmjs.org/async/0.1.15
npm http GET https://registry.npmjs.org/dequeue/1.0.3

> toobusy@0.2.2 install C:\Documents and Settings\Administrator\Application Data
> \npm\node_modules\pomelo\node_modules\toobusy
> node-gyp rebuild

C:\Documents and Settings\Administrator\Application Data\npm\node_modules\pomelo
\node_modules\toobusy>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gy
p-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
npm http 304 https://registry.npmjs.org/v8-profiler/3.6.2-1
npm http 304 https://registry.npmjs.org/socket.io-client/0.9.11
npm http 304 https://registry.npmjs.org/pomelo-monitor/0.3.7
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/eyes
npm http 304 https://registry.npmjs.org/redis/0.7.3
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm http 304 https://registry.npmjs.org/base64id/0.1.0
npm http 304 https://registry.npmjs.org/socket.io-client
npm http 304 https://registry.npmjs.org/stream-pkg/0.0.4
npm http 304 https://registry.npmjs.org/tinycolor
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/async/0.1.15
npm http 304 https://registry.npmjs.org/dequeue/1.0.3

> ws@0.4.25 install C:\Documents and Settings\Administrator\Application Data\npm
> \node_modules\pomelo\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Documents and Settings\Administrator\Application Data\npm\node_modules\pomelo
\node_modules\ws>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin
\....\node_modules\node-gyp\bin\node-gyp.js" rebuild

> v8-profiler@3.6.2-1 install C:\Documents and Settings\Administrator\Applicatio
> n Data\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modules\v8-profile
> r
> node-gyp rebuild

C:\Documents and Settings\Administrator\Application Data\npm\node_modules\pomelo
\node_modules\pomelo-admin\node_modules\v8-profiler>node "C:\Program Files\nodej
s\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js
" rebuild
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/stack-trace
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/cycle
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/cycle
npm http 304 https://registry.npmjs.org/stack-trace
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http GET https://registry.npmjs.org/zeparser/0.0.5
  toobusy.cc
  bufferutil.cc
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
  profile_node.cc
  heap_profiler.cc
C:\Documents and Settings\Administrator.node-gyp\0.8.21\deps\v8\include\v8.h(1
83): warning C4506: 内联函数“v8::Persistent<T> v8::Persistent<T>::New(v8::Handl
e<T>
)”没有定义 [C:\Documents and Settings\Administrator\Application Data\npm\node_m
odul
es\pomelo\node_modules\toobusy\build\toobusy.vcxproj]
          with
          [
              T=v8::Object
          ]
  cpu_profiler.cc
C:\Documents and Settings\Administrator.node-gyp\0.8.21\deps\v8\include\v8.h(1
83): warning C4506: 内联函数“v8::Persistent<T> v8::Persistent<T>::New(v8::Handl
e<T>
)”没有定义 [C:\Documents and Settings\Administrator\Application Data\npm\node_m
odul
es\pomelo\node_modules\ws\build\bufferutil.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Documents and Settings\Administrator.node-gyp\0.8.21\deps\v8\include\v8.h(1
83): warning C4506: 内联函数“v8::Persistent<T> v8::Persistent<T>::New(v8::Handl
e<T>
)”没有定义 [C:\Documents and Settings\Administrator\Application Data\npm\node_m
odul
es\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vcx
proj]
          with
          [
              T=v8::Object
          ]
     正在创建库 C:\Documents and Settings\Administrator\Application Data\npm\nod
e_mo
  dules\pomelo\node_modules\toobusy\build\Release\toobusy.lib 和对象 C:\Document
s
  and Settings\Administrator\Application Data\npm\node_modules\pomelo\node_modu
  les\toobusy\build\Release\toobusy.exp
  graph_edge.cc
  正在生成代码
  已完成代码的生成
C:\Documents and Settings\Administrator.node-gyp\0.8.21\deps\v8\include\v8.h(1
83): warning C4506: 内联函数“v8::Persistent<T> v8::Persistent<T>::New(v8::Handl
e<T>
)”没有定义 [C:\Documents and Settings\Administrator\Application Data\npm\node_m
odul
es\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vcx
proj]
          with
          [
              T=v8::Object
          ]
  snapshot.cc
  graph_node.cc
     正在创建库 C:\Documents and Settings\Administrator\Application Data\npm\nod
e_mo
  dules\pomelo\node_modules\ws\build\Release\bufferutil.lib 和对象 C:\Documents
an
  d Settings\Administrator\Application Data\npm\node_modules\pomelo\node_module
  s\ws\build\Release\bufferutil.exp
  正在生成代码
..\graph_node.cc(76): warning C4244: “参数”: 从“uint64_t”转换到“uint32_t”
，可能丢失数据 [C:\
Documents and Settings\Administrator\Application Data\npm\node_modules\pomelo\n
ode_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vcxproj]
..\graph_node.cc(84): warning C4244: “参数”: 从“uint64_t”转换到“uint32_t”
，可能丢失数据 [C:\
Documents and Settings\Administrator\Application Data\npm\node_modules\pomelo\n
ode_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vcxproj]
  已完成代码的生成
  profiler.cc
  toobusy.vcxproj -> C:\Documents and Settings\Administrator\Application Data\n
  pm\node_modules\pomelo\node_modules\toobusy\build\Release\toobusy.node
..\snapshot.cc(90): warning C4244: “参数”: 从“uint64_t”转换到“v8::SnapshotO
bjectId”，可
能丢失数据 [C:\Documents and Settings\Administrator\Application Data\npm\node_mo
dule
s\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vcxp
roj]
C:\Documents and Settings\Administrator.node-gyp\0.8.21\deps\v8\include\v8.h(1
83): warning C4506: 内联函数“v8::Persistent<T> v8::Persistent<T>::New(v8::Handl
e<T>
)”没有定义 [C:\Documents and Settings\Administrator\Application Data\npm\node_m
odul
es\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vcx
proj]
          with
          [
              T=v8::Object
          ]
  profile.cc
  bufferutil.vcxproj -> C:\Documents and Settings\Administrator\Application Dat
  a\npm\node_modules\pomelo\node_modules\ws\build\Release\bufferutil.node
  validation.cc
C:\Documents and Settings\Administrator.node-gyp\0.8.21\deps\v8\include\v8.h(1
78): warning C4506: 内联函数“v8::Persistent<T> v8::Persistent<T>::New(v8::Handl
e<T>
)”没有定义 [C:\Documents and Settings\Administrator\Application Data\npm\node_m
odul
es\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vcx
proj]
          with
          [
              T=v8::Object
          ]
     正在创建库 C:\Documents and Settings\Administrator\Application Data\npm\nod
e_mo
  dules\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\build\Release
  \profiler.lib 和对象 C:\Documents and Settings\Administrator\Application Data\
np
  m\node_modules\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\buil
  d\Release\profiler.exp
graph_node.obj : error LNK2001: 无法解析的外部符号 "public: class v8::HeapGraphN
ode cons
t \* __thiscall v8::HeapGraphNode::GetDominatorNode(void)const " (?GetDominatorN
ode@HeapGraphNode@v8@@QBEPBV12@XZ) [C:\Documents and Settings\Administrator\App
lication Data\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modules\v8
-profiler\build\profiler.vcxproj]
graph_node.obj : error LNK2001: 无法解析的外部符号 "public: class v8::HeapGraphE
dge cons
t \* __thiscall v8::HeapGraphNode::GetRetainer(int)const " (?GetRetainer@HeapGra
phNode@v8@@QBEPBVHeapGraphEdge@2@H@Z) [C:\Documents and Settings\Administrator\
Application Data\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modules
\v8-profiler\build\profiler.vcxproj]
graph_node.obj : error LNK2001: 无法解析的外部符号 "public: int __thiscall v8::H
eapGraph
Node::GetRetainersCount(void)const " (?GetRetainersCount@HeapGraphNode@v8@@QBEH
XZ) [C:\Documents and Settings\Administrator\Application Data\npm\node_modules\
pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vcxpro
j]
graph_node.obj : error LNK2001: 无法解析的外部符号 "public: int __thiscall v8::H
eapGraph
Node::GetRetainedSize(void)const " (?GetRetainedSize@HeapGraphNode@v8@@QBEHXZ)
[C:\Documents and Settings\Administrator\Application Data\npm\node_modules\pome
lo\node_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vcxproj]
C:\Documents and Settings\Administrator\Application Data\npm\node_modules\pomel
o\node_modules\pomelo-admin\node_modules\v8-profiler\build\Release\profiler.nod
e : fatal error LNK1120: 4 个无法解析的外部命令 [C:\Documents and Settings\Admin
istrator\
Application Data\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modules
\v8-profiler\build\profiler.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:255:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 5.1.2600
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Documents and Settings\Administrator\Application Data\npm\node_m
odules\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler
gyp ERR! node -v v0.8.21
gyp ERR! node-gyp -v v0.8.4
gyp ERR! not ok
C:\Documents and Settings\Administrator.node-gyp\0.8.21\deps\v8\include\v8.h(1
83): warning C4506: 内联函数“v8::Persistent<T> v8::Persistent<T>::New(v8::Handl
e<T>
)”没有定义 [C:\Documents and Settings\Administrator\Application Data\npm\node_m
odul
es\pomelo\node_modules\ws\build\validation.vcxproj]
          with
          [
              T=v8::Object
          ]
npm WARN optional dep failed, continuing v8-profiler@3.6.2-1
     正在创建库 C:\Documents and Settings\Administrator\Application Data\npm\nod
e_mo
  dules\pomelo\node_modules\ws\build\Release\validation.lib 和对象 C:\Documents
an
  d Settings\Administrator\Application Data\npm\node_modules\pomelo\node_module
  s\ws\build\Release\validation.exp
  正在生成代码
  已完成代码的生成
  validation.vcxproj -> C:\Documents and Settings\Administrator\Application Dat
  a\npm\node_modules\pomelo\node_modules\ws\build\Release\validation.node
C:\Documents and Settings\Administrator\Application Data\npm\pomelo -> C:\Docume
nts and Settings\Administrator\Application Data\npm\node_modules\pomelo\bin\pome
lo
pomelo@0.3.2 C:\Documents and Settings\Administrator\Application Data\npm\node_m
odules\pomelo
├── crc@0.2.0
├── seq-queue@0.0.5
├── pomelo-protocol@0.1.0
├── pomelo-monitor@0.3.5
├── async@0.2.5
├── pomelo-loader@0.0.4
├── pomelo-protobuf@0.3.0
├── mkdirp@0.3.3
├── pomelo-sync@0.0.3
├── pomelo-logger@0.0.2 (log4js@0.5.7)
├── cliff@0.1.8 (eyes@0.1.8, colors@0.6.0-1, winston@0.6.2)
├── toobusy@0.2.2 (bindings@1.0.0)
├── pomelo-admin@0.1.0 (pomelo-monitor@0.3.7, pomelo-schedule@0.3.4, socket.i
o-client@0.9.11)
├── socket.io@0.9.13 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.i
o-client@0.9.11)
├── pomelo-rpc@0.1.0 (stream-pkg@0.0.4, socket.io-client@0.9.11)
└── ws@0.4.25 (tinycolor@0.0.1, options@0.0.3, commander@0.6.1)

C:\Documents and Settings\Administrator>

**Comment by drinkw** [comment]
同样的问题，看到readme里说可以用vs2010编译，在win8下使用vs2010的命令行，执行npm install -g。

**Comment by jn5414** [comment]
ls的,请问具体怎么弄?

**Comment by drinkw** [comment]
我也是同样编译不过，你是什么环境，貌似要vs2008。这里提问有人处理吗？看上没英文版热闹啊

**Comment by peiweippww** [comment]
以后去英文版那里提问

**Comment by jn5414** [comment]
我的win7-x86的,vs2012,python2.7

**Comment by drinkw** [comment]
peiweippww，你看上去把pomelo装好了，能分享一下你的经验吗？

2013/3/13 jn5414 notifications@github.com

**Comment by peiweippww** [comment]
window上还是会报错，我是在linux上面装的

**Comment by py8765** [comment]
按照[pomelo快速使用指南](https://github.com/NetEase/pomelo/wiki/pomelo%E5%BF%AB%E9%80%9F%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)安装，大家有在windows环境下安装成功的吗？我们本地测试过win7和xp都没有问题，vs2010 express即可，vs2012貌似有问题。

**Comment by peiweippww** [comment]
没成功

**Comment by jiangzhuo** [comment]
0.3之前的版本在Win7下面vs2012是没有问题的 一直在用，还没有升级最新版没有试过
在 2013-3-14，上午10:06，py notifications@github.com 写道：

**Comment by jn5414** [comment]
@jiangzhuo  建议你先不要升级了,我也是0.3之前的ok的,准备升级的时候就那样了,目前只有装一下vs2010 express试一下了

**Comment by jn5414** [comment]
装了vs2010 express 貌似还是不行,还是一样的报错

**Comment by py8765** [comment]
中间有报错是正常的，你试试命令能用吗

**Comment by jn5414** [comment]
命令用不了,提示的和1楼的一模一样的,nodejs文件夹下面node_modules里面已经有了pomelo了

**Comment by py8765** [comment]
![ ](https://f.cloud.github.com/assets/2224417/258881/56550608-8cad-11e2-96ef-4a0cdafc851b.png)
刚刚我这试过了0.3.2也是出现这样的错误，但是命令已经安装成功了，你试试pomelo --help 
0.3.2命令有调整。

**Comment by jn5414** [comment]
汗,原来如此,原来早就装好了,那就不一定要vs2010 express了.因为我之前2012的时候也是一样的,只是命令没用我才以为有问题的
原来是命令换了,囧
抱歉了,因为某些原因自己电脑不方便用linux的,一直麻烦你解答,辛苦了

**Comment by py8765** [comment]
嗯 解决就好 :)
