### ISSUE TITLE
GameServer下app.js下配置时候的问题

### ISSUE THREAD

**Issue by chenyl107** [NetEase/pomelo-cn#11]
今天看代码的时候看到
var areaId = app.get('curServer').areaId;
理解上没问题应该是拿到当前的Server下的场景ID
然后我想有get肯定有set，找了半天没找到demo在哪set的后来在pomelo源代码中找到

Application.processArgs = function(args){
  var serverType = args.serverType || 'master';
  var serverId = args.serverId || this.get('master').id;
  this.set('main', args.main, true);
  this.set('serverType', serverType, true);
  this.set('serverId', serverId, true);
  if(serverType !== 'master') {
    this.set('curServer', this.getServerById(serverId), true);
  } else {
    this.set('curServer', this.get('master'), true);
  }
};

文档上好像对pomelo下app.get后的参数没有作详细的说明，希望能有一份文档能让我知道我还能get什么东西并且作用是什么，比如：curServer是当前服务器。

**Comment by py8765** [comment]
具体可以参考：https://github.com/NetEase/pomelo/wiki/%E6%B8%B8%E6%88%8F%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84app.js%E9%85%8D%E7%BD%AE%E5%8F%82%E8%80%83

**Comment by halfblood369** [comment]
1.areaId是场景服务器的ID，没错。场景服务器Id等信息是在配置文件中进行配置的，然后读取的，没有提供set方法。
2.pomelo游戏框架提供了set,get等方式配置自己的游戏应用，每个游戏应用的设置不同，当然拿到的东西也就不同。比如我们的游戏demo就配置了curServer这样的属性。

**Comment by chenyl107** [comment]
回复py:这份文档好像只有说pomelo提供get和set，没有说pomelo框架已经为我们set好了那些属性。好像node.js下也可以做app.set和app.get操作，所以猜测其实功能上可能是一样的，只是pomelo在node.js上预先为我们set好了一部分属性。
回复halfblood369:我还是不太明白，这么说的话是不是不同的游戏我们要自己手动的去修改pomelo源代码来配置属性。比如另一个游戏我不需要curServer就要删除pomelo源代码的curServer，然后要curArea的话要在pomelo源代码上添加相关的set属性。
其实就像代码：
Application.processArgs = function(args){
var serverType = args.serverType || 'master';
var serverId = args.serverId || this.get('master').id;
this.set('main', args.main, true);
this.set('serverType', serverType, true);
this.set('serverId', serverId, true);
if(serverType !== 'master') {
this.set('curServer', this.getServerById(serverId), true);
} else {
this.set('curServer', this.get('master'), true);
}
};
我可以知道pomelo为我们set好了main,serverType,serverId,curServer这些属性，其他地方是否还有pomelo预先为我们set好的属性可以让我们直接get。。

**Comment by halfblood369** [comment]
@chenyl107 哦，这个看错了，curServer是在pomelo框架内定义的。比如说curServer，serverType，serverId等是在pomelo框架就定义好的。你是想要这些框架本身就定义的参数的信息吧，这个会考虑的……
