### ISSUE TITLE
安装所有示例成功，进入看代码阶段，问一个代码组织的问题

### ISSUE THREAD

**Issue by weiyongqing123** [NetEase/pomelo-cn#111]
lordofpomelo的public下的js文件为什么都是类似**resources**["/app.js"] = {meta: {mimetype: "application/javascript"}, data: ...开头呢，这是使用的什么机制。我发现通过这种包装，代码组织的非常有条理。
另一方面：我们大家在qq群里因找不到真正解决问题的人太少了，大家说网易内部不用qq，那你们用什么即时沟通工具呢，可否建立个官方群。大家交流，推广会更好

**Comment by xiecc** [comment]
客户端使用的是我们的一个开源HTML 5游戏引擎colorbox， 这层其实是commonjs标准的wrapper。
实际开发其实跟component类型，不需要任何文件头，build之后才会出现这段head。但由于colorbox还没有完全开源，因此我们现在直接使用build过的文件。

2013/3/13 weiyongqing notifications@github.com

**Comment by weiyongqing123** [comment]
好的，明白了
