### ISSUE TITLE
area服务器配置问题

### ISSUE THREAD

**Issue by chenyl107** [NetEase/pomelo-cn#112]
终于有时间可以继续玩pomelo了，又刚好遇上pomelo推出新版本，按照捡宝自己的代码自己搭了一下，遇到一个配置area服务器的问题。

server.json里配置了area服务器

``` javascript
{
  "development":{
    "connector": [
        {"id": "connector-server-1", "host": "127.0.0.1", "port": 4110, "clientPort": 4010, "frontend": true},
        {"id": "connector-server-2", "host": "127.0.0.1", "port": 4111, "clientPort": 4011, "frontend": true},
        {"id": "connector-server-3", "host": "127.0.0.1", "port": 4112, "clientPort": 4012, "frontend": true}

    ],
    "area": [
        {"id": "area-server-1", "host": "127.0.0.1", "port": 4120, "clientPort": 4020}
    ],
    "gate": [
        {"id": "gate-server-1", "host": "127.0.0.1", "clientPort": 4009, "frontend": true}
    ]
  },
  "production":{
    "connector": [
        {"id": "connector-server-1", "host": "127.0.0.1", "port": 4110, "clientPort": 4010, "frontend": true},
        {"id": "connector-server-2", "host": "127.0.0.1", "port": 4111, "clientPort": 4011, "frontend": true},
        {"id": "connector-server-3", "host": "127.0.0.1", "port": 4112, "clientPort": 4012, "frontend": true}
    ],
    "area": [
        {"id": "area-server-1", "host": "127.0.0.1", "port": 4120, "clientPort": 4020}

    ],
    "gate": [
        {"id": "gate-server-1", "host": "127.0.0.1", "clientPort": 4009, "frontend": true}
    ]
  }
}
```

app.js中对area服务器进行配置

``` javascript
app.configure('production|development', 'area', function(){
    var areaId = app.get('curServer').areaId;
    console.log("areaId="+areaId);
    if (!areaId || areaId < 0) {
        throw new Error('load area config failed');
    }

   // area.init(dataApi.area.findById(areaId));
});
```

console输出undefined，然后就报了 throw new Error('load area config failed');抛出的error。
由于不知道dataApi是干什么的，所以注释掉了。为什么areaId会未定义，是不是我漏了什么步骤？

**Comment by chenyl107** [comment]
我错了，我面壁，json里没有配areaId，我以为id就是areaId。。囧

**Comment by demon0925** [comment]
这里其实areaId没什么用，因为treasures里只有一个area，这个是设计时为了多场景扩展预留的。
dataApi是用来统一获取/config/data/目录下的资源的统一接口，主要是为了方便读取json数据的工具，你也可以直接拿到这个json，然后把里面的东西提出来。
看你后面是把area初始化给注释掉了，这样你的服务应该会跑不起来的吧。。。

**Comment by chenyl107** [comment]
@demon0925 服务器倒是能跑起来了，因为我还没写module里的area.js.所以我猜只是启动了一个空的什么都没有的服务器。感觉module里的area.js好复杂，能不能简单的解释一下，要是自己编写的话要注意写什么，看了上次上海nodeparty的ppt，可能这个文件和pomelo框架的关系不是很大，没有涉及到这个文件的编写。

**Comment by demon0925** [comment]
area的复杂度是和你的应用相关的，基本的作用就是维护场景中所有的实体，然后由一个无限循环的tick驱动，定时更新实体状态。
lordofpomelo中的area因为集成了AI，AOI各种模块所以比较复杂，不适合做新手参考，捡宝里面的area.js其实已经很简单了，单纯从接口看就是一个无限循环的tick和一些信息获取接口。
https://github.com/NetEase/treasures/blob/master/game-server/app/models/area.js

要注意的是tick里面的东西一定要能在一个tick跑完，一些cpu密集型的运算最好分在area外面。
关于pomelo的游戏的开发我还在写文章，应该最近就可以看到了。

**Comment by chenyl107** [comment]
@demon0925 ,嗯，很期待你的文章，会发表到哪，CNode吗。要是你们能出本书就更好了。

**Comment by demon0925** [comment]
infoQ上，有我们的连载，不过现在只有两篇，我在写第三篇。
出书的事情现在有考虑，不过没有确定。
