### ISSUE TITLE
想知道POMELO是用什么工具做调试的

### ISSUE THREAD

**Issue by totollo** [NetEase/pomelo-cn#118]
如果是一般的NODEJS。NODE-INSPECTOR很好。不过POMELO进不了断点。想知道你们开发POMELO的时候使用什么工具调试的。

**Comment by py8765** [comment]
如果想用工具可以考虑node-inspector，如果想简单那就直接命令行输出。

**Comment by liketo** [comment]
为什么不用eclipse调试啊，今天下载了个试了下，体验超级好啊，是不是有什么问题？
