### ISSUE TITLE
客户端与服务器端的通讯

### ISSUE THREAD

**Issue by chenyl107** [NetEase/pomelo-cn#12]
昨天晚上自己写了一个pomelo的一个简单的app,只是简单的从数据库中读取一个字段的值显示在页面上。然后我想实现的是用定时器每一分钟执行这个request请求去读取数据库的值然后在这个值上+1（更新数据库），再从这个数据库取值然后显示在页面上，然后为了看到效果我把时间改成每一秒钟：

<script type="text/javascript">
      var pomelo = window.pomelo;
      var host = "127.0.0.1";
      var port = "3010";
       function show()
      {
        
          setInterval("insert1()", 1000);
      } 
    
     
      
     function insert1() {
          pomelo.init({
            host: host,
            port: port,
            log: true
          }, function() {
          pomelo.request("connector.entryHandler.update", function(data) {
              document.getElementById('lbltext').innerHTML=data.gold;
            });
          
      
          
          });
        } 
    </script>

效果实现了，每一秒向后台发送一个request请求，并且更新页面的值。我的问题是这样是不是很占服务器的资源，request是不是长连接，这样一分钟就建立了60个长连接。看了捡宝的文档，有三种通讯方式：
Request - Response 方式，Notify (向服务端发送通知)，Push （服务端主动发送消息到客户端。感觉Push方式最适合，客户端注册一个update事件，服务器每一秒钟push一下数据库的值，但是push是在channal中的，而我只有一个玩家，一个玩家一个channal会不会很浪费。比如这个值是金钱，每个玩家的金钱都不同，而且一定时间会自动增长。。。。。有点迷茫。。。

**Comment by changchang** [comment]
pomelo客户端会维护着一个socket.io的连接，所有的request和notify都是通过这个连接和服务器通讯的，所以不会出现一个request建立一个长连接的问题。至于底层到底是用websocket还是long-polling的形式实现，这是由socket.io根据浏览器环境来选择的。

单个push的话，channelService上提供有专门的push接口pushMessageByUids，具体可以参考我们的api文档和[框架参考](https://github.com/NetEase/pomelo/wiki/Pomelo-Framework)关于channel部分的章节。
