### ISSUE TITLE
新版的pomelo的jsclient用那个。

### ISSUE THREAD

**Issue by chenyl107** [NetEase/pomelo-cn#121]
用新版的pomelo init出来的工程web-server里的是build.js，如果不用pomelo的web-server，应该用那个js库。

**Comment by demon0925** [comment]
两个js-client分别对应socket.io和原生的websockt，如果需要多浏览器兼容用socket.io的，如果在意性能和流量就用原生的websocket。
socket.io走的是文本传输，兼容性较好。
websocket用的是二进制传输，而且会用到最新的数据压缩协议，传输效率更高。
