### ISSUE TITLE
关于component.sh的问题

### ISSUE THREAD

**Issue by chenyl107** [NetEase/pomelo-cn#123]
看了下component.sh：
cd public/js/lib && component install -f && component build -v
执行的时候会说public/js/lib不是一个文件或者目录，改成
cd ../public/js/lib && component install -f && component build -v后就可以了。
。。。。
额。。还有就是问下，这个sh文件是我们自己去执行的还是pomelo会自动帮我们去执行。我一开始没有执行，项目也能跑，执行后的作用是神马?

**Comment by xiecc** [comment]
嗯， 这是component的build， build完后生成完整的客户端javascript库。
不过目前我们已经在新建项目时默认build了一个， 所以可以跳过这步

**Comment by fantasyni** [comment]
这个是在lordofpomelo中，为了便于开发，在web-server目录的bin文件夹下面，有一个 component.sh web-server目录下执行命令，即可完成install和build客户端代码的工作  
具体详情还请到 [component](https://github.com/component/component) 上去了解
