### ISSUE TITLE
请问，cocos2d-x版的客户端的进度

### ISSUE THREAD

**Issue by zpbaaa** [NetEase/pomelo-cn#124]
在0.3的新特性说明中说到会提供新的C客户端， 支持cocos2d-x。请问一下这个客户端的进度到百分之几了？

**Comment by liketo** [comment]
同问。
发现个https://github.com/NetEase/libpomelo， 不知道 是不是

**Comment by demon0925** [comment]
恩 是这个，现在在调试和文档补充阶段，你们可以骚扰@changchang
