### ISSUE TITLE
求官方建个官方QQ技术群

### ISSUE THREAD

**Issue by liketo** [NetEase/pomelo-cn#126]
求官方建个pomelo技术群，你们没时间可以在里面潜着，号召下建起来就行，我们这样的新手有问题好能实时的问问，交流交流，也可以讨论些问题，啥小问题都来这发帖真不太合适

**Comment by liketo** [comment]
不用你们在群里解决问题，现在pomelo还比较新，用的人还不是很多，我们自己建个群的话，很难把用pomelo的人聚集到一起

**Comment by xiecc** [comment]
292495320  这个QQ群可以加一下， 上面有不上人，我们晚上会上去看一下

**Comment by liketo** [comment]
O了，谢谢
