### ISSUE TITLE
这个框架的注释能不能加些参数类型注释？

### ISSUE THREAD

**Issue by sonygod** [NetEase/pomelo-cn#127]
类似express这样
- @param {Number} size
- @return {Array}
- @api public
  */

req.range = function(size){
  var range = this.get('Range');
  if (!range) return;
  return parseRange(size, range);
};

发现pemelo代码里面很少对参数类型有注释，用其他工具生成的的读得很吃力。

**Comment by sonygod** [comment]
哦，刚才补看下，有些有，有些无，希望改进

**Comment by xiecc** [comment]
谢谢， 我们会花时间补上去的
