### ISSUE TITLE
iOS client编译时候报错

### ISSUE THREAD

**Issue by chenyl107** [NetEase/pomelo-cn#13]
pomelo.m中
id data = [packet dataAsJSON];
这一行报Receive type 'SocketIOPacket' for instance message is forward declaration
好像和ARC有关。
刚开始学iOS NetWorking部分，这一部分的开源框架还不怎么熟，pomelo依赖的socketIO-objc这个框架依赖的json-framework是否需要加入（pomelo-ios没有提到这个）如果要加入的话要加那些文件，这个框架文件夹很多。。。
![testPomelo](https://f.cloud.github.com/assets/2864311/29935/d2aa96f8-4dee-11e2-83e3-ff5a82b40a23.png)
![QQ20121225-2](https://f.cloud.github.com/assets/2864311/29936/d993bc10-4dee-11e2-9057-9916dba4a165.png)
PS：求公平对待，来个iOS demo。。。

**Comment by numbcoder** [comment]
iOS5 之后已经加入了 JSON 的支持，如果你的编译环境是 iOS 5 + ，那么不需要依赖第三方的 json-framework 的。
不好意思，我刚刚发现，socket.IO-objc 最近有个大更新，貌似 API 有所变化。这个我需要跟进，稍后给你回复。
demo 也会有的。: )

**Comment by chenyl107** [comment]
嗯，好

**Comment by numbcoder** [comment]
@chenyl107 版本已更新，可以用了。
具体用法可以看一下 Readme

**Comment by chenyl107** [comment]
@numbcoder 嗯，好。对了，我想知道我现在本机上的pomelo版本和github上的pomelo版本的差异要怎么看，刚看到rpc子框架2小时前更新过了，
