### ISSUE TITLE
关于服务器的物理配置

### ISSUE THREAD

**Issue by liketo** [NetEase/pomelo-cn#130]
呵呵，看到文档中只有服务器的逻辑架构，物理结构木有，对于一些老鸟肯定没问题了，像我这样的新手就搞不明白，那些服务器的物理结构改怎么配置合理，希望大神们能在写逻辑架构同时配上建议的物理结构，比如，哪个和哪个放一台物理机器上对性能更好

**Comment by xiecc** [comment]
物理配置不属于文档范围。
随着应用场景不同， 物理配置也完全不同。而且有可能是云环境， 也可能都是物理机。
如果只是保证性能， 根据实际负载情况分配进程就好。
如果把高可用，高并发什么的都考虑进去就复杂了

**Comment by liketo** [comment]
好吧，SQSQ
