### ISSUE TITLE
网易的大神，调试时除了app.js有，别的怎么都没了？

### ISSUE THREAD

**Issue by liketo** [NetEase/pomelo-cn#131]
网易的大神，用eclipsse调试pomelo时除了app.js在资源管理器中有，别的js文件（hander,remote)怎么都没了，是不是被你们搞到别的地方了？搞没了怎么调试hander里的代码呀

**Comment by xiecc** [comment]
pomelo是多进程架构， 断点可能会设到另一个进程上。
建议修改servers.json， 每类服务器只留一个进程。

2013/3/19 liketo notifications@github.com

**Comment by liketo** [comment]
哈哈，谢谢

**Comment by liketo** [comment]
啊，可是我要找的那个代码是gateHander，这个是只有一个的呀
是不是 node --debug app.js , 这个只是主进程会用debug模式启动，其它进程不是debug模式，是正常启动的？

**Comment by liketo** [comment]
还有个小问题   ，pomelo start是正常启动，debug启动是不是只有用node -debug app.js了？ pomelo start一样的启动方式有提供 debug吗

**Comment by liketo** [comment]
已解决，参考
#137
