### ISSUE TITLE
问个愚蠢简单的问题

### ISSUE THREAD

**Issue by liketo** [NetEase/pomelo-cn#134]
例如 handler.enter函数中有这样一行
session.push('rid', function(err){});
  我想看看push函数的定义，找来找去也找不到，pomelo库中有个session.js中也没有，类似的我该怎么用什么方式才能找到函数的定义呢？

**Comment by py8765** [comment]
参考[localsessionservice](https://github.com/NetEase/pomelo/blob/master/lib/common/service/localSessionService.js)

**Comment by liketo** [comment]
谢谢
