### ISSUE TITLE
提交一个bug!

### ISSUE THREAD

**Issue by liketo** [NetEase/pomelo-cn#135]
chatofpomelo 示例中
connector 中handler.enter 函数中
self.app.rpc.chat.chatRemote.add(session, uid, self.app.get('serverId'), rid, true, function(users)
与函数原型参数不匹配
原型：ChatRemote.prototype.add = function(uid, sid, name, flag, cb)

**Comment by py8765** [comment]
session参数是在rpc调用时必须传的，session参数在框架中进行了处理，到后端服务器就不需要写出来。
