### ISSUE TITLE
安装完lord of pomelo之后，启动game-server和web-server无法进行注册

### ISSUE THREAD

**Issue by zx135795** [NetEase/pomelo-cn#136]
如题，在注册的时候 web-server端会出现这个code：undefined,msg:'connect etimedout'，请问大概会是什么原因造成的呢？求解答，谢谢了

**Comment by demon0925** [comment]
这个报的是连接超时，看看mysql.json里面数据库的配置是否正确？

**Comment by zx135795** [comment]
就是这个原因，是数据库的配置错了，非常感谢
