### ISSUE TITLE
WebStorm 调试 Pomelo . (Pomelo Debug With WebStorm IDE)

### ISSUE THREAD

**Issue by ETiV** [NetEase/pomelo-cn#137]
## [新版本请至此处查看](https://github.com/NetEase/pomelo/wiki/%E4%BD%BF%E7%94%A8-WebStorm-IDE-%E8%B0%83%E8%AF%95-Pomelo-%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F)

---

*\* 因为我也才接触Pomelo 不过48小时, 以下以 chatofpomelo 为例

经群里Mr.Lee兄弟点播, 看到了这个帖子
http://stackoverflow.com/questions/10354879/how-can-i-use-webstorm-to-debug-my-node-application-across-multiple-processes/10361373

得知, 只要在新开child_process时, node 命令参数中加入 '--debug=$port' 就可以使子进程开启调试监听端口.

不用修改源代码了，直接在配置文件中插入下面的配置即可：
![debugging configuration](https://f.cloud.github.com/assets/1926860/305576/51378844-965d-11e2-9608-5fb234baf433.png)

<del>* 所以在 pomelo (版本: 0.3.1) 中找到了新开child_process的入口, game-server/node_modules/pomelo/lib/master/starter.js, Line 43:
............................
</del>

这里改动后
- 再去WebStorm中增加若干个"Node.js Remote Deubgging"配置

![WebStorm Remote Debug Config](https://f.cloud.github.com/assets/1926860/277097/328f845a-90bd-11e2-8175-59d281f613c5.png)
图中显示Connector的Remote Deubgger 连接到 127.0.0.1:8787 端口. 与服务器配置文件中的条目遥相呼应.
## 代码修改, 及相关配置到此结束
1. 运行game-server. (WebStorm中配置为 node app.js env=development, CWD=b..l..a..h/game-server)
2. 会看到 Console 中记录了 
   <pre>...... Executing cd F:\git\chatofpomelo\game-server && node --debug=8787  F:\git\chatofpomelo\game-server\app.js ......
   ...... Executing cd F:\git\chatofpomelo\game-server && node --debug=8788  F:\git\chatofpomelo\game-server\app.js ......
   ...... Executing cd F:\git\chatofpomelo\game-server && node --debug=8789  F:\git\chatofpomelo\game-server\app.js ......
   ......
   ......
   ...... debugger listening on port 8787 ......
   ...... debugger listening on port 8788 ......
   ...... debugger listening on port 8789 ......
   </pre>
   说明调试端口打开成功.
   ![game-server launch log](https://f.cloud.github.com/assets/1926860/277152/8804e9ba-90be-11e2-81c6-bdf6563f880c.png)

注意亮蓝色中的内容. 深红色圆圈内的忽略. 因为写入到配置文件中, 所以会直接输出到这里. 其实再增加一行代码就可以去掉了.
3. 此时, 再从运行/调试配置的下拉栏中, 选择刚刚配置的几条Remote Debugging配置.
4. 选择好后, 点击后方的臭虫(Debug)按钮. 你就可以看到 Debugger 标签中, 显示有 <code>Connected to 127.0.0.1:8787</code> 的字符提示.

![Debug Window](https://f.cloud.github.com/assets/1926860/277178/14a31e6e-90bf-11e2-8768-36d4389e7132.png)
1. 之后便可以在 诸如 gateHandler.js, entryHandler.js, chatRemote.js, chatHandler.js 中的各方法代码中插入断点. 然后去页面上做一下触发断点的操作.
2. 切换回WebStorm. 如果一切安好的话, 天便晴了. :)
   ![webstorm debugging pomelo child process](https://f.cloud.github.com/assets/1926860/277222/f6c87dd4-90bf-11e2-8348-acf639d1b3df.png)

*\* 目前我发现的, 有一个小"毛病". 如果长时间调试的话, 主程序会报一个timeout的错. 直接使得程序异常退出. 眼下还没有去找如何调整这个设置.

第一次在github上写东西. markdown什么的更是不懂了.
希望借此能够抛砖引玉. 使得Pomelo项目不仅易于开发, 更加易于调试.

**Comment by liketo** [comment]
哈哈，太好了！

**Comment by py8765** [comment]
赞~

**Comment by fantasyni** [comment]
赞~~~~~

**Comment by GeforceLee** [comment]
我在mac上遇到你昨天说的问题（我是Mr.Lee）  只能调试一次 再试就不好使了

**Comment by ETiV** [comment]
@GeforceLee 
应该就是我说的timeout了。

app.js 里有一个filter, 我昨晚后来就睡下了，没试。
你可以注释掉这行试试。按语义来讲，应该不会出timeout了。

<pre>
// filter configures
    app.filter(pomelo.timeout());
</pre>

**Comment by jiangzhuo** [comment]
大赞！

**Comment by xiecc** [comment]
赞， 其实--debug参数可以直接配置在servers.json文件的args参数里

**Comment by ETiV** [comment]
@xiecc 
OK! 看到了. 太牛掰了

**Comment by qumeta** [comment]
got it

**Comment by lg-john** [comment]
我在 servers.json中家了  "args":"--debug=32311"  怎么还是无法调试啊

**Comment by xiecc** [comment]
https://github.com/NetEase/pomelo/wiki/%E4%BD%BF%E7%94%A8-WebStorm-IDE-%E8%B0%83%E8%AF%95-Pomelo-%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F

**Comment by sonygod** [comment]
hello,按照教程，我发现只能在gateHandler.js里面的断点有效果，其他的hander无效果？why?
了解后，发现还要在其他配置里面加上---debug..OK
