### ISSUE TITLE
 Pomelo若干问题请教

### ISSUE THREAD

**Issue by enginespot** [NetEase/pomelo-cn#138]
1.Pomelo通讯协议有握手部分不是很明白，socket.io是基于http的,为什么要在通讯协议中再定义一次握手
2.Pomelo connector中实现了两个socket
一个是hybridsocket 一个是siosocket 这两个用途不一样还是别的原因
3.lordofpomelo中服务器端的文件目录结构是按照什么规则分类的，lordofpomelo中有个domain文件夹，这个文件夹代表什么意思

谢谢

**Comment by liketo** [comment]
socket.io需要握手升级http协议
domain中是游戏逻辑的主要部分
（注：本人新手，言论不靠谱）

**Comment by demon0925** [comment]
恩，是的，游戏逻辑基本都在这里。

2013/3/20 liketo notifications@github.com

**Comment by demon0925** [comment]
1，socket.io并不一定是基于http的，在支持websocket的浏览器上用的是websocket，而一些客户端上用的可能是其他长连接协议。觉得对于长连接协议来说，http协议实在是下下之选，只是在不得已的时候作为兼容只用。
在Pomelo中，我们使用socket.io肯定是用的websocket。
我们使用socket.io的时候没有握手的，只有使用websocket的时候用的。
2，这两个socket是为了同时兼容多种协议做的，在这里就是socket.io和websocket。

**Comment by enginespot** [comment]
就是说 
在pomelo 中hybridsocket 是针对不支持websocket 浏览器而设计的
siosocket是针对支持websocket的浏览器才设计的
是这个意思么

**Comment by changchang** [comment]
siosocket底层是使用socket.io，支持使用socket.io的客户端。
hybridsocket底层混合了socket和websocket，支持socket客户端和原生的websocket客户端。

**Comment by changchang** [comment]
Pomelo中的握手和底层通讯协议的握手的目的不一样。Pomelo的握手主要是提供一个机会供服务器和客户端在底层连接建立后进行一些初始化数据交换。比如：客户端的版本号，协商心跳间隔，传递字典压缩和protobuf定义数据等等。
