### ISSUE TITLE
急！不同场景玩家如果有个公共活动该如何设计结构比较合适呢？

### ISSUE THREAD

**Issue by liketo** [NetEase/pomelo-cn#139]
拿lord of pomel举例，比如有个活动，需要分散在3个area中的部分玩家共同去个特殊的地图去进行，结构改如何设计比较合理呢， 如果像chat那样再加个 ”特殊服务器“，然后通过rpc调用完成，这样会不会开销太大，还有什么更合理的方式吗？

有个前提，就是参加这种活动的人数比较多

**Comment by demon0925** [comment]
你这个应该就是”副本“概念了，建议的设计思路是：
1，一个副本就相当于一个特殊的场景，所以建议建立专门的副本服务器，上面可以根据玩家的需要启动，关闭副本实例，这需要一个专门的逻辑来管理。
2，所以当玩家进入副本时，可以通过切换场景操作进入副本，之后这些玩家的任何操作都是场景内的操作了。
3，因为副本服务器压力较小，建议可以采用单服务器对应多个副本的方式。
4，副本服务器可以在开始时默认分配一些，pomelo 0.3里加入了动态添加服务器的功能，可以在运行时根据负载来添加，减少服务器实例。

在 2013年3月20日下午1:11，liketo notifications@github.com写道：

**Comment by liketo** [comment]
谢谢
