### ISSUE TITLE
iOS client编译时候报错2

### ISSUE THREAD

**Issue by chenyl107** [NetEase/pomelo-cn#14]
构建了最新版本的ios client，编译的时候报expected a property attribute before 'unsafe_unretained'
![pomeloios1](https://f.cloud.github.com/assets/2864311/30458/5bead768-4e92-11e2-9a1a-eb3a5aaba282.png)
Compiler是LLVM GCC 4.2 ,Compiler改成Apple LLVM compiler 3.1
报Apple Mach-O Linker (Id) Error
![pomeloios2](https://f.cloud.github.com/assets/2864311/30461/7be8147a-4e94-11e2-90cd-ff2c9f088699.png)
Xcode版本4.3.1，ios5.1

**Comment by chenyl107** [comment]
好奇怪，我用socketIO-objc整个app打开然后加入他依赖的socketRocket和SBJson然后添加pomelo的文件，测试pomelo connect方法没有报错，可以成功。。然后自己新建一个项目，导入所需文件的话就会报错。。。。

**Comment by numbcoder** [comment]
这个应该是有些文件没有加入到编译环境中。
在 Build Phases 中 Complie Sources 中看一下，是不是所有依赖都在里面。
还有，socketRocket 也是需要几个 lib 依赖的，你加入进去了么？

**Comment by chenyl107** [comment]
Compile Sources都加进来了 有120个items，
SocketRocket中包含的以下文件：
![111111](https://f.cloud.github.com/assets/2864311/30910/4ff55ce2-4f39-11e2-81de-201594ac735f.png)

**Comment by numbcoder** [comment]
能跑起来么？
`.h` 文件是不需要加进 Compile Sources 的。

**Comment by chenyl107** [comment]
都是.m文件，跑不起来。还是报上面的错误。

**Comment by chenyl107** [comment]
我二了，没有把相关的lib加进来。
![chenyl](https://f.cloud.github.com/assets/2864311/30982/51f474ce-4f43-11e2-86b0-b8efc22be0f2.png)
加进来后报以下错误：
![chenyl2](https://f.cloud.github.com/assets/2864311/30983/7c639faa-4f43-11e2-990b-78de227e7854.png)
