### ISSUE TITLE
Pomelo Chat 小修改了一下

### ISSUE THREAD

**Issue by ETiV** [NetEase/pomelo-cn#148]
这些天有空了一直在研究chat demo.

[这是我修改的版本](https://github.com/ETiV/chatofpomelo)

默认的没法使用除了`127.0.0.1`的IP访问. 所以改成支持公开聊天.
要不然聊天"服务器" 也没啥意义了嘛.

公开聊天的配置方法:

clone 回去后, 打开 `game-server/config/servers.json`. 你会看到一些 `"clientHost":"127.0.0.1"` 的配置条目. 将所有的 `"clientHost"`键所对应的值, 改成你自己服务器的IP地址. 比如`192.168.1.140`什么的. **填你自己服务器的IP**
然后启动game, web服务器. 虽然web服务器提示"你可以打开 127.0.0.1:3001". 但实际上你也可以打开你服务器IP:3001. 比如`http://192.168.1.140:3001`. 浏览器打开后, 便可以支持公开环境下的聊天了.

修改原理:
客户端首先连接 `gate` 服务器来获取 `connector` 的连接配置.
而默认情况下, `gate` 只返回了 `connector` 配置条目下的 `host` 值作为连接IP. 而`host` 都是`127.0.0.1`. 所以即便在公开环境下你可以直接使用服务器的IP打开网页. 但是 `gate` 依旧返回了 `127.0.0.1` 作为连接IP. 而你客户端并不一定开通聊天服务器. 故而连接不上.

这里除了修改配置文件中的相关内容. 还修改了 `gateHandler.js` 中的相应方法. 让其返回`clientHost`. 便可对外服务了.

我这里, Win8 64位, CentOS 6.2, 树莓派(基于Debian的Raspbian “wheezy”. _纯折腾, 很慢就是了..._), Mac OS X Mountain Lion 全都可以跑的通.

Windows 下, 我这里的node使用的是 msi 安装. **node 并不需要从源代码安装**.
但 Visual Studio 2010 我是安装了的.

看大家最主要的问题就是安装各种依赖包. 因为安装依赖包的时候不仅安装了pomelo, pomelo的依赖也被安装了. 我看里面有`redis`, `v8-profiler`, 貌似这些都需要经过编译. 所以提示`vcbuild.exe 无法找到. 请安装VS2008...`这类的错误提示的, 可以参考以下内容.

我忘了在哪个帖子看见的. 其实很简单.

> 可以从VS2010的`"工具" - "Visual Studio工具提示"`进入CMD中.
> 
> 再 cd 到 pomelo 创建的项目下. 再从此分别进入`game-server`, `web-server`并执行`npm install -d`.
> 
> 稍等片刻. 就会有安装了什么包的提示. 到这里就安装成功了.

![pomelo 项目依赖安装完成 on Windows](https://f.cloud.github.com/assets/1926860/290449/769893bc-92e3-11e2-8c99-fc295cd76dcf.png)

Windows 就是这样. 所以最简单的还是用Linux. OS X 也还是需要下载庞大的XCode, 再从里面安装 Command Line Tool.

**Comment by py8765** [comment]
赞~

**Comment by ETiV** [comment]
通读了一下starter.js

发现默认的代码没有问题. 只需要修改配置下的 "host" 键, 写成本机的对外IP就可以了. 不需增加 "clientHost".

**Comment by tennessine** [comment]
赞
