### ISSUE TITLE
如何让自定义服务器使用RPC

### ISSUE THREAD

**Issue by gongxinheng** [NetEase/pomelo-cn#15]
我在lordofpomelo的基础上新加入了一个combat server。工程目录app/servers下新建了combat文件夹，该目录下有remote文件夹，remote文件夹内有combatRemot.js，内容如下：
var utils = require('../../../util/utils');
var exp = module.exports;
exp.calCombat = function(args, cb){
    var param = args.param;
    utils.invokeCallback(cb);
};

game-server/app/servers/area/handler/playerHandler.js
handler.enterScene中加入了
pomelo.app.rpc.combat.combatRemote.calCombat(session, {param:"test"}, null);

app.js中加入了
app.route('combat', routeUtil.combat);

routeUtil.js中加入了
exp.combat = function(session, msg, app, cb) {
    var serverId = areas[session.get('combat')];

```
if(!serverId) {
    cb(new Error('can not find server info for type:' + msg.serverType));
    return;
}

cb(null, session.frontendId);
```

};

但是测试时发现combat进程里
exp.calCombat = function(args, cb){
    var param = args.param;
    utils.invokeCallback(cb);
};
始终没有执行到。
routeUtil.js可以断点断到exp.combat中，这是为什么呢？我还缺少了什么步骤吗？顺便问问能详细解释下
app.route的作用和原理吗？谢谢

**Comment by changchang** [comment]
是否有在config/servers.json中加上combat服务器的配置呢？框架会根据这个配置启动和维护各个类型服务器的进程。如果没有配置，则不会有combat服务进程，rpc调用就会失败。

app.route是一个让游戏开发者可以定制路由规则的渠道。因为请求的路由规则可能和具体的游戏规则相关，所以要有机制让外面的开发者定制他们自己的路由规则。具体的原理可以参考[pomelo框架参考](https://github.com/NetEase/pomelo/wiki/Pomelo-Framework)中关于RPC的章节内容。

**Comment by changchang** [comment]
顺便提醒一下，在你的代码里看到有从`session`里get一个`combat`属性。需要注意的是在handler中set的属性之后，需要调用`session.push/pushAll`进行同步，否则会出现get不到的情况。具体代码可以参考lordofpemelo中的`connector/entryHandler.js`，[API文档](http://pomelo.netease.com/api.html)的LocalSession的说明以及框架参考的session小结的内容 :)

**Comment by gongxinheng** [comment]
config/servers.json 有加上，进程也成功启动了，因为挂接调试器是可以成功挂上的
server.json配置如下
        "combat": [
            {"id": "combat-server-1", "host": "127.0.0.1", "port": 5001, "area": 1, "args":"--debug=10001"}
        ],

**Comment by changchang** [comment]
可以打印一下`var serverId = areas[session.get('combat')];`的结果，看看所得的serverId是否就是目标的combat服务器的id？

后面的代码`cb(null, session.frontendId);`把`frontendId`作为路由计算的结果返回了，这样请求会被路由给前端服务器，而不是combat服务器了。

**Comment by xiecc** [comment]
combat server是根据场景分区的吗？ 作用是什么？

2012/12/26 changchang notifications@github.com

**Comment by gongxinheng** [comment]
不好意思~之前没弄清楚routeUtil里面写的方法的作用，只是照搬了个。现在好了~
现在改成这样调用了
    var combats = pomelo.app.getServersByType('combat');
    if(!combats || combats.length === 0) {
        next(null, {code: Code.AREA.FA_NO_COMBATSERVER_AVAILABLE});
        return;
    }
    session.set('combatID', combats[0].id);
    session.set('playername', player.name);
    session.set('playerId', player.id);
    session.pushAll(null);
    pomelo.app.rpc.combat.combatRemote.calCombat(session, {param:"test"}, null);

routeUtil改成这样了
exp.combat = function(session, msg, app, cb) {
    var serverId = session.get('combatID');

```
if(!serverId) {
    cb(new Error('can not find server info for type:' + msg.serverType));
    return;
}

cb(null, serverId);
```

};

我这里的combat server是计算战斗的服务器，因为我们是回合制游戏，而且一场战斗数据都是一次性计算好让客户端播放录像的。所以战斗服务器也会有很多个，以后再做扩展。
最后问下关于exp.combat = function(session, msg, app, cb) 函数内这里的cb(null, serverId);
跟这里的最后一个参数null有什么关系吗？
pomelo.app.rpc.combat.combatRemote.calCombat(session, {param:"test"}, null);

**Comment by changchang** [comment]
没有关系的。`combat`的cb主要的作用是返回目标服务器的id。`calCombat`是一个远程服务的方法，我们制定的规则，远程服务的实现第一个参数必须是session，最后一个参数必须是cb函数，这里如果不需要cb的话，可以传递一个null进去。

**Comment by xiecc** [comment]
牛逼， 我也明白了。 combat服务会记住前几个回合的状态， 所以计算时还要回到原来的combat服务器。
 因此用session记住服务器id就ok了，route算法这样写应该对了。

2012/12/26 changchang notifications@github.com

**Comment by gongxinheng** [comment]
那做远程调用的时候，这个cb是什么情况下调用呢？需要被调用方发送什么特定的消息吗？
pomelo.app.rpc.combat.combatRemote.calCombat(session, {param:"test"}, cb);

还有utils.invokeCallback(cb);这里这个invokeCallback又是调用哪个函数呢？

**Comment by changchang** [comment]
这只是作为rpc调用返回方式的一个封装而已，就当成本地方法的调用方式来调用就可以了。远程服务器调用cb传入返回参数，那么客户端的cb就会被触发并接收到相应的参数。简单的过程大致像下面这样的：

远程服务端代码：

```
yyService.add = function(num, cb) {
  cb(null, num + 1);
};
```

客户端代码：

```
app.rpc.xxx.yyService.add(session, 1, function(err, res) {
  // res === 2
});
```

两边的接口是差不多的，只是客户端调用的时候需要在第一个位置多加个session参数，并保证最后一个参数是cb。

`utils.invokeCallback(cb);` 是一个简单的工具方法，主要是检查cb是否是一个function，然后用后面的参数来调用cb而已。如果cb不是function就什么也不做。在不确定cb是否合法的情况下可以用这个来偷下懒，少些点重复的检查逻辑:)

**Comment by gongxinheng** [comment]
明白了！非常感谢！
