### ISSUE TITLE
关于pushMessage的问题。

### ISSUE THREAD

**Issue by totollo** [NetEase/pomelo-cn#150]
如果CHAT服务器有3个。用户A进入了服务器1，用户B进入了服务器2.
用户A使用pushMessage广播消息的时候用户B接收不到消息。
然后我发现Channel是跟服务器的。那样的话除非吧chatRemote独立做成一台服务器，否则不能实现全网广播消息。

求解～～～～～

**Comment by xiecc** [comment]
是的,我们demo里chat也是单独一台服务器. 不过全网广播的话可以直接调broadcast,不用建channel
