### ISSUE TITLE
像这样一个数据，在serverProtos.json中应该怎么定义？

### ISSUE THREAD

**Issue by yylol** [NetEase/pomelo-cn#153]
info: {
    "3-3" : [ 1, 1 ],
    "3-4" : [ 2, 3 ]
}

需要返回这样一个数据，在serverProtos.json中应该怎么定义

**Comment by demon0925** [comment]
'info' : {
  'repeated uInt32 3-3' : 1,
  'repeated uInt32 3-4' : 2
}

这个和protobuf里面的定义方法一样的，只是不需要package了。
这些array编码和嵌套array在lord的serverProtos.json里面都有示范的，可以去参考下。

2013/3/25 yylol notifications@github.com

**Comment by yylol** [comment]
你好，我没用过protobuf，我看过lordofpomelo中的serverProtos，没太懂，能把我给的那个info的例子直接写出来下吗，我参考参考，谢谢~

PS： 我的那个"3-3"这个key都不是固定的，个数和值都是可变的

**Comment by demon0925** [comment]
哦 对于变量名变化的情况，是不能用protobuf编码的，protobuf适合的是编码格式固定的情况。
你去了解一下protobuf就知道了，google-protobuf需要根据固定的编码格式生成代码的，如果key变化的话是无法处理的。
我们的pomelo-protobuf相对灵活很多，但也需要对原来的proto文件做下解析和分发，理论上是可以处理这种情况，但是代价会很大。

对于这种内容变化的消息，建议是不要采用protobuf编码了。
或者重构消息，组成适合protobuf编码的格式

**Comment by yylol** [comment]
谢谢，明白了，我去重新弄下数据格式
