### ISSUE TITLE
iosclient 疑问

### ISSUE THREAD

**Issue by ETiV** [NetEase/pomelo-cn#154]
[iosclient](https://github.com/NetEase/pomelo-iosclient) 好像有些时间没更新了。

看 @pomelonode 里面的 [jsclient](https://github.com/pomelonode/pomelo-jsclient-websocket) 说，websocket 压缩的更好，更适合于移动设备。

但我发现iosclient 好像还是用的 socket.io 的连接方式。

不知道 iosclient 何时能更新支持？

**Comment by demon0925** [comment]
恩是的，现在只有JS客户端和C客户端支持二进制数据传输。

iosclient和其他客户端正在开发中，预计最近这几周就会发布了。

**Comment by numbcoder** [comment]
iOS Client 现在的版本只能支持 pomelo 0.2 版本协议。
新版本正在开发中，将采用原生 Socket 连接，并且支持数据压缩！

**Comment by xuezier** [comment]
@numbcoder 新的版本在哪里，现在ios客户端完全不可用
