### ISSUE TITLE
关于数据压缩的问题

### ISSUE THREAD

**Issue by yylol** [NetEase/pomelo-cn#155]
如果我没有采用protobuf，直接以json数据传输，该数据有没有被压缩过？

**Comment by demon0925** [comment]
没有。

如果打开字典压缩是会做route字段的压缩。

如果使用websocket传输的话会被转换成二进制。

**Comment by yylol** [comment]
route字段的压缩是pomelo已经自己实现了呢？还是需要像protobuf一样写配置文件？

**Comment by demon0925** [comment]
route只要打开开关就自动对会对所有系统生成的route进行压缩，如‘area.playerHandler.attack'.

对于自定义的消息，如’onAttack','onMove'则需要加入自定义的字典进行压缩（可选），具体可参考：
https://github.com/NetEase/pomelo/wiki/Pomelo-%E6%95%B0%E6%8D%AE%E5%8E%8B%E7%BC%A9%E5%8D%8F%E8%AE%AE

**Comment by yylol** [comment]
明白了，谢谢哈，最后一个问题，我设置了connector: pomelo.connectors.hybridconnector，它会以什么协议进行数据传输（webcoket,falsh socket还是你们自定义的协议），或者是还要我在哪配置下呢？

**Comment by xiecc** [comment]
socket协议， 可以适配websocket， 所以叫hybrid
