### ISSUE TITLE
修改lordofpomelo-master项目里面的mysql.json的IP地址出现连接数据库异常

### ISSUE THREAD

**Issue by zx135795** [NetEase/pomelo-cn#158]
如题，我一旦把\shared\config\mysql.json文件里面的IP地址换成本地的IP，就会出现  msg: 'ER_HOST_NOT_PRIVILEGED: Host \'CHEN-PC\' is not allowed to connect to th
is MySQL server'这个异常，但是使用127.0.0.1的话就没有问题，求解

**Comment by piaohai** [comment]
你数据库只监听了127.0.0.1的端口吧

2013/3/27 zx135795 notifications@github.com

> 如题，我一旦把\shared\config\mysql.json文件里面的IP地址换成本地的IP，就会出现 msg:
> 'ER_HOST_NOT_PRIVILEGED: Host \'CHEN-PC\' is not allowed to connect to th
> is MySQL server'这个异常，但是使用127.0.0.1的话就没有问题，求解
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NetEase/pomelo-cn/issues/158
> .

## 

Name：Yao Piaohai
Tel：(0)15024452655
E-mail:piaohai@gmail.com

**Comment by zx135795** [comment]
在表单里面，我修改了监听的端口是本地IP的啊

**Comment by ETiV** [comment]
汗~~看到这个"CHEN-PC", 才想到.
俩方法, 选 1 吧. 简单.
1. 你把这个"CHEN-PC" 加到"Host"里. 再`flush privileges;`
2. MySQL 的配置文件里, 加上这么一行. 让服务器不反向解析你的IP. 然后重启服务器.

```
skip-name-resolve
```

**Comment by zx135795** [comment]
非常感谢各位的解答，修改了监听的IP之后，再把CHEN-PC加到Host里面之后，使用本地IP连接已经没有问题了，谢谢各位的热心帮助
