### ISSUE TITLE
关于pomelo的protobuf~

### ISSUE THREAD

**Issue by yylol** [NetEase/pomelo-cn#159]
如果我使用的是uInt32编码，实际传输过程中是统一都用了4个字节呢，还是底层做过处理，是多少字节就用多少字节传输？

**Comment by demon0925** [comment]
这个编码格式在protobuf协议里有标准的，这里的编码都是按照标准实现的。
基本是按照使用的进行编码，会多占用1bit的标志位，所以根据实际长度占用1～5bytes.

**Comment by yylol** [comment]
明白，再问个菜鸟问题，0.1这样一个浮点数会占用几个字节？

**Comment by demon0925** [comment]
float采用的是定长编码，都是4个字节，double是8个

**Comment by yylol** [comment]
刚刚测试了一个，传输一个22.5的浮点数，总共包的大小事2555B，我用js把22.5改为了Math.floor(22.5)，打印出来22.5的确是变为了22，但是传输的包还是2555B，这是什么原因？

是因为js没有真正改变数的类型？

**Comment by demon0925** [comment]
要修改proto吧，将类型改成uInt32才会按照这个进行编码。
如果不修改proto还是按照原本的float进行编码的。

**Comment by yylol** [comment]
我的测试是这样的：
我在proto中设置，比如说 required uInt32 num: 1
然后传输的时候传的值是num: 22.5，和num:22，结果包是一样大的，实际都是8字节

这是什么情况？

**Comment by yylol** [comment]
哦，我明白了，是因为底层先自动把22.5转化为整型22了，所以传输的时候都是整型，大小是一样的

**Comment by demon0925** [comment]
不知道你说的包指的是哪一层的包的大小。
如果要查看protobuf编码后的数据可以直接打印出编码后的buffer中的二进制码，不同类型编码差异很明显的。看大小的话也可以在这一层直接打出长度来。

protobuf是没有容错处理的，对类型，长度要求非常严格的，编码时候的任何错误都会导致解码失败。

**Comment by yylol** [comment]
好的，已经解决了，谢谢回答
