### ISSUE TITLE
pomelo 什么时候能支持windows下运行啊?

### ISSUE THREAD

**Issue by yishaoye** [NetEase/pomelo-cn#16]
如题......

**Comment by xiecc** [comment]
已经支持了， 明天上传代码，并将在wiki上详细说明使用方法。

**Comment by py8765** [comment]
pomelo已经支持windows下运行，具体可以参考[pomelo快速使用指南](https://github.com/NetEase/pomelo/wiki/pomelo%E5%BF%AB%E9%80%9F%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)，在github上下载pomelo的最新版本(>=0.2.3)。

**Comment by yishaoye** [comment]
![image](https://f.cloud.github.com/assets/2232296/42576/0431f24a-5635-11e2-8f33-85fba194fce8.png)
windows下安装报错.请问这个怎么解决?

**Comment by py8765** [comment]
pomelo的版本是不是0.2.3之后的？

**Comment by yishaoye** [comment]
我直接使用命令 node install -g pomelo 来安装的然后就报上面的错...

**Comment by py8765** [comment]
已经支持windows，满足下面两个条件：
1. Python(2.5<version<3.0)
2. VC++ 编译器，包含在Visual Studio 2010中（VC++ 2010 Express亦可）\
另外，所在目录名称最好不要有空格，pomelo版本（>=0.2.3）

**Comment by yishaoye** [comment]
使用 npm install -g pomelo 来安装的, 我电脑环境中 python版本是2.7.3  Visual Studio 2010; npm下载到的pomelo版本是0.2.4; 安装失败!!!

**Comment by py8765** [comment]
你的VS2010是否安装C++，然后能否把具体的错误贴出来？

**Comment by yishaoye** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Shao>npm install -g pomelo
npm http GET https://registry.npmjs.org/pomelo
npm http 304 https://registry.npmjs.org/pomelo
npm http GET https://registry.npmjs.org/seq-queue
npm http GET https://registry.npmjs.org/socket.io
npm http GET https://registry.npmjs.org/mkdirp/0.3.3
npm http GET https://registry.npmjs.org/pomelo-loader
npm http GET https://registry.npmjs.org/pomelo-rpc
npm http GET https://registry.npmjs.org/pomelo-protocol
npm http GET https://registry.npmjs.org/cliff
npm http GET https://registry.npmjs.org/crc
npm http GET https://registry.npmjs.org/pomelo-admin/0.0.18
npm http GET https://registry.npmjs.org/pomelo-monitor
npm http GET https://registry.npmjs.org/pomelo-logger/0.0.2
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/pomelo-sync
npm http 304 https://registry.npmjs.org/mkdirp/0.3.3
npm http 304 https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/pomelo-rpc
npm http 304 https://registry.npmjs.org/seq-queue
npm http 304 https://registry.npmjs.org/pomelo-loader
npm http 304 https://registry.npmjs.org/pomelo-protocol
npm http 304 https://registry.npmjs.org/cliff
npm http 304 https://registry.npmjs.org/crc
npm http 304 https://registry.npmjs.org/pomelo-admin/0.0.18
npm http 304 https://registry.npmjs.org/pomelo-monitor
npm WARN package.json pomelo-admin@0.0.18 No README.md file found!
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/pomelo-sync
npm http 304 https://registry.npmjs.org/pomelo-logger/0.0.2
npm http GET https://registry.npmjs.org/log4js
npm http GET https://registry.npmjs.org/pomelo-schedule
npm http GET https://registry.npmjs.org/v8-profiler
npm http GET https://registry.npmjs.org/socket.io-client
npm http GET https://registry.npmjs.org/stream-pkg
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/socket.io-client
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/socket.io-client/0.9.11
npm http GET https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/redis/0.7.3
npm http GET https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/log4js
npm http 304 https://registry.npmjs.org/v8-profiler
npm http 304 https://registry.npmjs.org/socket.io-client
npm http 304 https://registry.npmjs.org/pomelo-schedule
npm http 304 https://registry.npmjs.org/stream-pkg
npm http 304 https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/async/0.1.15
npm http 304 https://registry.npmjs.org/socket.io-client
npm http 304 https://registry.npmjs.org/eyes
npm http 304 https://registry.npmjs.org/socket.io-client/0.9.11
npm http 304 https://registry.npmjs.org/base64id/0.1.0
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/log4js

> v8-profiler@3.6.2-1 install C:\Users\Shao\AppData\Roaming\npm\node_modules\pom
> elo\node_modules\pomelo-admin\node_modules\v8-profiler
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/redis/0.7.3

C:\Users\Shao\AppData\Roaming\npm\node_modules\pomelo\node_modules\pomelo-admin\
node_modules\v8-profiler>node "C:\Program Files\nodejs\node_modules\npm\bin\node
-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
npm http 304 https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/async/0.1.15
npm http GET https://registry.npmjs.org/cycle
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/stack-trace
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm  profile_node.cc
 http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
  heap_profiler.cc
npm http  cpu_profiler.cc
 GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http GET https://registry.npmjs.org/ws
  graph_edge.cc
  snapshot.cc
  graph_node.cc
..\graph_node.cc(76): warning C4244: 'argument' : conversion from 'uint64_t' to
 'uint32_t', possible loss of data [C:\Users\Shao\AppData\Roaming\npm\node_modu
les\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vc
xproj]
..\graph_node.cc(84): warning C4244: 'argument' : conversion from 'uint64_t' to
 'uint32_t', possible loss of data [C:\Users\Shao\AppData\Roaming\npm\node_modu
les\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vc
xproj]
  profiler.cc
  profile.cc
npm http 304 https://registry.npmjs.org/log4js
..\snapshot.cc(90): warning C4244: 'argument' : conversion from 'uint64_t' to '
v8::SnapshotObjectId', possible loss of data [C:\Users\Shao\AppData\Roaming\npm
\node_modules\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\build\p
rofiler.vcxproj]
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http 304 https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/async/0.1.15
npm http 304 https://registry.npmjs.org/stack-trace
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http 304 https://registry.npmjs.org/cycle
     Creating library C:\Users\Shao\AppData\Roaming\npm\node_modules\pomelo\nod
  e_modules\pomelo-admin\node_modules\v8-profiler\build\Release\profiler.lib an
  d object C:\Users\Shao\AppData\Roaming\npm\node_modules\pomelo\node_modules\p
  omelo-admin\node_modules\v8-profiler\build\Release\profiler.exp
graph_node.obj : error LNK2001: unresolved external symbol "public: class v8::H
eapGraphNode const \* __cdecl v8::HeapGraphNode::GetDominatorNode(void)const " (
?GetDominatorNode@HeapGraphNode@v8@@QEBAPEBV12@XZ) [C:\Users\Shao\AppData\Roami
ng\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\b
uild\profiler.vcxproj]
graph_node.obj : error LNK2001: unresolved external symbol "public: class v8::H
eapGraphEdge const \* __cdecl v8::HeapGraphNode::GetRetainer(int)const " (?GetRe
tainer@HeapGraphNode@v8@@QEBAPEBVHeapGraphEdge@2@H@Z) [C:\Users\Shao\AppData\Ro
aming\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modules\v8-profile
r\build\profiler.vcxproj]
graph_node.obj : error LNK2001: unresolved external symbol "public: int __cdecl
 v8::HeapGraphNode::GetRetainersCount(void)const " (?GetRetainersCount@HeapGrap
hNode@v8@@QEBAHXZ) [C:\Users\Shao\AppData\Roaming\npm\node_modules\pomelo\node_
modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vcxproj]
graph_node.obj : error LNK2001: unresolved external symbol "public: int __cdecl
 v8::HeapGraphNode::GetRetainedSize(void)const " (?GetRetainedSize@HeapGraphNod
e@v8@@QEBAHXZ) [C:\Users\Shao\AppData\Roaming\npm\node_modules\pomelo\node_modu
les\pomelo-admin\node_modules\v8-profiler\build\profiler.vcxproj]
C:\Users\Shao\AppData\Roaming\npm\node_modules\pomelo\node_modules\pomelo-admin
\node_modules\v8-profiler\build\Release\profiler.node : fatal error LNK1120: 4
unresolved externals [C:\Users\Shao\AppData\Roaming\npm\node_modules\pomelo\nod
e_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:236:23)
npm gyp http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Shao\AppData\Roaming\npm\node_modules\pomelo\node_modules\
pomelo-admin\node_modules\v8-profiler
gyp ERR! npm node -v v0.8.14
http gyp304  https://registry.npmjs.org/ws
ERR! node-gyp -v v0.7.1
gyp ERR! not ok
npm http 304 https://registry.npmjs.org/async/0.1.15
npm WARN optional dep failed, continuing v8-profiler@3.6.2-1
npm http GET https://registry.npmjs.org/zeparser/0.0.5
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/tinycolor
npm http 304 https://registry.npmjs.org/options

**Comment by py8765** [comment]
http://pomelo.netease.com/chat/  
channel: pomelo
在这里解决你的问题吧

**Comment by py8765** [comment]
在windows下v8-profiler组件安装失败报错是正常的，不影响pomelo的正常使用，因为该组件是选择性安装。

**Comment by it114** [comment]
遇到了同样的问题 ？？？
