### ISSUE TITLE
关于缓存~

### ISSUE THREAD

**Issue by yylol** [NetEase/pomelo-cn#164]
1.  app.set是不是缓存一些全局变量，是缓存在所有服务器的吗？
2.  是不是这个和memcached类似，用这个就可以不用memcached了？
3.  如果是和memcached类似，有没有提供锁？

**Comment by changchang** [comment]
`app.set`只是在当前进程上下文进行缓存，进程间相互不可见的。

**Comment by yylol** [comment]
明白了，谢谢回答
