### ISSUE TITLE
Unitysocketio打包之后[Android，exe，html]无法与服务器连接

### ISSUE THREAD

**Issue by zhaoqingqing** [NetEase/pomelo-cn#168]
项目使用unitysocketio,作为通信连接，在本机测试是正常能够连接，收发数据，但是打包成APK或者exe，html之后，就不能与服务器连接，接收不到服务器的消息，请问大家有遇到这样的情况吗？
这是build界面
![build](https://f.cloud.github.com/assets/3056814/350264/57802c0a-a013-11e2-8bcd-5b69e5ee4c72.png)
这是playersetting界面
![playersetting1](https://f.cloud.github.com/assets/3056814/350266/652e45c6-a013-11e2-962e-04d5b8f9f2c4.png)
这是项目目录结构截图
![assets1](https://f.cloud.github.com/assets/3056814/350271/8296aad6-a013-11e2-89fb-a9e7a8883c72.png)

**Comment by halfblood369** [comment]
就一个unity文件么，这个unity是做什么用的？不会是和服务器的通信就做到这个初始化里面了吧……

**Comment by zhaoqingqing** [comment]
整个项目就一个场景，这个unity就是用unitysocketio连接nodejs,服务器用的nodejs

**Comment by zhaoqingqing** [comment]
这个unity是做客户端，服务器端是nodejs，通信用的unitysocketio，我把unitysocketio.dll放在plgunis目录下，在开发的环境下是可以正常接收服务器数据的，打包之后就连接不上服务器了，打成exe在本机也连接不上

**Comment by zhaoqingqing** [comment]
这是连接服务器的代码：
![conection1](https://f.cloud.github.com/assets/3056814/350408/1775fe9c-a01c-11e2-8b59-a0994a15eda1.png)
和服务器连接不写在初始化里面，写在另一个CS文件的start里面，这个CS文件就写了一个连接的方法，一直挂在update对象上面
代码如下：
![conection2](https://f.cloud.github.com/assets/3056814/350411/494d2bc0-a01c-11e2-8aaa-e1c58bb5f2fa.png)

**Comment by zhaoqingqing** [comment]
分了两个CS，一个updateScript，负责连接，在start里面写好URL，调用NetworkToServer进行连接，
NetworkToServer.cs负责处理服务器返回的数据

**Comment by zhaoqingqing** [comment]
![conection3](https://f.cloud.github.com/assets/3056814/350429/c651704a-a01c-11e2-8dd0-e86ae1fd22eb.png)

**Comment by halfblood369** [comment]
AysConnect这个方法什么时候调用的，在Update里面么？如果是的话就肯定有问题了，这是初始化的工作，在初始化的时候调用一次就行了。

**Comment by zhaoqingqing** [comment]
不是，是在start里同调用的，不是在update里面

**Comment by zhaoqingqing** [comment]
这个脚本一直挂在一个upate的gameobject上面，通用这个这脚本调用另一个脚本中的AysConnect方法，是在start里调用，不是在update

**Comment by halfblood369** [comment]
哦，看到了！既然打包前可以通信，那说明socket应该没问题。你是怎么确定没有收到消息啊？后端node有没有报错？

**Comment by zhaoqingqing** [comment]
后端NODEJS没有报错，因为如果客户端连接成功之后，会收到服务器发送过来的在线人数，我把数据显示在界面上，我打包之后显示不出来，然后我点击注册，服务器端没有收到我发送的消息

**Comment by zhaoqingqing** [comment]
打包之后，接收与发送都不行，我点击按钮，服务器端接收不到消息。
如果不打包，在unity中可以接收到客户端发过去的消息

**Comment by halfblood369** [comment]
我看你在编译的时候用的是zjh这个unity文件，那你的upate的gameobject和这个zjh什么关系呢？

**Comment by zhaoqingqing** [comment]
zjh.unity是场景文件，update的gameobject可以说是一直挂着updateScript.cs这个脚本

**Comment by halfblood369** [comment]
其实我是想知道你这个对象有没有放在场景中。这样吧，你把脚本(cs)直接挂在zjh.unity文件下进行编译，看看效果。

**Comment by zhaoqingqing** [comment]
这个对象肯定有放在这个场景中啦，我的项目总共就一个场景，脚本也是挂在这个场景中，我把连接和接收消息的脚本都挂在这个场景中

**Comment by zhaoqingqing** [comment]
![update1](https://f.cloud.github.com/assets/3056814/354926/3a556ffe-a0b9-11e2-8394-e84a732c4470.png)

**Comment by halfblood369** [comment]
你在socket.connect()之前做点处理，看看打包后这个方法是否被调用？
还有看看pomelo-unitychat这个demo例子，里面有两个场景login 和 chat，分布挂有LoginGUI和ChatGUI两个脚本，LoginGUI是登陆界面，负责初始化socket连接，并把socket连接传递个ChatGUI脚本，ChatGUI负责和服务器进行通信，发送和接收消息。

**Comment by zhaoqingqing** [comment]
可以打出来，在socket.connect()之前，可以打印出来
4/9/2013 11:48:00 AM Log - hello world! from LogGenorator.Log()
我使用了一个LogGenorator.cs的日志文件，可以监听到连接方法并可以打印出来，之后的内容就执行不了

**Comment by zhaoqingqing** [comment]
pomelo-unitychat这个Demo，我尝试了，在WINDOWS下没有运行起来，安装pomelo不成功

**Comment by zhaoqingqing** [comment]
我的所有数据处理都放在一个CS文件中，然后在这个文件中调用其它CS文件中的方法，在其它的CS文件中没有使用socket,都放在一个CS文件中，这个文件挂在update上面

**Comment by zhaoqingqing** [comment]
我再次打包，socket还是连接不上服务器，连接脚本一直挂在update(gameObject)上面

**Comment by halfblood369** [comment]
不知道你这个问题和你在邮箱里面给我发的问题是不是一个，如果是一个的话，那就是页面刷新和socket连接两个线程通信的问题了，所有有关页面刷新的逻辑和代码都在onGUI方面里面进行，通过公共变量等进行和socket线程通信，注意锁的保护。

**Comment by zhaoqingqing** [comment]
是同一个问题，我在邮箱里问你的和页面刷新，还有socket都是同一个项目中的问题，我做一个小demo测试一下，是否是所有的都需要放到OnGUI里面，谢谢你啦！

**Comment by duyanghao** [comment]
所以，这个问题的答案是什么？
