### ISSUE TITLE
关于lordofpomelo登录时的一点小疑问

### ISSUE THREAD

**Issue by yylol** [NetEase/pomelo-cn#169]
在connector的entry中，为什么要先app.get('sessionService').kick(uid, cb)，然后再session.bind(uid, cb)，请问下这是为何？

**Comment by halfblood369** [comment]
这是游戏中相同玩家不能同时登陆的要求决定的，后登陆的玩家会踢掉之前的……

**Comment by yylol** [comment]
明白了，谢谢回答
