### ISSUE TITLE
game-server 下 app.js 自启动 在哪实现的

### ISSUE THREAD

**Issue by shaniu00** [NetEase/pomelo-cn#17]
我在game-serve  下的    app.js 里面 console.log(Math.random()) ;  
node app.js 发现 打印了 不同数字     找不到 在哪里 重复 调用的该脚本 哦 
具体重复调用的 脚本 位置 能贴下吗   3Q3Q

**Comment by xiecc** [comment]
你是指多进程吗？
看一下 lib/master/starter.js   其实就是调node或forever命令启动app.js

2012/12/27 shaniu00 notifications@github.com

**Comment by py8765** [comment]
关于服务器的启动可以参考[pomelo启动流程](https://github.com/NetEase/pomelo/wiki/pomelo%E5%90%AF%E5%8A%A8%E6%B5%81%E7%A8%8B)。
