### ISSUE TITLE
谁能简单解释下这几个api的作用

### ISSUE THREAD

**Issue by yylol** [NetEase/pomelo-cn#170]
谁能精辟的概括下filter,before,after这三个方法的作用，谢谢了

**Comment by halfblood369** [comment]
filter是消息过滤器，目的是对客户端和服务器之间通信的消息进行过滤。before方法是对客户端的消息进行过滤，然后调用next方法进入到具体的Handler中对消息进行处理；after是对服务器返回给客户端的消息进行过滤，然后调用next方法发送给客户端。

**Comment by yylol** [comment]
意思很明了，能具体说下使用情况吗，比如说什么情况下使用？
就像lordofpomelo的app.js中，有这么几个地方使用了。
1.在全局设置内有app.filter( pomelo.timeout() )，这里是什么意思？
2.在area设置内，app.filter( pomelo.filters.serial() ); app.before( playFilter() );这里又是什么意思？

麻烦抽空回答下，谢谢了

**Comment by halfblood369** [comment]
消息过滤器在很多情况下可以使用，比如计算客户端请求的处理时间，对客户端请求进行检查，丢弃非法请求等。

1.app.filter( pomelo.timeout() )，这是采取pomelo提供的请求超时过滤器timeout，当处理时间超出默认时间时候给出警告。这里的这种用法可能有问题，应该用pomelo.filters.timeout()，我们会尽快核对并处理的。

2.app.filter( pomelo.filters.serial())，这是采取pomelo提供的请求串行化过滤器serial，对客户端的请求进行串行化，一定程度上可以保证请求的顺序执行，每个请求默认给3秒钟的处理时间，如果超出这个时间，给出警告。

3.app.before(playFilter())，这里采取的是用户自定义的过滤器playFilter，只有before方法。在pomelo中filter方法其实是对消息进行了before和after两种过滤操作。

**Comment by yylol** [comment]
很详细，谢谢回答！
