### ISSUE TITLE
关于lordofpomelo的chat服务器

### ISSUE THREAD

**Issue by yylol** [NetEase/pomelo-cn#171]
1. lordofpomelo例子中，在chatService中看到了add,leave等方法，中间通过app.get('channelService').getChannel( channelName, true )来获取channel对象，问题是：是在何时createChannel的？是有配置文件还是其他？
2. lordofpomelo这个例子中的chatRemote.js中没有send方法，如果我因为需求，需要在别的服务器上，直接向特定的玩家广播消息，是通过调用什么实现的？

谢谢网易同仁的细心回答！

**Comment by changchang** [comment]
1. 由`getChannel`的第二个参数决定。true表示`getChannel`的时候如果channel不存在则会创建，false表示不创建。
2. 可以通过`app.get('channelService').pushMessageByUids`来给特定玩家推送消息。

**Comment by yylol** [comment]
谢谢，了解
