### ISSUE TITLE
关于lordofpomelo的app.js中的几个问题

### ISSUE THREAD

**Issue by yylol** [NetEase/pomelo-cn#175]
在lordofpomelo的app.js中，请教几个问题。
1.async.waterfall中有两个参数，第一个数组和第二个cb，第二个参数的cb和数组中的function有什么区别？
2.在这个例子中使用了一个session.pushAll( cb )，请问这里使用它的作用是什么？
3.session.on( 'closed', onUserLeave.bind( null, self.app ) )，这局代码是不是用户离开的时候执行？这里的closed是pomelo提供的接口吗，还是需要用户离开时抛出closed信号？

谢谢回答

**Comment by halfblood369** [comment]
app.js里面没有你说的这些函数啊，请问是哪个文件里面的？

**Comment by yylol** [comment]
不好意思，不是app.js，是connecor下的entryHandler.js

**Comment by halfblood369** [comment]
1.这是async的基本用法，参见：https://github.com/caolan/async#waterfall 。
2. pushAll是把localSession的属性全部 同步到全局session中，源码参见 https://github.com/NetEase/pomelo/blob/master/lib/common/service/localSessionService.js 。
3.这里的＂closed＂是pomelo根据不同协议（socket.io、websocket、socket）的规范抛出的colsed事件，用户在离开的时候一般不需要主动抛出closed信号，因为该工作一般都会在socket.io等协议中封装好的。

**Comment by yylol** [comment]
谢谢，其他的都明白了，还有一处小疑问：

关于pushAll是把localSession的属性同步到全局session中。
1.为什么这里需要把localSeesion同步到全局session中了？
2.全局session和localSession有什么区别，这算不算是一种缓存？
3.那用户离开的时候，是不是需要主动去清楚这一块的缓存呢？

谢谢回答

**Comment by changchang** [comment]
`globalSession`用来缓存少量的用户基本信息（如：用户的id等），保存在前端服务器（如：connector服务器），对当前连接有效。`localSession`可以看成是`globalSession`的一个副本，在每次请求会从`globalSession`复制，连同请求一起forward给后面的服务器。`localSession`仅对当前请求有效。

在`localSession`上一般进行读操作，而写操作仅对当前请求可见。想要把`localSession`上的修改提升为全局可见，就需要同步到`globalSession`。

框架会在连接断开后把对应的session清理掉的。

**Comment by yylol** [comment]
谢谢，非常详细。

刚我测试了一下，session.on( 'closed', onUserLeave.bind( null, self.app ) )这个，当我直接关闭客户端时，没有执行onUserLeave，这是为什么呢，我客户端是c++的版本

**Comment by changchang** [comment]
是在什么服务器上调用`on`来绑定事件的呢？只有在连接所在的前端服务器上绑定才有效的。

**Comment by yylol** [comment]
是在connector中，找到原因了，加上pushAll就正常了

谢谢回答，问题都解决了，呵
