### ISSUE TITLE
关于pomelo的日志

### ISSUE THREAD

**Issue by peiweippww** [NetEase/pomelo-cn#179]
1.logs文件夹下，有如下几类log：con-log-connector.log, crash.log, 根据我的服务器类别，还会出现forward-log-----    node-log-----     rpc-log------     这三类，后面两个分别表示handler和remote目录下的log，这个比较好理解，forward-log---是表示哪里的log呢？
2.con-log-connector.log又表示哪里的log呢？
3.我代码为console.log，console.error，这些是不是都会出现在日志内？
4.既然console已经能输出日志了，logger有什么作用呢？

**Comment by halfblood369** [comment]
1.forward日志表示的是前端服务器的响应时间以及请求参数的日志。
2.con日志表示connector服务器处理请求时间等日志。
3.console打印的日志时会出现在日志中的。
4.logger打印的日志会按照一定的格式输出日志，而且支持时间回滚等log4j默认支持的功能，这些是console做不到的。
