### ISSUE TITLE
关于IPC组件的设计

### ISSUE THREAD

**Issue by wbpmrck** [NetEase/pomelo-cn#18]
各位好：

我们把之前的问题再接着讨论下去。之前changchang回复说了2点，我想进一步讨论一下：
1、client与client之间的类似聊天的通信

我这边是这样的，后台的逻辑处理进程(backend),是动态增加的，因为我的场景个数（房间）是可以动态由用户创建的。然后，有时候一个逻辑进程收到一个请求的时候，需要通知其他的逻辑进程做一些处理。典型的情况：用户打开2个浏览器标签，如果用户角色本来在场景A,而后打开的浏览器页面进入了场景B,我需要在后台做这样的处理：
a)负责场景B的逻辑进程，处理用户进入场景的操作
b)通知负责场景A的逻辑进程，做用户离开场景的处理

2、pomelo的后台进程之间是网状通信结构，这就意味着每2个互通的进程之间需要直接建立连接

这样的设计我的疑问是：如果后台进程比较多，那么岂不是每2个进程之间都要直接建立连接，这样一个是要配置很多socket端口，另外也没这个必要。
所以我是建立一个中心节点，然后所有后台进程(client)连接到这个节点。

我遇到的问题是，clientA需要通知clientB(其实是2个backend之间通信)，并受到clientB的回复，这个需要中心节点做一个转接，这个实现没有想好怎么做比较优雅一些。

我想了解一下pomelo的后台backend之间如何通信的？难道是一个做server，另一个做client，之间建立socket连接？

**Comment by changchang** [comment]
其实无论采用哪种模型，我归纳一下大概有这几点需要考虑的吧。
1. 各个服务进程之间怎么相互感知。
   这个就是我用聊天系统打的比方，一个服务进程加入了集群，需要把自己注册到集群中，就跟用户登录一样。然后就是各个服务进程需要知道集群里的进程信息，就是聊天的好友列表，无论是采用推还是拉的形式实现。进程间通讯也就是把聊天消息发给目标用户。
   像房间切换的功能需要有一个集中的地方（如：房间管理器）做协调，它感知到用户进入房价B的事件，同时也能查询到用户之前在房间A的状态。
2. 服务进程之间的连接怎么建立和管理。
   这个就是前面提到的网络拓扑的问题。每个模型都有自己的优点和不足，可以根据具体的需求做选择，这个在传统的MQ和zeromq之间的讨论也比较多，可以在网上搜一下。
   在lordofpomelo中的策略是依赖方向被依赖方建立一个连接。比如：A依赖B，则A建立一个到B的连接，把B当成server，在上面实现req/resp模式。也就是说如果A,B相互依赖的话，它们之间会建立起两个连接。连接的建立采用的是延迟建立的策略，也就是在发起第一个请求的时候才会去建立连接，而不是一开始每两个进程间都建立连接。
3. 底层的细节如何隐藏。
   优雅的关键，隐藏掉底层的细节，把公共的功能接口提取出来，对上层提供的是IRC的功能，而不是IRC实现的策略。这样以后即使要调整底层的策略，上层代码也不会受到影响。这也是我们设计RPC框架的目的。

**Comment by wbpmrck** [comment]
谢谢~我明白你说的意思了。

其实我是想能否不用在要互相通信的2个进程之间建立“实际的连接”，但是又可以向开发人员提供看上去像是“直接连接”的API,比如在work1的逻辑代码中，这样写：

IPC.sendToLogicWorker('worker2','userIn',{userID;1},function(error,data){
   //这里可以获得worker2的回复
   if(error)
     //blabla
    else 
      //blabla
   //data是worker2返回的数据
});

我现在是想用一个进程结点做server,然后所有的LogicWorker都作为client连接上去，这样无论有多少个client新增进来，对已有的其他client不会有改动（不需要直连）

**Comment by changchang** [comment]
> 其实我是想能否不用在要互相通信的2个进程之间建立“实际的连接”，但是又可以向开发人员提供看上去像是“直接连接”的API,比如在work1的逻辑代码中

这个其实就是我前面说的第三点隐藏底层的细节。我觉得采用聊天系统的模型是可以完成的，只是定义好节点之间的消息协议而已。

下面是一个思路，是否符合你所想表达的意思。

work1向worker2发起请求的过程

```
req = {src: 'worker1', dest: 'worker2', reqId: '1', body: 'req'}
worker1 -- req --> server -- req --> worker2 
```

work2向worker1返回响应的过程

```
resp = {src: 'worker2', dest: 'worker1', respId: '1', body: 'resp'}
worker2 -- resp --> server -- resp --> worker1
```

worker1经过sendToLogicWorker处理后，将src, dest, sid加上，body是具体请求的内容，形成req包，同时建立reqId到cb的映射关系，然后将包发给中心节点server，server根据dest转给worker2。

worker2获得req包后记录src, dest和reqId，将body丢给上层对应的处理函数（通过'userIn'可以知道是什么请求）。上层把data返回后，组成resp发给server，再转给worker1。

worker1取到resp后提取出data，根据respId找到对应的cb，触发回调。

**Comment by wbpmrck** [comment]
谢谢~
