### ISSUE TITLE
SessionService 中的sendMessage 客户端如何接受？

### ISSUE THREAD

**Issue by youxiachai** [NetEase/pomelo-cn#188]
文档里面只说了提供两个参数，一个uid，一个msg， 那么客户端是如何接受这个数据？

尝试想channel 那样在msg指定 route {route:"onMsg",msg:"helloworld"}

客户端：pomelo.on("onMsg", cb);

但是没有效果。

**Comment by changchang** [comment]
推送消息还是使用channel吧，`SessionService`不建议使用了，准备转成私有服务了。
