### ISSUE TITLE
0.4.2的心跳客户端主动断开，服务端有心跳超时提醒，但是，不调用closed 事件

### ISSUE THREAD

**Issue by youxiachai** [NetEase/pomelo-cn#189]
如果客户端是断网了，服务端虽然打印出了heartbeat的信息，但是，并不触发session closed 时间，只有那个客户端重连才会调用

等了heart \* 2的时间也是一样，只有等到断开的客户端重连才会调用session closed 事件

论坛也有讨论。
[http://nodejs.netease.com/topic/51b4b6c33e8b1fca032a5a3a#51b4f25d3e8b1fca032a7223](http://nodejs.netease.com/topic/51b4b6c33e8b1fca032a5a3a#51b4f25d3e8b1fca032a7223)

**Comment by xiecc** [comment]
我们再测试一下看

2013/6/10 youxiachai notifications@github.com
