### ISSUE TITLE
pomelo package.json 的疑问

### ISSUE THREAD

**Issue by chenyl107** [NetEase/pomelo-cn#19]
"dependencies": {
    "socket.io": ">=0.9.4",
    "pomelo-sync": ">=0.0.1",
    "async": ">=0.0.1",
    "seq-queue": ">=0.0.5",
    "crc": ">=0.0.1",
    "cliff": ">=0.1.8",
    "pomelo-loader": ">=0.0.4",
    "pomelo-rpc": ">=0.0.10",
    "pomelo-protocol": ">=0.0.3",
    "pomelo-admin": ">=0.0.17",
    "pomelo-monitor": ">=0.3.5",
    "pomelo-logger": "0.0.2"
  }

"devDependencies": {
    "should": ">=0.0.1",
    "mocha": ">=0.0.1",
    "socket.io-client": ">=0.0.1"
  }

这是pomelo源代码中package.json的依赖关系。为什么develop环境下只需要socket.io-client,should,mocha这三个框架。deploy里的依赖框架好像也是需要的呀，还是dev会自动依赖dep中的框架

**Comment by changchang** [comment]
devDependencies表示的是在开发环境里依赖的包，如：测试相关的依赖。其他人通过npm下载你的包的时候，不会把devDependencies里的包也下下来。可以参考[这里](https://github.com/isaacs/npm/blob/c6162070e3972f6e487774df811d6f435d5fa6f4/doc/json.md#devdependencies)。

**Comment by chenyl107** [comment]
呀，看走眼了，上面那个是dependencies，我以为是depdependencies。嗯。这样就懂了，thank you
