### ISSUE TITLE
api 文档ChannelService 中broadcast() 的描述不好

### ISSUE THREAD

**Issue by youxiachai** [NetEase/pomelo-cn#190]
ChannelService 中 opts 明明是一个对象，但是在ChannelService 源码里面标注的却是
- @param  {Boolean}  opts    却是一个boolean 类型？

明明 opts.binded，opts 有个binded 参数才为 boolean 类型。

描述太不清晰了。

而在线文档中，连opts 描述得binded 参数是什么类型都没有标注。

**Comment by xiecc** [comment]
嗯， 这个后来接口改了， 文档没跟上

2013/6/10 youxiachai notifications@github.com
