### ISSUE TITLE
pomelo 0.4.3 android sdk 不能用

### ISSUE THREAD

**Issue by youxiachai** [NetEase/pomelo-cn#192]
06-17 16:30:23.638: I/System.out(19637): [socket][12] connection /192.168.1.107:3010;LocalPort=32901(10000)
06-17 16:30:23.639: I/System.out(19637): [CDS]connect[/192.168.1.107:3010] tm:10
06-17 16:30:23.640: D/Posix(19637): [Posix_connect Debug]Process com.example.pomelo_push_demo :3010 
06-17 16:30:23.643: I/System.out(19637): [socket][/192.168.1.104:32901] connected
06-17 16:30:23.643: I/System.out(19637): [CDS]rx timeout:10000
06-17 16:30:31.815: I/System.out(19637): [CDS]EAGAIN or EWOULDBLOCK in Recvfrom
06-17 16:30:31.815: I/System.out(19637): [CDS]read byte is 0
06-17 16:30:31.818: W/System.err(19637): io.socket.SocketIOException: Error while handshaking
06-17 16:30:31.819: W/System.err(19637):    at io.socket.IOConnection.handshake(IOConnection.java:322)
06-17 16:30:31.820: W/System.err(19637):    at io.socket.IOConnection.access$600(IOConnection.java:39)
06-17 16:30:31.824: W/System.err(19637):    at io.socket.IOConnection$ConnectThread.run(IOConnection.java:199)
06-17 16:30:31.825: W/System.err(19637): Caused by: java.net.SocketTimeoutException
06-17 16:30:31.826: W/System.err(19637):    at java.net.PlainSocketImpl.read(PlainSocketImpl.java:495)
06-17 16:30:31.827: W/System.err(19637):    at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
06-17 16:30:31.828: W/System.err(19637):    at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
06-17 16:30:31.828: W/System.err(19637):    at java.io.InputStream.read(InputStream.java:163)
06-17 16:30:31.829: W/System.err(19637):    at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
06-17 16:30:31.829: W/System.err(19637):    at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
06-17 16:30:31.830: W/System.err(19637):    at libcore.io.Streams.readAsciiLine(Streams.java:201)
06-17 16:30:31.831: W/System.err(19637):    at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:561)
06-17 16:30:31.831: W/System.err(19637):    at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:814)
06-17 16:30:31.832: W/System.err(19637):    at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:293)
06-17 16:30:31.832: W/System.err(19637):    at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:185)
06-17 16:30:31.836: W/System.err(19637):    at io.socket.IOConnection.handshake(IOConnection.java:313)
06-17 16:30:31.836: W/System.err(19637):    ... 2 more
06-17 16:30:31.837: I/io.socket(19637): Cleanup
06-17 16:30:31.838: D/dalvikvm(19637): threadid=11: exiting
06-17 16:30:31.838: D/dalvikvm(19637): threadid=11: bye!
06-17 16:30:31.839: D/dalvikvm(19637): threadid=12: exiting
06-17 16:30:31.839: D/dalvikvm(19637): threadid=12: bye!

请求的步骤按照列子一样,服务端,用网页链接没有问题,但是用android sdk 就无法使用.,用手机自带浏览器访问也没问题.

**Comment by youxiachai** [comment]
只能用...
pomelo.connectors.sioconnector

不支持:pomelo.connectors.hybridconnector

麻烦更新一下sdk 的readme 说明一下.........

**Comment by youxiachai** [comment]
顺便问一下...android socket 版本的sdk 有时间表吗?

**Comment by py8765** [comment]
好的，readme会更新；android socket版本可能要下个版本吧。
