### ISSUE TITLE
pomelo 是否可以兼容所有浏览器

### ISSUE THREAD

**Issue by tudoukp** [NetEase/pomelo-cn#194]
pomelo 是否和socket.io一样可以支持

WebSocket
Adobe® Flash® Socket
AJAX long polling
AJAX multipart streaming
Forever Iframe
JSONP Polling

以兼容所有浏览器

还是这些客户端都需要我们自己来完成？

**Comment by xiecc** [comment]
基本都兼容， js客户端都有， 在我们wiki上可以到了。

不过我们在js客户端里需要编解码，有几个方法ie6是不支持的， 其它浏览都没问题
