### ISSUE TITLE
Pomelo可否做手机游戏的服务器？

### ISSUE THREAD

**Issue by SwordBearer** [NetEase/pomelo-cn#198]
公司一直使用PHP来手机游戏后端，但是个人对PHP不是很感冒，想请教一下，如果使用Pomelo来作为实时手机游戏后端效果如何呢？

**Comment by halfblood369** [comment]
很好很强大！国内已经有发布的游戏案例了，用pomelo搞的……

**Comment by xiecc** [comment]
好多公司都在用了， 有几个手机游戏已经上线了。

你可以来 http://nodejs.netease.com  讨论

2013/7/18 SwordBearer Tang notifications@github.com

**Comment by gonglei007** [comment]
To  halfblood369 和 xiecc: 能告诉一下游戏的名称或者地址吗？非常感谢！

**Comment by py8765** [comment]
你可以到pomelo 里的QQ群里问一下，群号：292495320。

**Comment by gonglei007** [comment]
好，谢谢。

Date: Sun, 25 Aug 2013 18:30:26 -0700
