### ISSUE TITLE
关于服务器远程调用的传参问题

### ISSUE THREAD

**Issue by gongxinheng** [NetEase/pomelo-cn#20]
我在某服务器用rpc调用另一个服务器的方法时直接传递了一个player对象过去。但发现在另外一端调用的时候发现这个player里面大部分属性都丢失了。是bug还是因为消息体太大被截断？感觉不像是被截断，大括号被截掉根本就语法错误了才对。

**Comment by changchang** [comment]
你是指lordofpomelo里的player吗？lord里面我们为了精简数据，是会去掉一些属性的。

**Comment by gongxinheng** [comment]
是的，那这部分精简在哪做的呢？我刚跟到socket底层解析了，发现那些数据还在。

**Comment by changchang** [comment]
Player里定义了toJSON，里面做了裁减

**Comment by gongxinheng** [comment]
好的，谢谢~我看看先

**Comment by gongxinheng** [comment]
在toJSON里加断点后发现确实调用了，但是似乎通过某个回调调用的。机制比较像序列化，不过内部代码好像跟不到了。这个toJSON函数是pomelo调用的方法呢还是node.js内部机制支持的？大大能不能给介绍下这些调用关系的流程吗？还有这种toJSON方法可不可以有多个呢，根据不同的消息发送时指定不同的toJSON方法呢？非常感谢^^

**Comment by changchang** [comment]
是js本身的机制。JSON.stringify会检查对象有没有定义toJSON方法，有的话就用这个来做转换。通过这个机制可以根据需要来定制自己的json序列化。具体资料网上也很多，搜一下可以找到的。

**Comment by gongxinheng** [comment]
好的~谢谢
