### ISSUE TITLE
请教：客户端使用unity， protobuf的使用貌似有点麻烦

### ISSUE THREAD

**Issue by matings79** [NetEase/pomelo-cn#201]
因为按照文档的说法，pomelo需要使用json来定义protobuf, 而这个结构不是google protobuf官方的结构， 那么客户端就必须自己定义proto结构。 如此一来， 客户端和服务器端就不能共享网络消息和一般的数据结构。有什么好的解决办法吗？

**Comment by xiecc** [comment]
这个proto定义是服务端客户端共享的， 在握手的时候这个proto定义会从服务端传到客户端。
protobuf的解析在框架的untiy client里已经写了，客户端不用写任何东西就支持protobuf了

**Comment by matings79** [comment]
原来如此， 多谢了， 我再试一下

matings79

发件人： Charlie Crane
发送时间： 2013-07-25 10:13
收件人： NetEase/pomelo-cn
抄送： matings79
主题： Re: [pomelo-cn] 请教：客户端使用unity， protobuf的使用貌似有点麻烦 (#201)
这个proto定义是服务端客户端共享的， 在握手的时候这个proto定义会从服务端传到客户端。
protobuf的解析在框架的untiy client里已经写了，客户端不用写任何东西就支持protobuf了

**Comment by chiuan** [comment]
不错！
