### ISSUE TITLE
pomelo android client目前只能连接pomelo.connectors.sioconnector，不能使用pomelo.connectors.hybridconnector？

### ISSUE THREAD

**Issue by joneqian** [NetEase/pomelo-cn#204]
1、网上看到有关文章说，pomelo android client目前只能连接pomelo.connectors.sioconnector，不能使用pomelo.connectors.hybridconnector，是这样吗？
2、有些demo会对gate做配置
app.configure('production|development', 'gate', function(){
app.set('connectorConfig',
{
connector : pomelo.connectors.sioconnector
});
});
有些demo则没有做显示的配置，这样有区别吗？
3、如果connector用了pomelo.connectors.hybridconnector，是否gate也一定要用pomelo.connectors.hybridconnector呢？

**Comment by py8765** [comment]
在论坛已经回复，详情见[pomelo-club](http://nodejs.netease.com/topic/52085525d6bc618c60179884).
