### ISSUE TITLE
pomelo 为 flash 提供 843 端口访问，端口被占用

### ISSUE THREAD

**Issue by lg-john** [NetEase/pomelo-cn#207]
1. 我新建了一个文件，crossdomain.js  做为为flash 提供 843 端口访问
   var net = require("net");
   var netLister = net.createServer(
   function(socket) {
       socket.write("<?xml version='1.0' ?>\n");
       socket.write("<!DOCTYPE cross-domain-policy SYSTEM 'http://www.macromedia.com/xml/dtds/cross-domain-policy.dtd'>\n");
       socket.write("<cross-domain-policy>\n");
       socket.write("\t<allow-access-from domain='*' to-ports='*' />\n");
       socket.write("</cross-domain-policy>\n");
   
   ```
   socket.end();
   ```
   
   }
   );
   netLister.listen(843);
   console.log("Flash policy server has started.\nPlease see on http://127.0.0.1:843/");
2. 我就添加了这个一个策略文件的支持，在game-server app.js 中调用

var polcy = require('./app/net/crosspolicy');

这样会有异常，   Caught exception: Error: listen EADDRINUSE
1. 我查看了日志，其中，我看到

[2013-09-06 23:43:26.959] [INFO] [default] - Flash policy server has started.
Please see on http://127.0.0.1:843/

[2013-09-06 23:43:26.959] [INFO] [default] - debugger listening on port 32312

[2013-09-06 23:43:26.959] [INFO] [default] - Flash policy server has started.
Please see on http://127.0.0.1:843/

[2013-09-06 23:43:26.960] [INFO] [default] - Flash policy server has started.
Please see on http://127.0.0.1:843/

看这个日志是启动了三次，所以才造成了端口被占用的问题，但是我就调用了一次，何来另外的两次呢。
1. 我用的pomelo 的版本是 0.5.1

有遇到的兄弟吗，谢谢！！！

**Comment by lg-john** [comment]
servers.json 如下

是不是配置了，connector,gate,chat 三个才出现了引用三次，那如果是的话，都怎么解决的

{
  "development":{
    "connector": [
    {"id": "connector-server-1", "host": "192.168.1.179", "port": 3150, "clientPort": 3010, "frontend": true,"args":"--debug=32312"}
    ],
    "gate": [
      {"id": "gate-server-1", "host": "192.168.1.179", "clientPort": 3014, "frontend": true, "args":"--debug=32312"}
    ],
    "chat": [
        {"id":"chat-server-1", "host":"192.168.1.179", "port":6050, "args":"--debug=32312"}
    ]
  },
  "production":{
    "connector": [
    {"id": "connector-server-1", "host": "192.168.1.179", "port": 3150, "clientPort": 3010, "frontend": true,"args":"--debug=32312"}
    ],
    "gate": [
      {"id": "gate-server-1", "host": "192.168.1.179", "clientPort": 3014, "frontend": true,"args":"--debug=32312"}
    ],
    "chat": [
        {"id":"chat-server-1", "host":"192.168.1.179", "port":6050, "args":"--debug=32312"}
    ]
  }
}

**Comment by py8765** [comment]
因为每个服务器启动都是从app.js开始，如果你想只在某台服务器中执行某些操作可以通过app.configure，具体可以参考[chatofpomelo](https://github.com/NetEase/chatofpomelo)或者是[lordofpomelo](https://github.com/NetEase/lordofpomelo).

**Comment by mani95lisa** [comment]
@lg-john 请问解决了吗，我也遇到了同样的问题，多谢~

**Comment by lg-john** [comment]
另外声明了一个文件,将代码放进去。 启动： node crossdomain.js  这样就没问题了
