### ISSUE TITLE
iOS client “回调函数”的问题

### ISSUE THREAD

**Issue by chenyl107** [NetEase/pomelo-cn#21]
Pomelo *pomelo = [[Pomelo alloc] initWithDelegate:self];
        [pomelo connectToHost:@"localhost" onPort:3014];
iOS NetWorking是基于事件的，就像上面这个方法返回200或者error的话会触发那些方法，就像jsclient的回调函数那样。
我在模拟器上跑的时候输出
2012-12-28 22:14:50.803 Tsangyang2[4470:10a03] didReceiveResponse() 200
找不到这是在哪打印出来的，是不是socketIO-objc里的方法，所以pomelo的文档没有写出来。

**Comment by chenyl107** [comment]
在socket-io中看到代码：
/# pragma mark -
/# pragma mark Handshake callbacks (NSURLConnectionDataDelegate)
- (void) connection:(NSURLConnection *)connection didReceiveResponse:(NSURLResponse *)response 
  {
  // check for server status code (http://gigliwood.com/weblog/Cocoa/Q__When_is_an_conne.html)
  if ([response respondsToSelector:@selector(statusCode)]) {
      int statusCode = [((NSHTTPURLResponse *)response) statusCode];
      DEBUGLOG(@"didReceiveResponse() %i", statusCode);
  
  ```
  if (statusCode >= 400) {
      // stop connecting; no more delegate messages
      [connection cancel];
  
      NSString *error = [NSString stringWithFormat:NSLocalizedString(@"Server returned status code %d", @""), statusCode];
      NSDictionary *errorInfo = [NSDictionary dictionaryWithObject:error forKey:NSLocalizedDescriptionKey];
      NSError *statusError = [NSError errorWithDomain:SocketIOError
                                                 code:statusCode
                                             userInfo:errorInfo];
      // call error callback manually
      [self connection:connection didFailWithError:statusError];
  }
  ```
  
  }
  
  [_httpRequestData setLength:0];
  }

---

 DEBUGLOG(@"didReceiveResponse() %i", statusCode);

**Comment by numbcoder** [comment]
新的 API 和 Demo 已经有了。可以参考。
[https://github.com/NetEase/pomelo-ioschat](https://github.com/NetEase/pomelo-ioschat)

**Comment by chenyl107** [comment]
跑了一下这个demo，一开始报MainStoryboard没找到，然后在Summary中去掉MainStoryboard后跑起来了，但是点击登陆后报错：

2012-12-29 13:07:09.208 PomeloChat[1853:f803] Connecting to socket with URL: http://127.0.0.1:3014/socket.io/1/?t=16807
2012-12-29 13:07:09.213 PomeloChat[1853:f803] didReceiveResponse() 200
2012-12-29 13:07:09.213 PomeloChat[1853:f803] connectionDidFinishLoading() Vl3QzeNEQKOwBbF29-OY:60:60:websocket,htmlfile,xhr-polling,jsonp-polling
2012-12-29 13:07:09.213 PomeloChat[1853:f803] sid: Vl3QzeNEQKOwBbF29-OY
2012-12-29 13:07:09.218 PomeloChat[1853:f803] heartbeatTimeout: 67.000000
2012-12-29 13:07:09.218 PomeloChat[1853:f803] transports: (
    websocket,
    htmlfile,
    "xhr-polling",
    "jsonp-polling"
)
2012-12-29 13:07:09.218 PomeloChat[1853:f803] websocket supported -> using it now
2012-12-29 13:07:09.218 PomeloChat[1853:f803] -[SocketIO port]: unrecognized selector sent to instance 0x6e4b050
2012-12-29 13:07:09.218 PomeloChat[1853:f803] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SocketIO port]: unrecognized selector sent to instance 0x6e4b050'
**\* First throw call stack:
(0x14de022 0x167ccd6 0x14dfcbd 0x14e0053 0x1445099 0x1444cb2 0x9cd9 0x7ffd 0xf1aa49 0xf18e84 0xf19ea7 0xf18e3f 0xf18fc5 0xe5df5a 0xcda39 0x19a596 0x19a861 0xc4120 0x19a117 0xc3fbf 0x14b294f 0x1415b43 0x1415424 0x1414d84 0x1414c9b 0x1ca07d8 0x1ca088a 0x517626 0xbcdd 0x24f5)
terminate called throwing an exception(lldb) 
。。。服务器端已经启动

**Comment by numbcoder** [comment]
看报的错是端口有问题，你服务器开的端口是和app 中一致么？

**Comment by chenyl107** [comment]
客户端和服务器端的代码都是从github上刚clone下来的，设了断点是gate.gateHandler.queryEntry这个请求的时候出的错，这个端口应该就是3014吧，因为是gate服务器。看了下charofpomelo客户端js代码逻辑完全一样，好忧伤。。。

**Comment by numbcoder** [comment]
设断点看一下，是不是 port 值传的有问题，有可能是类型转换什么的，把值弄变 了。

**Comment by chenyl107** [comment]
if (([name length] > 0) && ([channel length] > 0)) {
        [pomelo connectToHost:@"127.0.0.1" onPort:3014 withCallback:^(Pomelo _p){
            NSLog(@"connect over_*********");
            NSDictionary *params = [NSDictionary dictionaryWithObject:name forKey:@"uid"];
            [pomelo requestWithRoute:@"gate.gateHandler.queryEntry" andParams:params andCallback:^(NSDictionary *result){
                [pomelo disconnectWithCallback:^(Pomelo *p){
                    [self entryWithData:result];
                }];
            }];
        }];
    }

connect over 没有输出。可能和connectToHost的callback没有关系，我再调试下，这个demo你们那边能跑吗？我一行代码都没改过。

**Comment by numbcoder** [comment]
我这边能跑啊。先确定 gate 端口是 3014，然后看看服务端有木有错误。
把 web server 启动起来，看用浏览器能不能进去

**Comment by chenyl107** [comment]
"gate":[
         {"id": "gate-server-1", "host": "127.0.0.1", "wsPort": 3014}
    ]

这是gate的配置，是3014，浏览器能进去，没有任何问题。ios报错后game-server没有报任何错误。

**Comment by chenyl107** [comment]
ios模拟器连接需不需要配置SSH。。。是127.0.0.1应该不需要吧，我还没配置SSH

**Comment by numbcoder** [comment]
进这个 http://pomelo.netease.com/draw/  聊。 
channel ：pomelo
