### ISSUE TITLE
关于pomelo的session监听事件issue

### ISSUE THREAD

**Issue by KellyLai** [NetEase/pomelo-cn#210]
查看源代码显示LocalSession应该是继承了EventEmitter, 根据node.js的标准api在connector handler做添加和移除监听事件代码和结果如下

session.on('closed', onUserLeave.bind(null, this.app));
console.log('Before remove: ' + util.inspect(session.listeners('closed')));//此时打印出有一个监听函数

session.removeListener('closed', onUserLeave.bind(null, this.app));
console.log('After removeListener: ' + util.inspect(session.listeners('closed'))); //此时打印结果仍有一个监听函数, 移除监听器无效

session.removeAllListeners(['closed']);
console.log('After removeAllListener: ' + util.inspect(session.listeners('closed'))); //打印结果移出成功, 实际仍在监听, 仍会在断开链接时进入onUserLeave函数

有大大可以解释下这是怎么回事吗, 拜谢

**Comment by py8765** [comment]
你这个session是handler里面的session，这个session如果在前端服务器是MockSession，在后端服务器则是LocalSession，每次请求都会根据全局session重新创建。

**Comment by KellyLai** [comment]
Hi py8765, thanks for reply

您说的这些我已经明白了, 我也查看了pomelo源代码中的on方法

MockLocalSession.prototype.on = function(event, listener) {
  EventEmitter.prototype.on.call(this, event, listener);
  this.**session**.on(event, listener);
};

调用的也是this.**session**.on(event, listener);
所以是否可以理解为, 把监听事件传递给了全局Session
如果是这样的话, 要实现我的需求, 要如何调用全局session? 是通过session.**session**来调用吗

已实测如下代码
  console.log('Before add: ' + util.inspect(session.**session**.listeners('closed')));//打印结果[[Function]]

  session.on('closed', onUserLeave.bind(null, this.app));
  console.log('Before remove: ' + util.inspect(session.**session**.listeners('closed')));//打印结果[[Function], [Function]]

  session.**session**.removeListener('closed', onUserLeave.bind(null, this.app));//
  console.log('After remove: ' + util.inspect(session.**session**.listeners('closed')));//打印结果[[Function], [Function]], 移除失败

  session.**session**.removeAllListeners(['closed']);
  console.log('After remove all: ' + util.inspect(session.**session**.listeners('closed'))); //打印结果[],移出成功, 实际也不监听, 但是同时也移除了另外一个监听事件, 是逻辑之外的

不解的地方是removeListener('closed', onUserLeave) 并不生效, 不知道是何原因

**Comment by py8765** [comment]
跟onUserLeave.bind(null, this.app)有关，你第一次on的function和后面remove的function在内存指向不是同一处。你可以尝试在用一个自己写的简单方法替换，就不会出现这种问题。

**Comment by KellyLai** [comment]
hi py, thx for your quick reply

Already fixed the problem. you are right, the issues is caused by the CURRYING. so i fixed the code as below to solve the problem

var leaveFun = onUserLeave.bind(null, this.app);
session.on('closed', leaveFun);
session.removeListener('closed', leaveFun);

I think this thread can be closed now. Thanks a lot.
