### ISSUE TITLE
配置网关服务器报异常

### ISSUE THREAD

**Issue by Hakunata** [NetEase/pomelo-cn#211]
[2013-10-08 17:16:33.942] [ERROR] pomelo-admin - [/home/galaxy/project_pomelo/MIDGameServerSolution/game-server/node_modules/pomelo/node_modules/pomelo-admin/lib/monitorAgent.js] server "gate-server-1" "gate" register master failed

新建(pomelo init)一个工程，启动(game-server下pomelo start)没问题，按照聊天工程加入一个gate服务器，重新启动，结果启动报上面的异常，造成gate服务器没有启动成功。

问了下谷歌，貌似没有相关结果，请各位帮忙看看，先谢谢了。

**Comment by py8765** [comment]
看报错是gate服务器在连接mater服务器的时候发生注册失败，检查一下gate服务器的配置及master的配置文件。

**Comment by Hakunata** [comment]
谢谢，忘记配置adminServer.json文件了

**Comment by majimboo** [comment]
I have the same error, English of this please?

**Comment by py8765** [comment]
Check the configuration in adminServer.json

**Comment by Pilatch** [comment]
Writing this here (in English) for the posterity of the internet. To set up a server in Pomelo, you need both configuration and convention. Add entries to both adminServer.json and to servers.json in game-server/config, and add files as appropriate to game-server/app/servers/nameOfYourServer/ in folders such as: "handler", "filter", "remote".
