### ISSUE TITLE
pomelo.app的时候，app为undefined

### ISSUE THREAD

**Issue by Hakunata** [NetEase/pomelo-cn#218]
app.js里面肯定做了var app = pomelo.createApp();app.set...;app.configure...

然后在我的一个游戏逻辑模块里面：
var pomelo = require('pomelo');
。。。
this.channel = pomelo.app.get('channelService').getChannel(channelName, true);
打印pomelo对app的引用为undefined(app为undefined)，为何？

求关注～

**Comment by Hakunata** [comment]
补充：这个调用（pomelo.app）是否要在app.start()之后才能做？

**Comment by peterchen08** [comment]
你的程序逻辑是不是有点问题啊。
app对象可以理解成一个全局的上下文，app.js创建了这个app对象，并将这个对象在所有服务器初始化的时候做为参数传递进去，通过这个app作为上下文对所有的js类进行串联，只要不关闭服务器，这个app对象一直存在。
在你的游戏逻辑中，你是否已经将这个app传递进去了呢？ 
你的代码“var pomelo = require('pomelo'); ”只是获取pomelo组件，这个组件还没有实例化呢，当然没有app这个对象，简单来说，就是初始化的时候将app传递进去，然后再调用。

**Comment by Hakunata** [comment]
@peterchen08  是这样的，后来看了找到了这个问题，如果不是同一个服务器，需要rpc到具体的服务器remote模块里面去，然后再访问该服务器的具体service组件。

谢谢你的回复！
