### ISSUE TITLE
move action 无法发送给其他客户端

### ISSUE THREAD

**Issue by lg-john** [NetEase/pomelo-cn#220]
1. 参照lordofpomelo 的例子，在area.playerHandler.move 里面，将move action 推送给其他玩家
2. move 里面的代码如下
   ![image](https://f.cloud.github.com/assets/3103224/1452895/0393b0b8-42e2-11e3-8ffc-8a28149600e6.png)
3. 在messageService 里面会最终调用 
   pomelo.app.get('channelService').pushMessageByUids(route, msg, uids, errHandler); 
   执行完毕了，但是另外的游戏客户端就是收不到。

有遇到的吗，或者说给提供下思路，非常感谢！！！

**Comment by py8765** [comment]
参考论坛里的帖子[pomelo 论坛](http://nodejs.netease.com/topic/527387770a516e185141b32a)

**Comment by lg-john** [comment]
是的，不是需要的用户。
因为在登录的时候，设置的格式为 playerName*channelname,但是在channelService 在往客户端发送的是，格式却是 playerId, 所以是对应的uids 不对。。。。

多谢 你的提示！！！
