### ISSUE TITLE
请问pomelo的chat demo 如何可以发送图片消息或者表情？？

### ISSUE THREAD

**Issue by HughNian** [NetEase/pomelo-cn#221]
chat demo都是发送文字，怎么样可以发送实时的图片消息，还有表情，而且，发送图片消息，服务器上还要保存此图片 

哪位大牛可以讲解的具体一点，嘿嘿，有人说用base64 string 不过小弟不是很理解～

**Comment by py8765** [comment]
详见论坛[pomelo论坛](http://nodejs.netease.com/topic/527677970a516e1851443604)
