### ISSUE TITLE
能在pomelo直接使用websocket,而不用再在websocket基础之上封装针对pomelo的协议 么?

### ISSUE THREAD

**Issue by mingzhi1** [NetEase/pomelo-cn#224]
谢谢你们的分享!

使用pomelo 进行通信好像要再客户端封装一层pomelo协议,
请问 能直接使用websocket,
而不用再在websocket基础之上封装针对pomelo的协议么?

**Comment by xiecc** [comment]
可以啊， 所谓的协议就是encode和decode方法， 在配置时用自己的方法实现就可以了

2013/11/8 pan.mingzhi notifications@github.com
