### ISSUE TITLE
pomelo安装失败，mac版本10.9.2 

### ISSUE THREAD

**Issue by wangboo** [NetEase/pomelo-cn#246]
-bash-3.2$ sudo npm install -g
npm http GET http://registry.cnpmjs.org/socket.io/0.9.16
npm http GET http://registry.cnpmjs.org/async/0.2.5
npm http GET http://registry.cnpmjs.org/seq-queue/0.0.5
npm http GET http://registry.cnpmjs.org/crc/0.2.0
npm http GET http://registry.cnpmjs.org/cliff/0.1.8
npm http GET http://registry.cnpmjs.org/pomelo-loader/0.0.6
npm http GET http://registry.cnpmjs.org/pomelo-rpc/0.4.0
npm http GET http://registry.cnpmjs.org/mkdirp/0.3.3
npm http GET http://registry.cnpmjs.org/pomelo-protocol/0.1.3
npm http GET http://registry.cnpmjs.org/pomelo-admin/0.4.0
npm http GET http://registry.cnpmjs.org/pomelo-logger/0.1.2
npm http GET http://registry.cnpmjs.org/pomelo-scheduler/0.3.8
npm http GET http://registry.cnpmjs.org/ws/0.4.25
npm http GET http://registry.cnpmjs.org/pomelo-protobuf/0.4.0
npm http GET http://registry.cnpmjs.org/commander/2.0.0
npm http GET http://registry.cnpmjs.org/node-bignumber/1.2.1
npm http 304 http://registry.cnpmjs.org/crc/0.2.0
npm http 304 http://registry.cnpmjs.org/socket.io/0.9.16
npm http 304 http://registry.cnpmjs.org/seq-queue/0.0.5
npm http 304 http://registry.cnpmjs.org/async/0.2.5
npm http 304 http://registry.cnpmjs.org/cliff/0.1.8
npm http 304 http://registry.cnpmjs.org/pomelo-loader/0.0.6
npm WARN package.json pomelo-loader@0.0.6 No repository field.
npm http 304 http://registry.cnpmjs.org/pomelo-rpc/0.4.0
npm http 304 http://registry.cnpmjs.org/mkdirp/0.3.3
npm WARN package.json pomelo-rpc@0.4.0 No repository field.
npm http 304 http://registry.cnpmjs.org/pomelo-admin/0.4.0
npm http 304 http://registry.cnpmjs.org/pomelo-protocol/0.1.3
npm WARN package.json pomelo-admin@0.4.0 No repository field.
npm WARN package.json pomelo-protocol@0.1.3 No repository field.
npm http 304 http://registry.cnpmjs.org/pomelo-logger/0.1.2
npm http 304 http://registry.cnpmjs.org/commander/2.0.0
npm http 304 http://registry.cnpmjs.org/pomelo-protobuf/0.4.0
npm http 304 http://registry.cnpmjs.org/ws/0.4.25
npm http 304 http://registry.cnpmjs.org/pomelo-scheduler/0.3.8
npm WARN package.json pomelo-logger@0.1.2 No repository field.
npm WARN package.json pomelo-protobuf@0.4.0 No repository field.
npm WARN package.json pomelo-scheduler@0.3.8 No repository field.
npm http 304 http://registry.cnpmjs.org/node-bignumber/1.2.1
npm http GET http://registry.cnpmjs.org/log4js/0.6.7
npm http GET http://registry.cnpmjs.org/log4js
npm http GET http://registry.cnpmjs.org/pomelo-monitor/0.3.7
npm http GET http://registry.cnpmjs.org/socket.io-client/0.9.16
npm http GET http://registry.cnpmjs.org/policyfile/0.0.4
npm http GET http://registry.cnpmjs.org/heapdump/0.2.7
npm http GET http://registry.cnpmjs.org/base64id/0.1.0
npm http GET http://registry.cnpmjs.org/redis/0.7.3
npm http GET http://registry.cnpmjs.org/colors
npm http GET http://registry.cnpmjs.org/eyes
npm http GET http://registry.cnpmjs.org/winston
npm http GET http://registry.cnpmjs.org/pomelo-loader/0.0.5
npm http GET http://registry.cnpmjs.org/stream-pkg/0.0.5
npm http GET http://registry.cnpmjs.org/node-uuid/1.4.0
npm http GET http://registry.cnpmjs.org/async/0.2.10
npm http GET http://registry.cnpmjs.org/tinycolor
npm http GET http://registry.cnpmjs.org/commander
npm http GET http://registry.cnpmjs.org/options
npm http 304 http://registry.cnpmjs.org/log4js/0.6.7
npm http 304 http://registry.cnpmjs.org/socket.io-client/0.9.16
npm http 304 http://registry.cnpmjs.org/log4js
npm http 304 http://registry.cnpmjs.org/policyfile/0.0.4
npm http 304 http://registry.cnpmjs.org/pomelo-monitor/0.3.7
npm WARN package.json policyfile@0.0.4 No repository field.
npm WARN package.json policyfile@0.0.4 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm http 304 http://registry.cnpmjs.org/heapdump/0.2.7
npm http 304 http://registry.cnpmjs.org/base64id/0.1.0
npm http 304 http://registry.cnpmjs.org/colors
npm http 304 http://registry.cnpmjs.org/eyes
npm http 304 http://registry.cnpmjs.org/redis/0.7.3
npm WARN engine heapdump@0.2.7: wanted: {"node":">=0.10.0"} (current: {"node":"v0.8.26","npm":"1.2.30"})
npm WARN package.json eyes@0.1.8 No repository field.
npm http 304 http://registry.cnpmjs.org/async/0.2.10
npm http 304 http://registry.cnpmjs.org/node-uuid/1.4.0
npm http 304 http://registry.cnpmjs.org/stream-pkg/0.0.5
npm http 304 http://registry.cnpmjs.org/winston
npm http 304 http://registry.cnpmjs.org/pomelo-loader/0.0.5
npm WARN package.json pomelo-loader@0.0.5 No repository field.

> heapdump@0.2.7 install /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump
> node-gyp rebuild

npm http GET http://registry.cnpmjs.org/async/0.1.15
npm http GET http://registry.cnpmjs.org/semver
npm http GET http://registry.cnpmjs.org/readable-stream
npm http GET http://registry.cnpmjs.org/async
npm http GET http://registry.cnpmjs.org/cycle
npm http GET http://registry.cnpmjs.org/pkginfo
npm http GET http://registry.cnpmjs.org/request
npm http GET http://registry.cnpmjs.org/stack-trace
npm http 304 http://registry.cnpmjs.org/commander
npm http 304 http://registry.cnpmjs.org/tinycolor
npm http 304 http://registry.cnpmjs.org/options

> ws@0.4.25 install /usr/local/lib/node_modules/pomelo/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm http GET http://registry.cnpmjs.org/dequeue/1.0.3
npm http 304 http://registry.cnpmjs.org/readable-stream
npm http 304 http://registry.cnpmjs.org/async
npm http 304 http://registry.cnpmjs.org/cycle
npm http GET http://registry.cnpmjs.org/active-x-obfuscator/0.0.1
npm http GET http://registry.cnpmjs.org/uglify-js/1.2.5
npm http 304 http://registry.cnpmjs.org/semver
npm http 304 http://registry.cnpmjs.org/async/0.1.15
npm http GET http://registry.cnpmjs.org/xmlhttprequest/1.4.2
npm http GET http://registry.cnpmjs.org/isarray/0.0.1
npm http GET http://registry.cnpmjs.org/core-util-is
npm http GET http://registry.cnpmjs.org/string_decoder
npm http GET http://registry.cnpmjs.org/inherits
npm http 304 http://registry.cnpmjs.org/pkginfo
npm http 304 http://registry.cnpmjs.org/stack-trace
npm http 304 http://registry.cnpmjs.org/request
npm http 304 http://registry.cnpmjs.org/active-x-obfuscator/0.0.1
npm http 304 http://registry.cnpmjs.org/dequeue/1.0.3
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  CXX(target) Release/obj.target/heapdump/src/heapdump.o
npm http 304 http://registry.cnpmjs.org/uglify-js/1.2.5
npm http 304 http://registry.cnpmjs.org/isarray/0.0.1
npm http 304 http://registry.cnpmjs.org/xmlhttprequest/1.4.2
../src/heapdump.cc:95:37: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
       void WriteSnapshot(const v8::FunctionCallbackInfo<Value>& args))
                                ~~~~^
../src/heapdump.cc:36:25: note: expanded from macro 'COMPAT'
# define COMPAT(_, exp) exp

```
                    ^
```

../src/heapdump.cc:95:57: error: expected ')'
       void WriteSnapshot(const v8::FunctionCallbackInfo<Value>& args))
                                                        ^
../src/heapdump.cc:36:25: note: expanded from macro 'COMPAT'
# define COMPAT(_, exp) exp

```
                    ^
```

../src/heapdump.cc:95:26: note: to match this '('
       void WriteSnapshot(const v8::FunctionCallbackInfo<Value>& args))
                         ^
../src/heapdump.cc:36:25: note: expanded from macro 'COMPAT'
# define COMPAT(_, exp) exp

```
                    ^
```

../src/heapdump.cc:99:22: error: no matching constructor for initialization of 'v8::HandleScope'
         HandleScope handle_scope(isolate));
                     ^            ~~~~~~~
../src/heapdump.cc:36:25: note: expanded from macro 'COMPAT'
# define COMPAT(_, exp) exp

```
                    ^
```

/Users/wangboo/.node-gyp/0.8.26/deps/v8/include/v8.h:467:3: note: candidate constructor not viable: no known conversion from 'v8::Isolate _' to 'const v8::HandleScope' for 1st
      argument
  HandleScope(const HandleScope&);
  ^
/Users/wangboo/.node-gyp/0.8.26/deps/v8/include/v8.h:442:3: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  HandleScope();
  ^
../src/heapdump.cc:102:7: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  if (args[0]->IsString()) {
      ^~~~
      uv_process_options_s::args
/Users/wangboo/.node-gyp/0.8.26/deps/uv/include/uv.h:1215:10: note: 'uv_process_options_s::args' declared here
  char_\* args;
         ^
../src/heapdump.cc:102:7: error: invalid use of non-static data member 'args'
  if (args[0]->IsString()) {
      ^~~~
../src/heapdump.cc:103:32: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
    String::Utf8Value filename(args[0]);
                               ^~~~
                               uv_process_options_s::args
/Users/wangboo/.node-gyp/0.8.26/deps/uv/include/uv.h:1215:10: note: 'uv_process_options_s::args' declared here
  char*\* args;
         ^
../src/heapdump.cc:103:32: error: invalid use of non-static data member 'args'
    String::Utf8Value filename(args[0]);
                               ^~~~
../src/heapdump.cc:112:10: error: use of undeclared identifier 'args'
         args.GetReturnValue().Set(ok));
         ^
../src/heapdump.cc:36:25: note: expanded from macro 'COMPAT'
# define COMPAT(_, exp) exp

```
                    ^
```

../src/heapdump.cc:120:27: error: no member named 'NewFromUtf8' in 'v8::String'
                  String::NewFromUtf8(isolate, "writeSnapshot")),
                  ~~~~~~~~^
../src/heapdump.cc:36:25: note: expanded from macro 'COMPAT'
# define COMPAT(_, exp) exp

```
                    ^
```

../src/heapdump.cc:154:16: error: no member named 'GetHeapProfiler' in 'v8::Isolate'
      isolate->GetHeapProfiler()->TakeHeapSnapshot(String::Empty()));
      ~~~~~~~  ^
../src/heapdump.cc:36:25: note: expanded from macro 'COMPAT'
# define COMPAT(_, exp) exp

```
                    ^
```

10 errors generated.
make: **\* [Release/obj.target/heapdump/src/heapdump.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:686:10)
gyp ERR! System Darwin 13.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump
gyp ERR! node -v v0.8.26
gyp ERR! node-gyp -v v0.10.0
gyp ERR! not ok 
npm http 304 http://registry.cnpmjs.org/core-util-is
npm http 304 http://registry.cnpmjs.org/string_decoder
npm http GET http://registry.cnpmjs.org/zeparser/0.0.5
  SOLINK_MODULE(target) Release/bufferutil.node
npm http 304 http://registry.cnpmjs.org/inherits
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/vendor/web-socket-js/README.md'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/wangboo/Desktop/projects/pomelo
npm ERR! node -v v0.8.26
npm ERR! npm -v 1.2.30
npm ERR! path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/vendor/web-socket-js/README.md
npm ERR! fstream_path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/vendor/web-socket-js/README.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR! weird error 1
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/uglify-js/lib/process.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/wangboo/Desktop/projects/pomelo
npm ERR! node -v v0.8.26
npm ERR! npm -v 1.2.30
npm ERR! path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/uglify-js/lib/process.js
npm ERR! fstream_path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/uglify-js/lib/process.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm http 304 http://registry.cnpmjs.org/zeparser/0.0.5
npm http GET http://registry.cnpmjs.org/zeparser/download/zeparser-0.0.5.tgz
npm http 200 http://registry.cnpmjs.org/zeparser/download/zeparser-0.0.5.tgz
npm http GET http://registry.cnpmjs.org/xmlhttprequest/1.4.2
npm http GET http://registry.cnpmjs.org/uglify-js/1.2.5
npm http GET http://registry.cnpmjs.org/active-x-obfuscator/0.0.1
npm http 304 http://registry.cnpmjs.org/active-x-obfuscator/0.0.1
npm http 304 http://registry.cnpmjs.org/xmlhttprequest/1.4.2
npm http 304 http://registry.cnpmjs.org/uglify-js/1.2.5
npm http GET http://registry.cnpmjs.org/zeparser/0.0.5
npm http 304 http://registry.cnpmjs.org/zeparser/0.0.5
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/wangboo/Desktop/projects/pomelo/npm-debug.log
npm ERR! not ok code 0

**Comment by py8765** [comment]
node版本有点低，建议0.10.x

**Comment by wangboo** [comment]
谢谢，换了node v0.10.28 解决了
