### ISSUE TITLE
关于多服务器配置

### ISSUE THREAD

**Issue by totollo** [NetEase/pomelo-cn#25]
你好。我使用一台服务器跑POMELO CHAT的DEMO . 另一台电脑登陆。在WEB端看到你们其他DEMO吧127.0.0.1过滤成浏览器当前IP。我觉得这样不好，于是我尝试吧CONNECTOR的IP改成服务器的外网IP。问题就出来了。服务器死活不肯启动。

[2012-12-31 16:12:38.642] [ERROR] /node_modules/pomelo/lib/master/starter.js - FAILED TO RUN, return code: 255

我也看了关于SSH-AGENT的问题。服务器本身就是可以免密码登陆的。

其实如果能增加一个wsHost的配置在server.json 然后在gate那里返回给客户端就GJ了。

**Comment by totollo** [comment]
原来还真可以在server.json上添加wshost .。。。。 然后我在gateHandler里面吧返回 res.host 改成返回 res.wshost 就OK了。这样就可以在一台有多网卡的服务器上配置出口鸟～～

**Comment by xiecc** [comment]
嗯， 这个解决方案不错。 我们整理一下

2012/12/31 endenvoy notifications@github.com
