### ISSUE TITLE
chatofpomelo遇到问题，服务器正常开启，客户端会自动触发disconnect

### ISSUE THREAD

**Issue by pengqiuyuan** [NetEase/pomelo-cn#251]
客户端会自动触发disconnect，客户端关闭，服务端正常， 从进入到触发disconnect，大概10秒左右 ，请问是什么问题！求助

**Comment by pengqiuyuan** [comment]
![11](https://cloud.githubusercontent.com/assets/4953205/3795007/8f1fa9f0-1bb5-11e4-92fc-27f5a5e6b1e5.png)

![22](https://cloud.githubusercontent.com/assets/4953205/3795087/bd5daab4-1bb6-11e4-98a0-caf77f961ab0.png)
![33](https://cloud.githubusercontent.com/assets/4953205/3795088/bd93ff88-1bb6-11e4-9830-ef91a43541f8.png)

**Comment by py8765** [comment]
一直触发？第一次是会连接gate服务器，然后关闭再连接connector，应该是触发一次是正常的。

**Comment by pengqiuyuan** [comment]
第一次有触发 ，就是点击进入的时候，  先是这里pomeloclient.js的  pomelo.disconnect = function() {
        if(socket) {
            socket.disconnect();
            socket = null;
        }
    };  之后是client的     pomelo.on('disconnect', function(reason) {
        alert("ttttttttttttttttt");
        showLogin();
    });   这里的disconnect都是正常的  。 可是进去之后，大概10秒左右，客户端会自动触发disconnect，客户端关闭，服务端正常。。是为什么

**Comment by pengqiuyuan** [comment]
基本是进去之后 ，10秒左右就 disconnect 了  ，服务端正常 ，客户端是chrome 也正常 ， 客户端我用的ie7。。 对不起我知道用ie很多问题 ，但是我还是想尝试下，也想知道问题是什么。。求助

**Comment by pengqiuyuan** [comment]
ie 几个低版本 7 8 9 都聊天可以的 ，这是这里不知道为什么  。。问题卡这里了。。@py8765

**Comment by py8765** [comment]
你有没有更改代码的逻辑呢？按道理只是第一次从gate服务器切换到connector服务器会有disconnect，你可以抓包看看。

**Comment by pengqiuyuan** [comment]
是的我有改源码了。。sioconnector.js的解码  和 pomeloclient.js的编码  其他地方就是pomeloclient上的几个函数不兼容ie 的修改。。

这俩个地方  都是加了判断 ，分开ie 和 chrome 的 。。会不会有问题。。

**Comment by pengqiuyuan** [comment]
10秒 ,果断会断开, 一秒也不差呀。。，请问这10秒是在什么地方呢 @py8765

**Comment by pengqiuyuan** [comment]
https://github.com/pengqiuyuan/chatofpo   @py8765  @xiecc  能帮看下吗..
pomelo 版本是1.0.3 , 客户端触发disconnect之后，服务端的这个session还在.. , 这个是在什么地方触发的。

**Comment by py8765** [comment]
代码应该没有什么问题，我这边用ie8，ie7测试也一切正常，检查一下浏览器和服务器的相关配置。

**Comment by py8765** [comment]
现在只能抓包看看是哪里发了fin包

**Comment by pengqiuyuan** [comment]
我在群里，让朋友帮忙看，他们也没问题，不会出现断开的情况。。就我的会不管用什么360、还是ie都会10秒断开，fin包是在服务端测吗，怎么抓，求指教下。。
![666](https://cloud.githubusercontent.com/assets/4953205/3836483/14ad36c4-1dd6-11e4-81cd-ab95f8af0bde.png)

**Comment by py8765** [comment]
找一个抓包工具，例如wireshark，然后看看客户端和服务端的数据包

**Comment by pengqiuyuan** [comment]
谢谢

发自我的 iPhone
