### ISSUE TITLE
关于flash客户端

### ISSUE THREAD

**Issue by blackgun** [NetEase/pomelo-cn#26]
现在有很多flash网游，flash是世界最普及的平台（覆盖率97%）拥有比windows（70%）更广的用户群，请出个flash as3的客户端。

我大致看了一下手机客户端，为什么要用socket.io的库呢，那不是for js的吗，iOS/Androd本身不就支持socket吗？

看了一下FlashSocket.IO, 是封装了web-socket，然后通过JS bridge来实现的，这样的问题：1）flash AS3本身就支持socket和xmlsocket，结合JAVA服务器做的网游项目很多了，本身socket功能就很强大，用websocket舍近求远。 2）现在AS3的一个重点应用就是用于移动设备的AIR，external.call这种bridge方式也没法用啊

我不太清楚socket.io跟socket的差别，通信有什么问题，即便存在协议上的差异，通过JS做个node端的通信代理也应该很容易解决。因为flash跟node.js直接就可以进行socket通信。

**Comment by py8765** [comment]
其实flash客户端我们之前就已经有了，只是现在系统有所改变，没有对其进行完全的封装，如果你感兴趣，可以考虑封装提供一个，我们将会非常感谢，后面可能会考虑提供flash客户端。

其实socket.io是在websocket的基础上进行封装，websocket也是在原生socket的基础上进行封装。关于直接使用原生socket，我们已经提出了这个想法，应该不久就会去对其进行支持，到时就可以提供两种供用户选择。
