### ISSUE TITLE
cocos2d-js 打包android  pomelo报错求指导

### ISSUE THREAD

**Issue by CimXin** [NetEase/pomelo-cn#262]
在chrome里cocos2d-js 连接服务器并且通讯正常 ，打包到Android 报如下错误
![2015-10-21 11 51 09](https://cloud.githubusercontent.com/assets/8610654/10629200/612276a2-77ff-11e5-93a1-6df53e3399e0.png)

**Comment by jamy325** [comment]
显然ip没改过来
