### ISSUE TITLE
通过自定义服务器给客户端发消息

### ISSUE THREAD

**Issue by gongxinheng** [NetEase/pomelo-cn#27]
我分离了一些lordofpomelo Demo中的代码来建立自己的游戏服务器。在已有connector,area,gate,auth,chat等服务器的基础上自定义了一个combat服务器，现在触发战斗的流程是由area发送给combat，在combat计算完后我想节省流量，不返回给area而是在combat端直接发送给客户端战斗相关过程信息（目前从area通过rpc调用combat的计算，这部分都已经调通了）。但是我不知道该从何下手。参考了一下lordofpomelo里面的一些方法，似乎有一个messageService.pushMessage系列方法，我想知道可以通过这种方式直接发送给客户端吗？还需要做一些什么额外的事情呢？还有里面用到的那些event，如player.on(...)，看起来是可以给具体某个Entity注册event。能简单介绍下这些原理吗？非常感谢！

**Comment by py8765** [comment]
嗯，服务端给客户端推送消息主要是通过channel,你首先可以看看pomelo中channel的相关API，它提供了相关消息推送的方法，具体可以查看[pomelo API](http://pomelo.netease.com/api.html)。至于你说的事件注册，这都是基本的EventEmitter做的事情，这个如果不清楚可以看看node的Event类，自己尝试继承EventEmitter，再去做事件封装。

**Comment by numbcoder** [comment]
area 把消息发送到 combat ，combat 计算完后，自己把消息发送的客户端是可以的。就是通过 pushMessage
lordofpomelo 中可能有些复杂，你可以看看这个简单一点的demo https://github.com/NetEase/treasures ，或许能看懂。

player 能注册 event，是因为它继承了 EventEmitter

**Comment by gongxinheng** [comment]
嗯，已经成功了，谢谢。
node.js的event机制我大概了解一些，看到pomelo里面为不同实体注册了很多这样的事件，不过有一点我还不太确定。node.js通过emit发送的消息都能确保按顺序收到处理吗？如果是乱序的话那lordofpomelo Demo中这样大量的使用估计就可能有问题了
