### ISSUE TITLE
在WIN7下安装pomelo后，用“pomelo start”执行后，只输出一行信息，然后立即退出。

### ISSUE THREAD

**Issue by catxuxiang** [NetEase/pomelo-cn#28]
如题：
cmd下的执行情况如下：
![image](https://f.cloud.github.com/assets/3175435/40229/495359a6-558e-11e2-864a-0dfe67128d3c.png)
不知道什么情况。然后我用node app执行，得到下述错误，看来，对windows的支持还是有问题咯。
![image](https://f.cloud.github.com/assets/3175435/40244/c79d114e-558e-11e2-803b-a1799ea713c2.png)
我把目录放在系统根目录后，问题解决。看来应该是node.js对windows支持不好的问题。

**Comment by py8765** [comment]
嗯，谢谢提出的问题。

**Comment by catxuxiang** [comment]
这个问题可以关闭了，留在github里可以让其它人也参考一下。

**Comment by vail-hng** [comment]
貌似是路径有空格的问题？
