### ISSUE TITLE
Mac 安装pomelo 不成功？

### ISSUE THREAD

**Issue by py8765** [NetEase/pomelo-cn#3]
My system is mac os 10.8.2, and I was excuted with "npm install pomelo -g" but "pomelo" common not support, and pomelo install's log is no err,
my system is os x 10.8.2+xcode4.5+node0.8.14+python2.7.2

installl log for you:

npm http GET https://registry.npmjs.org/socket.io
npm http GET https://registry.npmjs.org/pomelo-sync
npm http GET https://registry.npmjs.org/seq-queue
npm http GET https://registry.npmjs.org/cliff
npm http GET https://registry.npmjs.org/crc
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/pomelo-loader
npm http GET https://registry.npmjs.org/pomelo-rpc
npm http GET https://registry.npmjs.org/pomelo-protocol
npm http GET https://registry.npmjs.org/pomelo-monitor
npm http GET https://registry.npmjs.org/pomelo-logger/0.0.2
npm http GET https://registry.npmjs.org/pomelo-admin
npm http 304 https://registry.npmjs.org/pomelo-sync
npm http 304 https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/pomelo-loader
npm http 304 https://registry.npmjs.org/pomelo-rpc
npm http 304 https://registry.npmjs.org/seq-queue
npm http 304 https://registry.npmjs.org/pomelo-monitor
npm http 304 https://registry.npmjs.org/pomelo-logger/0.0.2
npm http 304 https://registry.npmjs.org/pomelo-admin
npm WARN package.json pomelo-admin@0.0.17 No README.md file found!
npm http 304 https://registry.npmjs.org/pomelo-protocol
npm http 304 https://registry.npmjs.org/crc
npm http 304 https://registry.npmjs.org/cliff
npm http GET https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/log4js
npm http GET https://registry.npmjs.org/pomelo-schedule
npm http GET https://registry.npmjs.org/v8-profiler
npm http GET https://registry.npmjs.org/socket.io-client
npm http GET https://registry.npmjs.org/socket.io-client
npm http GET https://registry.npmjs.org/stream-pkg
npm http GET https://registry.npmjs.org/socket.io-client/0.9.11
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/redis/0.7.3
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/pomelo-schedule
npm http 304 https://registry.npmjs.org/socket.io-client
npm http 304 https://registry.npmjs.org/stream-pkg
npm http 304 https://registry.npmjs.org/socket.io-client/0.9.11
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm http 304 https://registry.npmjs.org/redis/0.7.3
npm http 304 https://registry.npmjs.org/eyes
npm http 304 https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/cycle
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/stack-trace
npm http 304 https://registry.npmjs.org/log4js
npm http GET https://registry.npmjs.org/async/0.1.15
npm http 304 https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/cycle
npm http 304 https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/stack-trace
npm http 304 https://registry.npmjs.org/async/0.1.15
npm http 304 https://registry.npmjs.org/v8-profiler
npm http 304 https://registry.npmjs.org/socket.io-client

> v8-profiler@3.6.2-1 install /usr/local/share/npm/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/v8-profiler
> node-gyp rebuild

npm http GET https://registry.npmjs.org/log4js
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/zeparser/0.0.5
  CXX(target) Release/obj.target/profiler/cpu_profiler.o
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/options
  CXX(target) Release/obj.target/profiler/graph_edge.o
  CXX(target) Release/obj.target/profiler/graph_node.o
  CXX(target) Release/obj.target/profiler/heap_profiler.o
npm http 304 https://registry.npmjs.org/log4js
npm http GET https://registry.npmjs.org/async/0.1.15
  CXX(target) Release/obj.target/profiler/profile.o
  CXX(target) Release/obj.target/profiler/profile_node.o
npm http 304 https://registry.npmjs.org/tinycolor
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
  CXX(target) Release/obj.target/profiler/profiler.o
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
  CXX(target) Release/obj.target/profiler/snapshot.o
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/async/0.1.15
npm http 304 https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/zeparser/0.0.5
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/commander
  SOLINK_MODULE(target) Release/profiler.node

> ws@0.4.23 install /usr/local/share/npm/lib/node_modules/pomelo/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> node install.js

[ws v0.4.23] Attempting to compile blazing fast native extensions.
  SOLINK_MODULE(target) Release/profiler.node: Finished
[ws v0.4.23] Native extension compilation successful!
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
npm http 304 https://registry.npmjs.org/tinycolor
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/options

> ws@0.4.23 install /usr/local/share/npm/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/ws
> node install.js
> 
> ws@0.4.23 install /usr/local/share/npm/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/ws
> node install.js

[ws v0.4.23] Attempting to compile blazing fast native extensions.
[ws v0.4.23] Attempting to compile blazing fast native extensions.
[ws v0.4.23] Native extension compilation successful!
[ws v0.4.23] Native extension compilation successful!
/usr/local/share/npm/bin/pomelo -> /usr/local/share/npm/lib/node_modules/pomelo/bin/pomelo
pomelo@0.2.0 /usr/local/share/npm/lib/node_modules/pomelo
├── pomelo-protocol@0.0.3
├── crc@0.2.0
├── pomelo-monitor@0.3.5
├── seq-queue@0.0.5
├── pomelo-loader@0.0.4
├── async@0.1.22
├── pomelo-sync@0.0.2
├── cliff@0.1.8 (eyes@0.1.8, colors@0.6.0-1, winston@0.6.2)
├── pomelo-logger@0.0.2 (log4js@0.5.5)
├── socket.io@0.9.11 (policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.11)
├── pomelo-admin@0.0.17 (pomelo-schedule@0.3.4, v8-profiler@3.6.2-1, socket.io-client@0.9.11)
└── pomelo-rpc@0.0.11 (stream-pkg@0.0.4, socket.io-client@0.9.11)
What's wrong?

-bash: pomelo: command not found

**Comment by py8765** [comment]
/usr/local/share/npm/bin/pomelo -> /usr/local/share/npm/lib/node_modules/pomelo/bin/pomelo
是链接到/usr/local/share/npm/bin/这个目录下了，而这个目录不在你系统的PATH里，所以找不到。
这个目录可能跟你的npm的配置有关。
我本地的npm是链接到/usr/local/bin目录下的。

**Comment by yishaoye** [comment]
我的再mac安装也报错啊; 为什么啊?
npm http GET https://registry.npmjs.org/pomelo
npm http 304 https://registry.npmjs.org/pomelo
npm ERR! error rolling back Error: EPERM, chmod '/usr/local/bin/pomelo'
npm ERR! error rolling back  pomelo@0.2.2 { [Error: EPERM, chmod '/usr/local/bin/pomelo'] errno: 50, code: 'EPERM', path: '/usr/local/bin/pomelo' }
npm ERR! Error: EPERM, chmod '/usr/local/bin/pomelo'
npm ERR!  { [Error: EPERM, chmod '/usr/local/bin/pomelo'] errno: 50, code: 'EPERM', path: '/usr/local/bin/pomelo' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 11.4.2
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pomelo" "-g"
npm ERR! cwd /Users/yi_shao
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm ERR! path /usr/local/bin/pomelo
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, chmod '/usr/local/bin/pomelo'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/yi_shao/npm-debug.log
npm ERR! not ok code 0

**Comment by py8765** [comment]
应该是需要管理员权限，你试一下：sudo npm install -g pomelo

**Comment by yishaoye** [comment]
安装成功了. 我之前使用的是你们文档中提示的 npm install pomelo -g 命令来安装的失败了;

**Comment by kevinkam** [comment]
所以問題要怎麼解決阿?@@
我的不管怎麼安裝都是pomelo: Command not found.
我又看到他在/usr/local/lib/node_modules/底下
要怎麼把路徑加到terminal裡呢?

**Comment by kevinkam** [comment]
我把termanal整個退出再重新安裝又成功了@@
