### ISSUE TITLE
如何在connector以外的服务器中获取全局session

### ISSUE THREAD

**Issue by gongxinheng** [NetEase/pomelo-cn#31]
我在area服务器中封装了一个方法用来触发战斗，然后通过rpc调用战斗服务器的接口。这个时候会需要用到session中设置战斗服务器的id来做路由。路由函数实现如下：
exp.combat = function(session, msg, app, cb) {
    var serverId = session.get('combatID');

```
if(!serverId) {
    cb(new Error('can not find server info for type:' + msg.serverType));
    return;
}

cb(null, serverId);
```

};
但是通过rpc调用的时候是通过一个emit事件beAttacked来触发的，这里面并没有传递session作为参数，
    /**
     \* Be attacked event handler
     */
    mobOnMap.on('beAttacked', function(args){
        var player = args.attacker;
        var mobOnMap = args.mobOnMap;

```
    //Trigger a combat of solo
    combatAgent.requestSolo(player, mobOnMap,null);
});
```

exp.requestSolo = function(player, mobOnMap, cb) {
    var combatServer = serverDispatchService.dispatchCombat();
    var session = {combatID: combatServer.id};  // 应该在此获取session来设置combatID
    pomelo.app.rpc.combat.combatRemote.reqCombatSolo(
            session, player.toCombatAttributes(),
            player.team.leaderPos, mobOnMap.toCombatAttributes(),
            cb
    );
};
这时候我想通过获取本地的全局session往里面填充combatID，但是没有发现有相关API获取。请问这种呢情况应该如何处理比较好呢？求解答~

**Comment by changchang** [comment]
机制是有的，系统提供了一个rpc接口用来修改全局session属性。可以参考localSessionService里的[push](https://github.com/NetEase/pomelo/blob/master/lib/common/service/localSessionService.js#L35)方法的实现，需要额外提供的参数有玩家所在的frontend server id和session id。

这个用法当初认为不大典型，而且破坏了封装性，所以没有放在文档里公布。以后我们可以考虑一个方便点的接口来做这事情:)

根据你的描述，应该是玩家主动攻击怪物后触发的事件吧，这个事件是否是在handler里emit的呢？是否可以在事件参数里把session带过来，这样可能会更简单一些。

**Comment by gongxinheng** [comment]
其实不用session的方式，直接把combatID作为rpc调用的第一个参数，然后在路由函数里面var serverId = session;这样也是可以的，刚刚试过了~不过总感觉有点不妥。

把session通过事件触发传过去的方式我也考虑过。但是有一些问题，比如传递的层次过深，从connector把session传过来后可能通过好些接口才到触发emit事件。另外还有一点玩家碰怪有主动和非主动两种方式，怪物也可以直接找玩家的，那这种情况下应该是有服务器主动通知客户端了。所以我觉得这个时候还是有必要获取session

**Comment by changchang** [comment]
恩，是的。session参数的主要目的是将玩家的状态信息传递给路由函数，不一定非要pomelo的session对象不可。

获取session的接口确实是必要的，在下一版本考虑加上:)

**Comment by gongxinheng** [comment]
好的~谢谢^^

**Comment by luoxinliang** [comment]
遇到同样问题，请问现在的版本可以了么？

**Comment by luoxinliang** [comment]
remote 调用 remote，session丢了，但是没有session，就没法route了。
