### ISSUE TITLE
关于pomelo-aoi的几点疑惑

### ISSUE THREAD

**Issue by ghost** [NetEase/pomelo-cn#34]
1. AOIService有必要吗？看了它的实现，都是对towerAOI函数包了一层，出于哪方面考虑？方便将来扩展？
2. AOIService函数的这段，2个!!不就等于不写吗？还是有什么特殊的地方？
   if(!!config.aoi){
     this.aoi = config.aoi.getService(config);
   }else{
     this.aoi = towerAOI.getService(config);
   }

**Comment by ghost** [comment]
这里，没有2个参数的checkPos函数呀
if(!this.checkPos(oldPos.x, oldPos.y) || !this.checkPos(newPos.x, newPos.y))

**Comment by ghost** [comment]
var changedTowers = getChangedTowers(p1, p2, oldRange, newRange, this.towers, this.max);
var removeTowers = changedTowers.removeTowers;
var addTowers = changedTowers.addTowers;
getChangedTowers 这个函数返回的unChangeTowers没有处理？？

**Comment by demon0925** [comment]
1，是的，因为可能会用到其他的AOI实现方式，不过在我们的测试中，基于tower的aoi算法的效率和效果还是可以接受的，因此没有使用更为复杂的算法。
2，！！会把结果转成boolean型，在需要boollean型的时候会有些好处。
3，checkpos这个是bug。。。 。。。。已修复
4，unChangeTower表示在因为watcher位置变化前后都在视野中的tower，在当前的逻辑中，这些towers是不需要进行通知的（因为都在视野中），因此没有进行处理。

**Comment by ghost** [comment]
好的，谢谢
