### ISSUE TITLE
无基础如何学习pomelo！

### ISSUE THREAD

**Issue by chujun320** [NetEase/pomelo-cn#35]
看了很多pomelo里自带的例子，基本都能运行成功，但是当要自己动手的时候，却不知道怎么写。
本来看到出了pomelo-unity的客户端，因为对unity还算比较了解，准备用它学习下，但是当要自己动手的时候，发现pomelo-unity客户端和chat里的很多代码还是不知道用法。
没学过网页开发，没学过js，没学过nodejs，也没有服务器的基础，我该如何一步步搞懂pomelo！
求助！

**Comment by py8765** [comment]
建议先学习js，然后nodejs，最后再看[pomelo wiki](https://github.com/NetEase/pomelo/wiki/Home-in-Chinese)。

**Comment by halfblood369** [comment]
其实unityclient 和unitychat里面对pomelo的运用是很基础的，如楼上建议，可以从js，nodejs学起，等有了基础后再研究pomelo。

**Comment by xiecc** [comment]
node.js是脚本语言，相对入门门槛比C低很多， 开发效率则比C高很多。
学习起来还是比较快的，认真学的话，从掌握js到node.js应该在2个月之内。

2013/1/10 halfblood notifications@github.com
