### ISSUE TITLE
如何实现动态创建房间的结构

### ISSUE THREAD

**Issue by itomsawyer** [NetEase/pomelo-cn#36]
我了解到Servers目录下每个组件都运行在不同的进程中，所以示例一中connetor 调用 chat时需要rpc。那么，如果想要实现用户登录后同一进入一个大厅，然后可以分别建立新房间。请问应该如何实现比较好呢？

因为每个房间的数据都有独立性，而且房间中执行的代码可能还不一样。是单独写一个应用，然后当用户新建房间就fork新进程吗，再load一些其他组件吗？

**Comment by xiecc** [comment]
动态创建新进程的功能我们在0.3版本已经开发完毕。
因为我们还准备在lord of pomelo中支持动态副本，这个需要跟你很类似。
不过0.3版还在整合， 一些功能需要测试，预计春节前后发布。

**Comment by numbcoder** [comment]
一个 chat 进程是可以容纳多个房间的。所谓的房间只是一个独立上下文中运行的一套逻辑而已。具体就是一个 chat 进程中可以有 n 个 Room 对象，每个 Room 对象中有 n 个 User 对象。

假如一个 chat 服务可以支撑100个 room，那么你可以通过水平扩展多个 chat 服务来支撑更多的 room。

**Comment by itomsawyer** [comment]
@numbcoder  恩，理解了，多谢。
