### ISSUE TITLE
客户端socket.send后服务端在哪接收

### ISSUE THREAD

**Issue by shaniu00** [NetEase/pomelo-cn#37]
pomelo.request = function(route) {
    if(!route) {
      return;
    }
    var msg = {};
    var cb;
    arguments = Array.prototype.slice.apply(arguments);
    if(arguments.length === 2){
      if(typeof arguments[1] === 'function'){
        cb = arguments[1];
      }else if(typeof arguments[1] === 'object'){
        msg = arguments[1];
      }
    }else if(arguments.length === 3){
      msg = arguments[1];
      cb = arguments[2];
    }
    msg = filter(msg,route);
  id++;
  callbacks[id] = cb;
  var sg = Protocol.encode(id,route,msg);
    socket.send(sg);
  };

到这步骤socket.send之后 跟踪不到了 服务端socket 接收消息的代码位置在哪里哦
好心人帮忙回答下 ^^

**Comment by xiecc** [comment]
看一下 components/connector.js  和  connectors/siosocket.js 这两个类。

前端服务器加载时会load  connector这个component， connector底层会通过siosocket接收消息。
最后由 connector的handleMessage方法来分发消息到指定服务器或方法。
