### ISSUE TITLE
源代码的小疑问

### ISSUE THREAD

**Issue by chenyl107** [NetEase/pomelo-cn#38]
/**
- Process command line arguments.
  *
- @param args command line arguments
  *
- @return Object args_map map of arguments
  */
  utils.argsInfo = function (args) {
  var args_map = {};
  var main_pos = 1;
  
  while(args[main_pos].indexOf('--')>0){
    main_pos++;
  }
  args_map.main = args[main_pos];
  
  for (var i = (main_pos+1); i < args.length; i++) {
    var str = args[i].split('=');
    args_map[str[0]] = str[1];
  }
  return args_map;
  };

这是pomelo下./util/utils中的代码，该方法在defaultConfiguration时候被调用，传入的是process.argv，应该是命令行的所有输入的数组。
如果传入的是pomelo start --daemon的话 是不是应该在main_pos =2 的时候 

while(args[main_pos].indexOf('--')>0){
    main_pos++;
  }

这里才会做++操作。
而传入的如果是 pomelo start production --daemon的话应该是main_pos =3的时候。
还有一个疑问是var str = args[i].split('='); pomelo命令行文档里并没有说可以配置 XXX=OOO之类的。。。

**Comment by py8765** [comment]
传入的参数可以在servers.json配置,这个在[pomelo 命令行文档](https://github.com/NetEase/pomelo/wiki/%E5%91%BD%E4%BB%A4%E8%A1%8C%E6%96%87%E6%A1%A3) 有说明。在底层传入的命令也不是pomelo start --daemon，这之前先经过了bin/pomelo中对命令进行解析了，到这里都是node命令。

**Comment by chenyl107** [comment]
soga。。。Pomelo框架包含一个类似Shell的命令行工具，这个命令行工具的源代码是不是就是bin/pomelo？

**Comment by py8765** [comment]
嗯 是的

**Comment by chenyl107** [comment]
@py8765  有木有node.js shell编程方面的参考资料？我还木有玩过shell编程。。。

**Comment by py8765** [comment]
跟普通的node编程没有太大的区别，你可以参考一下forever或者commander.js的相关实现。
