### ISSUE TITLE
master服务器是做什么的

### ISSUE THREAD

**Issue by chenyl107** [NetEase/pomelo-cn#41]
刚看源代码的时候看到
this.loadConfig('master', this.getBase() + '/config/master.json');
由于不知道master，所以我们项目中没有master.json这个文件，请问master服务器的作用是什么，有相关文档吗

**Comment by xiecc** [comment]
Master必须要有的,他是所有进程的管理器,进程启动,停止,监控等都由master管理

发自我的 iPad

在 2013-1-12，5:07，陈奕龙 notifications@github.com 写道：

**Comment by chenyl107** [comment]
@xiecc 是不是adminConsole时候会用到master，我们的项目没有配置master服务器现在也能跑起来，能具体解释下吗，对这个服务器很模糊。。

**Comment by huaye2007** [comment]
这个项目的文档有明确介绍吧！是监控其他服务器的。

**Comment by halfblood369** [comment]
其实Master服务器的作用还是很明确的，正如上面所说的管理和监控其他服务器，更多的信息你可以参考wiki中的pomelo架构概览，Pomelo Framework等文档。
