### ISSUE TITLE
关于pomelo-sync模块的exec接口参数问题

### ISSUE THREAD

**Issue by gongxinheng** [NetEase/pomelo-cn#44]
文档上介绍第二个参数id是唯一主键值，我不明白这个参数干什么用的。我试着改成一个任意数字似乎也没有什么影响。求解释~
另外顺便问下lord Demo里面有用到redis吗？

**Comment by piaohai** [comment]
id是唯一主键值是指需要修改的实体主键值，也就是需要持久化的对象的主键，主要是在持久化之前做合并用的，比较你发了多个持久化对同一个对象的操作，前面的操作在周期内都不再同步，只同步最后一次的对象。

没有用到REDIS，第一次载入数据后, 全在内存操作.

**Comment by gongxinheng** [comment]
这样啊~那这个键值可以是多个键值的组合吗？比如组合主键呢？

**Comment by piaohai** [comment]
主键是由用户自己定义和控制的，只要能保证数据唯一并能更新就可以
