### ISSUE TITLE
什么时候会有C++的client？

### ISSUE THREAD

**Issue by falqs** [NetEase/pomelo-cn#45]
什么时候会有C++的client？
我尝试自己搞，但是连接上后，发出的消息，不被pomelo处理，头疼...

**Comment by py8765** [comment]
后面版本可能会计划出c++客户端。

**Comment by falqs** [comment]
哦，既然我搞了那就先问一下吧：我现在用socket.io的是这个库https://github.com/ebshimizu/socket.io-clientpp

可以连接上服务器，切换到http1.1也正常，但是在send message的时候pomelo不处理了。我对照了一下C++和JS的encode时候的byte数组，是一样的。所以问一下，pomelo会不会在什么地方做些消息过滤？

**Comment by py8765** [comment]
应该是消息格式的问题，我们在pomeloclient.js里面做了对客户端发过去的消息做过处理，具体可以参考一下。

**Comment by halfblood369** [comment]
现在用的还是socket.io，传输的是string数据，你最好看下最终传输的string数据是否一致（参考pomelo-client里面的bt2Str函数）。

**Comment by falqs** [comment]
嗯，我再看看，确认一下，编码是UTF8的吧？

**Comment by halfblood369** [comment]
@falqs 字节转化为string是用的utf8编码。具体你可以看下https://github.com/NetEase/pomelo-unityclient/blob/master/pomelo-unityclient/pomelo-unityclient/Protocol.cs 这是c#版本的协议实现。

**Comment by falqs** [comment]
终于走通了，感谢两位大哥的火力支援，3Q！

**Comment by liketo** [comment]
大神，可否把网络部分封装的内容发小弟参考下，mail :122285688@qq.com,谢谢啦

**Comment by xiecc** [comment]
https://github.com/NetEase/libpomelo

代码一直在git上，只是还没完全测好
