### ISSUE TITLE
客户端是否可以连接area服务器

### ISSUE THREAD

**Issue by chenyl107** [NetEase/pomelo-cn#46]
pomelo的架构图中客户端拿到gate分配的connector服务器后，连接connector服务器，然后再由connector转发到area服务器。但是刚刚在看捡宝代码的时候看到
pomelo.request('area.playerHandler.move', {targetPos: targetPos}, function(result) {
。。。
}

客户端直接去连接area服务器，客户端好像只能知道connector服务器的地址和端口吧，怎么能发送到area服务器呢，求解？

**Comment by numbcoder** [comment]
发起这个 request 实际上也是先发到 connector 然后再路由到 area 服务器。

**Comment by chenyl107** [comment]
是不是pomelo自动让connector转发的吗？我们不需要写任何代码？

**Comment by numbcoder** [comment]
自动的。:smile:

**Comment by chenyl107** [comment]
能不能麻烦你把自动转发的这部分相关的pomelo源代码的文件位置告诉下我，谢谢。

**Comment by changchang** [comment]
frontend服务器forward消息的地方在[这里](https://github.com/NetEase/pomelo/blob/master/lib/server/server.js#L178)

backend服务器接收消息的地方在[这里](https://github.com/NetEase/pomelo/blob/master/lib/common/remote/backend/msgRemote.js#L20)

**Comment by chenyl107** [comment]
thank you

**Comment by ghost** [comment]
不错
