### ISSUE TITLE
demo一点疑惑connection.js

### ISSUE THREAD

**Issue by shaniu00** [NetEase/pomelo-cn#47]
game-server/node_modules/pomelo/lib/components/connection.js

var Component = function(app) {
        this.app = app;
        this.service = new ConnectionService(app);

```
    // proxy the service methods except the lifecycle interfaces of component
    var method, self = this;
    for(var m in this.service) {
            if(m !== 'start' && m !== 'stop') {
                    method = this.service[m];
                    if(typeof method === 'function') {
                            this[m] = (function(m) {
                                    return function() {
                                            return self.service[m].apply(self.service, arguments);
                                    };
                            })(m);
                    } 
            }
    } 
```

};

新手关于闭包用途不是很清楚

this[m] = (function(m) {
       return function() {
                 return self.service[m].apply(self.service, arguments);
                  };
 })(m);
换成
this[m] =function() {
                 return self.service[m].apply(self.service, arguments);
                  };
区别在哪 不是很清楚 有能理解的 分享下哦3Q3Q

**Comment by changchang** [comment]
这两个的结果都是把一个function赋给this[m]。

所不同的是，第一个情况的代码通过函数闭包，把当前的m值保存到了外层的function里，这样内层的function的m不会因为外面的m改变而改变。

第二种情况的function内部直接引用了外面的m，这样产生的所有函数的m值都会变成循环过后m最后的值。

js闭包的问题网上资料应该蛮多的，也可以自己写个简单的例子对比一下效果。 :)
