### ISSUE TITLE
服务器如何主动断开客户端链接？

### ISSUE THREAD

**Issue by totollo** [NetEase/pomelo-cn#49]
服务器如何主动断开客户端链接？

**Comment by changchang** [comment]
在这个客户端连接的frontend server上，调sessionService.kick方法就可以踢掉指定的客户端连接了。
在lordofpomelo里有个[例子](https://github.com/NetEase/lordofpomelo/blob/master/game-server/app/servers/connector/handler/entryHandler.js#L55)。
