### ISSUE TITLE
app configure函数调用疑问？

### ISSUE THREAD

**Issue by ghost** [NetEase/pomelo-cn#50]
// app configure
app.configure('production|development', function() {
    // route configures
    app.route('chat', routeUtil.chat);

```
// filter configures
app.filter(pomelo.timeout());
```

});

Application.configure = function (env, type, fn) {
....
}

调用时只传递了，第一和第三个参数？

**Comment by ghost** [comment]
原来参数是这么取的：var args = [].slice.call(arguments);
arguments 对象
JavaScript 中每个函数内都能访问一个特别变量 arguments。这个变量维护着所有传递到这个函数中的参数列表。
注意: 由于 arguments 已经被定义为函数内的一个变量。

**Comment by ghost** [comment]
// start app
app.start();

Application.start = function(cb) {
...
}

支持不传递参数，也能调用到这个函数？

**Comment by ghost** [comment]
不知道是否有工具能够断点调试 chatofpomelo例子 pomelo start 的启动过程？

**Comment by py8765** [comment]
可以在servers.json中配置相应参数，然后使用一些调试工具，例如node-inspector。

**Comment by ghost** [comment]
能给出具体如何配置吗？

**Comment by py8765** [comment]
可以参考[命令行使用文档](https://github.com/NetEase/pomelo/wiki/%E5%91%BD%E4%BB%A4%E8%A1%8C%E6%96%87%E6%A1%A3)和[node-inspector](https://github.com/dannycoates/node-inspector)。

**Comment by ghost** [comment]
可以了，非常感谢
