### ISSUE TITLE
下面这注释掉的两行代码是否是没有用的？

### ISSUE THREAD

**Issue by ghost** [NetEase/pomelo-cn#54]
//Pomelo.components.**defineGetter**(name, load);
Pomelo.**defineGetter**(name, load);
......
//Pomelo.filters.**defineGetter**(name, load);
Pomelo.**defineGetter**(name, load);

注释掉后，仍可以运行chatofpomelo。

**Comment by shaniu00** [comment]
可能其他代码里面没有用到  如果需要通过 Pomelo.components.name 调用就用到了，代码里用到的是 Pomelo.name 这种形式
示例
Date.prototype.**defineGetter**('year', function() {return this.getFullYear();});
Date.prototype.**defineSetter**('year', function(y) {this.setFullYear(y)});

var now = new Date;
alert(now.year);
now.year = 2006;
alert(now);

**Comment by ghost** [comment]
好的。谢谢
