### ISSUE TITLE
求推荐游戏服务器开发相关书籍

### ISSUE THREAD

**Issue by shaniu00** [NetEase/pomelo-cn#55]
大家都知道游戏服务器开发会遇到很多问题，想往这方面发展应该掌握哪些其他知识呢，比如一些专门分享游戏开发遇到的问题的解决方案

**Comment by py8765** [comment]
可以先看看[这篇文章](http://www.infoq.com/cn/articles/game-server-development-1)。

**Comment by halfblood369** [comment]
其实游戏服务器开发和高实时的web服务器开发有很多相同点，如果你有web服务器开发的经验，建议你可以直接看pomelo的WiKi（https://github.com/NetEase/pomelo/wiki)， 里面有比较详细的pomelo游戏服务器开发文档，可以帮助你更好的理解游戏服务器开发的过程。
