### ISSUE TITLE
Pomelo上的channelService和taskManager 目的是什么，用在何处

### ISSUE THREAD

**Issue by ghost** [NetEase/pomelo-cn#57]
Pomelo.channelService = require('./common/service/channelService');
Pomelo.taskManager = require('./common/service/taskManager');

关于这两个服务，没找到具体使用的地方，麻烦告知下

**Comment by changchang** [comment]
这两个服务是之前版本的pomelo暴露出来的服务，现在不建议使用了，以后可能会移除掉的:)

channelService已经封装成一个component，使用方法可以参考[这里](https://github.com/NetEase/lordofpomelo/blob/master/game-server/app/domain/area/area.js#L95)。

taskManager现在封装成一个私有服务了，供[serial.js](https://github.com/NetEase/pomelo/blob/master/lib/filters/handler/serial.js#L5)这个filter中使用，来保证请求的顺序。

**Comment by ghost** [comment]
好的。谢谢。
