### ISSUE TITLE
android chat客户端进入房间的时候很慢

### ISSUE THREAD

**Issue by sun7834** [NetEase/pomelo-cn#58]
从服务器上git 下来之后，本地先大家好chat的服务器，浏览器可以正常的很快的访问。然后整好android客户端，运行发现加入房间很慢。后台打印日志大概要40-50s，进入房间之后一切都正常，聊天速度也挺快。我看了日志，从gate返回connector的信息大概要20s，再通过connect连接到进入chat服务器要20s左右，本地网络是正常的。

**Comment by py8765** [comment]
git上有一个apk，是连接这个[聊天室](http://pomelo.netease.com/chat/)的，你试试速度如何，我本地测试的时候速度还是挺快的。

**Comment by sun7834** [comment]
确实，我用git上的apk运行是很快的。奇怪。我再查查原因。

**Comment by py8765** [comment]
嗯，可能是网络的原因。
