### ISSUE TITLE
源代码

### ISSUE THREAD

**Issue by huaye2007** [NetEase/pomelo-cn#61]
记得之前刚开始开放游戏框架的时候，第一个例子的代码可以提供下载地址么？
第二个例子我的源码下载下来了。可这段时间发现很多源代码已经变了，不是第二个例子的源代码了。能否提供下载链接地址呢?

**Comment by py8765** [comment]
你是想要老版本的lordofpomelo？

**Comment by huaye2007** [comment]
嗯，对的，有没有链接地址下载呢？

**Comment by halfblood369** [comment]
由于lordofpomelo的素材经过替换，代码也改动了很多，即使你用老版本的游戏框架，之前的lordofpomelo现在肯定是跑不起来的……

**Comment by huaye2007** [comment]
嗯，不需要能跑起来，我只看demo的一些源代码。

**Comment by huaye2007** [comment]
正在做游戏方面的开发，所以想多看点游戏服务器的一些实现方式。

**Comment by halfblood369** [comment]
lordofpomelo的源代码自从开放后的历史版本你都能找得到，这可能需要你花点时间去看看commits。lordofpomelo的改动还是很多的，不过每次都改动比较少，大的改动就是替换素材，不过这也只是客户端有改动较大，服务器端改动很小的。

**Comment by huaye2007** [comment]
哦，看来没有具体的demo的下载地址了，谢谢了。
