### ISSUE TITLE
app.get('sync').flush()函数提示"[object Object] callback function not exist"

### ISSUE THREAD

**Issue by pengpeng** [NetEase/pomelo-cn#62]
游戏在用户退出以后，需要立即更新数据库数据。
执行
app.get('sync').flush('playerSync.updatePlayer', e.userid, e.strip()); 
提示[object Object] callback function not exist

但是执行
app.get('sync').exec('playerSync.updatePlayer', e.userid, e.strip());
和app.get('sync').sync()
都可以得到预期的结果。

**Comment by piaohai** [comment]
刚看了一下代码，这里是重构后flush的一个BUG，多传了一个参数，npm install pomelo-sync 重新装一下包试试。
谢谢指正～

**Comment by xiecc** [comment]
嗯， 多谢提这么有价值的bug

**Comment by pengpeng** [comment]
@piaohai @xiecc 已验证，没有问题了。
多谢。
