### ISSUE TITLE
用户强制退出或掉线后怎么把用户从后台服务器的channel中踢出？

### ISSUE THREAD

**Issue by birdroidcn** [NetEase/pomelo-cn#63]
我的想法是，把用户的在后台服务器的channel信息存在local session中，用户退出后在后台服务器的handle中获取local session中的channel信息，进而踢出用户。
但是用户强制退出后只会在前端服务器触发closed事件。前端服务器可以通过rpc连接到remote中。但在remote不能获取local session，所以不能获取用户channel信息。
还有种做法就是channel信息推送到全局session中，但是channel信息是和本地服务器相关的，所以不合适。

**Comment by py8765** [comment]
现在的做法是用户退出后触发close事件，然后通过rpc调用remote方法，将用户从channel中移出。
