### ISSUE TITLE
game-server端没有在app.js里面配置route，出现的怪异BUG

### ISSUE THREAD

**Issue by yandaoyong** [NetEase/pomelo-cn#66]
刚开始的时候，忘记在app.js里面配置
![QQ 20130124174247](https://f.cloud.github.com/assets/2143456/93046/6e0fa902-660a-11e2-8a89-a040ffe8a258.png)

我在开发一个社交游戏：《扎堆》
的时候，发现channelService.getChannel()这个方法重复创建了channel

我使用了三个游览器：IE9 火狐 chrome

分别进入同一个channel，叫做zhadui

IE9进入的UID是147
火狐进入的UID是170
谷歌进入的UID是146

当UID 146 进入后，控制台打印显示，重复创建了zhadui这个channel，导致获取getMembers时，在线人数是1，正确的应该是3个人啊

请查看截图

![ ](https://f.cloud.github.com/assets/2143456/93055/cd7673ee-660a-11e2-99aa-c2f15e0d25f5.jpg)

![ ](https://f.cloud.github.com/assets/2143456/93074/24bd24da-660c-11e2-8c68-53e710cc8451.jpg)

调试了很久，感觉很怪异

后来检查发现是由于app.js里面没有指定route造成的
加上第一张截图里面的代码，就好了

不知道这算是BUG，还是是自己的错误，因为在我没有加那段代码的时候，项目还是可以跑起来的，而且消息传输也没有问题

反正现在解决了，算一个经验吧，感谢网易的pomelo引擎以及工作人员的热情

**Comment by changchang** [comment]
不知你有多少个后端的服务器呢？route函数是用来指定路由规则的，也就是说决定了一个请求应该路由到哪一台后端服务器去。

默认的路由算法是根据uid对后端服务器数量取模来确定后端服务器的。

从现象上来看，有可能是其中两个用户被分配到一台后端服务器A，剩下的一个用户被分配到另外一台后端服务器B上了。

channel是每台服务器独立的，也就是说A和B服务器上都创建了名字为zhadui的channel，并且其中一个channel中的人数为2，另外一个为1，所以出现了上面的日志打印的内容。

**Comment by xiecc** [comment]
Route算法的代码贴上来看看

发自我的 iPad

在 2013-1-24，17:52，yandaoyong notifications@github.com 写道：

**Comment by yandaoyong** [comment]
我的route算法也和默认一样的，就是用户id取余服务器数量

已经解决了，就是在game-server的app.js加上route配置代码就好了

现在游戏在继续开发中，大概1个星期就可以上线了

PS：我现在有一个疑问，就是单channel里面如果存储用户量太高，比如1万人

用户每次进入游戏，都要去getMembers()获取所有在线用户列表，这样服务器压力会不会很大啊

我现在的解决方案是用户每次进入游戏时，对getMembers()进行爆布流的显示，不一次性加载完

但是pushMessage()如何解决呢，每次一push，就要1万条，这个压力很大吧

**Comment by xiecc** [comment]
嗯，channel只提供基本的API， 显示在线用户应该是由应用去缓存或分页的。

你的应用类型是啥？ 一般应用很少出现同时向1万用户广播， 除非是系统公告这种发送频率很低的。
通常的游戏逻辑可以通过AOI算法等减少广播范围

2013/1/24 yandaoyong notifications@github.com

**Comment by demon0925** [comment]
一般对用户来说你给他一万人的在线列表是没有什么意义的，没人回去看这么多，这种push肯定会造成很大压力，如果同时进入游戏的人很多的话就算应用层不出错，底层的基础设施，比如网络带宽，cpu什么的都不一定能撑得住。
不知道你具体的游戏类型是什么，但我建议这里可以针对具体的应用场景进行优化，比如channel细分等。
