### ISSUE TITLE
MonitorAgent模块中connect/3函数的疑惑

### ISSUE THREAD

**Issue by ghost** [NetEase/pomelo-cn#68]
``` javascript
this.socket.on('disconnect', function(reason) {
    if(reason === 'booted') {
        //disconnected by call disconnect function
        this.state = ST_CLOSED;
        self.emit('close');
    } else {
        //some other reason such as heartbeat timeout
    }
});
```

这里的：this.state = ST_CLOSED; 是否应该修改为：self.state = ST_CLOSED;

**Comment by ghost** [comment]
另外：
除了'error'事件的监听，其他事件的监听为什么这里不像MasterAgent模块那样，在'connection'事件的监听器函数中才添加监听？

**Comment by changchang** [comment]
恩，正确的应该是self而不是this。

事件的监听主要是客户端和服务器的区别。MasterAgent是服务器，'connection'事件触发后才能获取到一个新的客户端连接实例，之后才能对其进行绑定操作。MonitorAgent是客户端，是创建了连接实例才去尝试连接，所以可以先对连接实例进行事件绑定。如果放在'connect'事件响应函数中进行监听，客户端有可能存在重连的情况，导致重复的监听。

**Comment by ghost** [comment]
好的，谢谢解答。
