### ISSUE TITLE
关于Pomelo的几个问题

### ISSUE THREAD

**Issue by agreatfool** [NetEase/pomelo-cn#69]
1. 聊天室demo中的一个问题
   项目：chatofpomelo
   文件：game-server/app/servers/connector/handler/entryHandler.js
   函数申明：
   /**
   - User log out handler
     *
   - @param {Object} app current application
   - @param {Object} session current session object
     *
     */
     var onUserLeave = function(app, session) {
     if(!session || !session.uid) {
     return;
     }
     app.rpc.chat.chatRemote.kick(session, session.uid, app.get('serverId'), session.get('rid'), null);
     };
     函数调用：
     session.on('closed', onUserLeave.bind(null, self.app));
     问题：
     这里我不明白的是，明明没有申明过bind函数，这个bind函数是从哪里来的？
     然后这里的第一个参数null是什么意思？在什么地方能查到这个东西的文档或者源代码？
2. 回调函数的问题：
   在源代码中充斥这这样的调用，handler的某一个接口调用中：
   next(null, {
   users:users
   });
   next函数负责进行返回，请问这个next函数的定义在哪里能查到文档或者源代码？
   我在阅读范例的时候觉得null这个参数的位置应该是用来传new Error的，但是不太确定。
3. 关于错误处理的问题：
   Pomelo框架的错误处理机制是怎样的？如果我在代码中throw 一个new Error，我自己不写try catch块的话，在哪里这个错误会被捕获到？什么样的错误会导致程序崩溃？

**Comment by xiecc** [comment]
1. bind是javascript自带的函数， 用于为调用函数绑定一个作用域，因为this很容易跟丢它原来所在的作用域。建议看一下js的参考文档。
2. 这是node.js的默认规范， 第一个参数是error， 如果流程正常则传入null，除非确实出错才会传入真正的error
3. 尽量不要写try catch，除非确实这个异常是意料中的情况，一般异常抛给框架更合适，容易跟踪，也更容易优化。进程不会崩溃，因为app.js里有process.on机保证，并打印异常信息。

**Comment by agreatfool** [comment]
非常感谢
