### ISSUE TITLE
关于lordofpomelo中的灯塔的疑惑

### ISSUE THREAD

**Issue by gongxinheng** [NetEase/pomelo-cn#7]
area.json表中有两个字段控制灯塔的宽和高。我想了解下这两个参数的含义是否跟我理解的一样。我的理解是这个范围代表了以玩家位置为中心点，参数为一个矩形区域的感知范围。
比如玩家在坐标(250,150)，灯塔是300*300，那么此玩家可收到{x1=100,x2=400,y1=0,y2=300}矩形区域之间的消息。是这样吗？

**Comment by demon0925** [comment]
实际通知区域要比这个大一些。
灯塔是AOI的最小单位，对于AOI中的对象来说，还有一个视野的概念。视野指的是以玩家为中心，向外扩展的范围。
这里以灯塔的坐标为例：
一个玩家的坐标为（2，2），视野为2，那么他能看到的范围是以（0,0)为左上角，(4,4)为右下角的一个矩形区域。

在实际的场景中，玩家的视野大小会根据窗口大小来变化的，但最小值不会小于2。而怪物的视野默认为0，即怪物只能接受到它所在灯塔内的消息，这也就是你说的情况。

**Comment by gongxinheng** [comment]
谢谢~大概了解了。
不过还有疑惑，area.json中设置灯塔的宽高默认是(300,300)，我想了解下这里的单位是以tile为单位还是实际的坐标单位？另外顺便问下玩家的视野范围在哪设置呢？单位是tile吗？

**Comment by demon0925** [comment]
这个是实际的坐标单位，用tile做单位就太大了一点么。
玩家的视野范围是在player初始化的时候可以通过传入参数来设置，默认为2.
然后在客户端更改屏幕大小的时侯会向服务端发送一个请求{area.playerHander.changeView)，服务端在处理这个请求时会改变玩家视野，并且会触发相应的AOI事件。

玩家的视野范围不是地图的tile，是以灯塔为单位的。服务端的地图实际上会有3套坐标，实际坐标，tile坐标和灯塔坐标，其中tile粒度较小（默认20px），用来构建障碍物地图，计算路径时使用。而灯塔坐标则主要是在AOI中使用。

**Comment by gongxinheng** [comment]
OK, Thanks~
