### ISSUE TITLE
component.connection 为空的问题

### ISSUE THREAD

**Issue by innobeanslong** [NetEase/pomelo-cn#70]
玩家登陆服务器之后，session.bind(uid),调用pomelo/lib/components/connector.js，line118的函数，但是发现component.connection的值为空，导致无法addLoginedUser，pomelo-admin-web无法检测在线玩家数据，求解答。，想知道component.connection是何时赋值的？

PS:我在调用判断是否为空值前加了component.connection = component.app.components.**connection**，倒是能检测在线玩家数据，不知道这样会不会导致其他问题

**Comment by changchang** [comment]
恩，这里确实把connector组件中的connection字段初始化漏掉了，是一处bug，谢谢指出。该bug已经在https://github.com/NetEase/pomelo/commit/3d578041741748cf406283cfdaad19b8f193bde8 中修复。

**Comment by innobeanslong** [comment]
好的，解决了就行
