### ISSUE TITLE
server.json添加了一台服务器记录报错。具体错误看下面图片

### ISSUE THREAD

**Issue by fangzehua** [NetEase/pomelo-cn#73]
![ 5NL AIOG9XXU8 4 OM 09](https://f.cloud.github.com/assets/3446414/117577/d7f02972-6c46-11e2-9f65-b76a783e2157.jpg)
![4N DL 6Y6E14_X PHGEK UU](https://f.cloud.github.com/assets/3446414/117578/d815de56-6c46-11e2-905d-c4b944229746.jpg)

2太机子可以相互ssh登陆且无需输入密码

master.josn配置均192.168.1.64（主）

谁有知道的 帮忙我回答下， 谢谢。小弟刚接触这块

**Comment by xiecc** [comment]
可能是之前的进程没杀干净，导致端口冲突。 用pomelo kill或 pomelo kill --force， 在game-server目录下执行

**Comment by fangzehua** [comment]
应该不是这个问题。我2台机子刚启动的， 进程都是没有开启的
如果1.64启动成功了 1.65上面是不是pomelo list 可以看到进程，
还是我忘记了那些步骤， 请帮我看看 谢谢你们了。 暂时看不懂源码，

**Comment by py8765** [comment]
那就是其它服务占用了端口，从你的错误提示看确实是端口冲突。

**Comment by fangzehua** [comment]
换了端口也是一样的错误 还是无法打组建。应该不是端口的问题  或者是我那个地方配置错了。

2个机子的跑的是一模一样的 配置文件都是一致的  是不是这个有问题 ？

麻烦你了

**Comment by fangzehua** [comment]
换了端口也是一样的错误 还是无法打组建。应该不是端口的问题 或者是我那个地方配置错了。

2个机子的跑的是一模一样的 配置文件都是一致的 是不是这个有问题 ？

麻烦你了

**Comment by py8765** [comment]
你不会在两台机器上都运行了pomelo start命令吧。

**Comment by fangzehua** [comment]
不是的 我在1.64上运行  pomelo start
2台的 配置文件都是一样的 master.josn配置是 1.64

**Comment by fangzehua** [comment]
不好意思啊 我在65上输入pomelo list 没看到运行进程  但是我ps -ef|grep 'pomelo" 的时候 确实发现 65上面有启动进程  是否这就说明已经成功
root      3223  3214  0 00:06 pts/1    00:00:00 ssh 192.168.1.65 cd /home/fzh/pomeloTest/testDemo/game-server && node  /home/fzh/pomeloTest/testDemo/game-server/app.js env=development serverType=connector serverId=connector-server-2
 那个错误是不是可以无视啊

**Comment by py8765** [comment]
你看一下你的应用能不能正常的跑起来。

**Comment by fangzehua** [comment]
可以跑起来的 是pomelo init 的里面没有任何东西

**Comment by py8765** [comment]
那你可以试试我们的几个demo项目，chatofpomelo和treasure，分别试试分布式的跑一下。

**Comment by fangzehua** [comment]
恩 刚有这个打算  我试试看 谢谢你啊

**Comment by fangzehua** [comment]
![ 9EEKF4Y IWZ ZIOSIY6XJ](https://f.cloud.github.com/assets/3446414/120513/f8b114fa-6cfa-11e2-89d0-35342c0019a7.jpg)
这个是刚测试的chat聊天的那个 咋显示这个了。还测试了下  init的demo在XP上可以正常跑 点击可以弹出对话框
但linux上不出对话框 不是是否不支持火狐

**Comment by py8765** [comment]
应该是缓存的原因，浏览器最好是chrome。

**Comment by fangzehua** [comment]
恩 谢谢你拉
