### ISSUE TITLE
关于这个pomelo-scheduler库的几个问题

### ISSUE THREAD

**Issue by ghost** [NetEase/pomelo-cn#74]
1. 目录中存在临时文件README.md~
2. 第一段描述中，schedulemodule 应该为 schedule module 吧？ 
3. 代码缩进跟pomelo不同。

**Comment by xiecc** [comment]
嗯， 这个模块在lord of pomelo中没用到， 所以做的不是太严谨。 我们改进一下

**Comment by ghost** [comment]
恩恩。
