### ISSUE TITLE
关于Pomelo Unity3D Client的两个问题

### ISSUE THREAD

**Issue by ninjacatii** [NetEase/pomelo-cn#76]
各位大大：
      我现在正在用Pomelo+Unity3D开发项目，在开发项目的过程中，碰到了两个问题：
1.SimpleJson的接口不太友好，每次要生成一个JsonObject，或从JsonObject中取值时的代码为：

```
public static JsonObject GetJsonObject(params System.Object[] args) {
    int length = args.Length;
    if (length % 2 != 0 || length == 0) {
        Debug.LogError("The length of args is zero or an odd number.");
        return null;
    }
    JsonObject o = new JsonObject();
    for (int i = 0; i < length / 2; i++) {
        o.Add(args[i * 2].ToString(), args[i * 2 + 1]);
    }
    return o;
}

public static System.Object GetJsonObjectValue(JsonObject jo, string key) {
    System.Object o = null;
    jo.TryGetValue(key, out o);
    return o;
}
```

请问有没有更好的方式来解决生成JsonObject或从中取值的方法。
2.UnityClient中似乎没有EventEmitter类，许多Entity需要从EventEmitter继承，我要如何解决这个问题呢？

**Comment by halfblood369** [comment]
1.SimpleJson是个第三方库，专门处理json数据对象。一些比较好的开源软件，比如https://github.com/kerryjiang/SuperWebSocket 等都用的这个库，应该还不错。如果你觉得这个库不好，你可以替换它或者修改它的代码。
2.关于事件机制，你可以参考pomelo-unityclient 项目里的EventManager类，这是C#中处理事件机制的通用做法。

**Comment by ninjacatii** [comment]
好的，非常感谢大大的帮助，希望大家一起把Pomelo的团队建设得越来越强大。
