### ISSUE TITLE
给我个java客户端的demo好么。github上面下载了一个 这么搞都不搞不出来。 

### ISSUE THREAD

**Issue by fangzehua** [NetEase/pomelo-cn#78]
给我个demo好么  java客户端的  能连接pomelo服务端 最好能发送个信息， 连接成功输出个信息  可以么 谢谢了 早上下载l你们的 那个列子  一直都跑不成功。不知道问题在哪里 
实在感谢

**Comment by xiecc** [comment]
已经开发了android版的客户端， 与java版是通用的， 也有聊天客户端的demo。
你去我们wiki页面查看一下： https://github.com/NetEase/pomelo/wiki

2013/2/4 fangzehua notifications@github.com
