### ISSUE TITLE
chatofpomelo最新的demo代码当前频道用户列表显示不出来

### ISSUE THREAD

**Issue by chenyl107** [NetEase/pomelo-cn#79]
chatofpomelo最新的demo代码当前频道用户列表显示不出来，我参考了一些chatofpomelo中的代码，charRemote的get方法得到的不是当前频道的人我只能得到自己，demo是空的

**Comment by py8765** [comment]
有报什么错吗，我在线上的聊天室也是用的github代码，ms也没有什么问题。

**Comment by chenyl107** [comment]
@py8765 是我弄错了，最新的可以 之前的版本不行。data.length没有定义。我再看看。。。

**Comment by chenyl107** [comment]
@py8765 
服务器端:
self.app.rpc.chat.chatRemote.add(session, uid, self.app.get('serverId'), rid, true, function(users){
                       next(null, {code: 200,userinfo: res,users:users});
                   });

客户端:
console.log(data.users);

chatRemote代码和chat的demo一样的，返回的只有一个用户

**Comment by chenyl107** [comment]
@py8765 找到原因了，我的channel是保存在数据库里的，其中一个多了一个空格，建议channelService.js添加对channal名字前后空格的过滤
