### ISSUE TITLE
帮我看下代码可以么

### ISSUE THREAD

**Issue by fangzehua** [NetEase/pomelo-cn#80]
public class PomeloTest  {
 PomeloClient client ;
 JSONObject json;
 String route;  

```
public PomeloTest() throws JSONException {
    client = new PomeloClient("http://127.0.0.1", 80);
    client.init();  
    client.request("",json,new DataCallBack(){

        @Override
        public void responseData(JSONObject arg0) {
            //这里做啥
        }
    });

    client.on("onChat", new DataListener(){
        @Override
        public void receiveData(DataEvent arg0) {
            JSONObject json = arg0.getMessage();
            System.out.println(json.toString());
        }
    });
}

public static void main(String[] args) throws JSONException {
    new PomeloTest();
}
```

}

报错  握手失败。 client.request()这里面具体是啥，我这里route可以是空的吧

**Comment by fangzehua** [comment]
谢谢拉

**Comment by fangzehua** [comment]
io.socket.SocketIOException: Error while handshaking
    at io.socket.IOConnection.handshake(IOConnection.java:322)
    at io.socket.IOConnection.access$600(IOConnection.java:39)
    at io.socket.IOConnection$ConnectThread.run(IOConnection.java:199)
Caused by: java.io.FileNotFoundException: http://127.0.0.1:80/socket.io/1/
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at io.socket.IOConnection.handshake(IOConnection.java:313)
    ... 2 more
2013-2-4 16:50:51 io.socket.IOConnection cleanup
信息: Cleanup
错误信息

**Comment by py8765** [comment]
client.request()是客户端发送到某个服务器的请求，route需要有具体的服务器路径，你可能要先弄清楚pomelo的客户端的基本用法，可以参考[chatofpomelo](https://github.com/NetEase/pomelo/wiki/tutorial1--%E5%88%86%E5%B8%83%E5%BC%8F%E8%81%8A%E5%A4%A9)。

**Comment by fangzehua** [comment]
恩  谢谢拉  我昨天看了下 了解了
