### ISSUE TITLE
flash客户端连接chat聊天demo提示

### ISSUE THREAD

**Issue by fangzehua** [NetEase/pomelo-cn#84]
warn: 'unknown transport: "flashsocket"' 这个是啥子原因

**Comment by piaohai** [comment]
请问你使用的是那个库，是https://github.com/stokegames/pomelo-flashchat这个吗？

socket.io-client里面支持HTTP和WEBSOCKET二种。

**Comment by fangzehua** [comment]
下载了是https://github.com/stokegames/pomelo-flashchat这个吗？
还是一样的提示

**Comment by fangzehua** [comment]
啥问题 manager.js 输出的transports 没有flashsocket 所有我直接push了下  那个问题是解决了、
但是默认却不行 你们知道是啥的么  2个客户端我都测试了 同一个错误提示

**Comment by piaohai** [comment]
那个源代码是需要运行一个FLAHS的POLICY文件的吧，默认没有FLAHSOCKET。
或者下载这里的FLEX源代码测试运行
https://github.com/piaohai/socket.io-flashclient.git

**Comment by joshle** [comment]
我调试了好几天，终于明白为什么会报：warn: 'unknown transport: "flashsocket"'  这个提示了，是因为默认的defaultTransports 没有包含 flashsocket 这一项，所以就连接失败了。
添加transport项：flashsocket 就可以正常连接到服务器了。
方法：找到文件：chatofpomelo/game-server/node_modules/pomelo/node_modules/socket.io/lib/manager.js
找到36行：var defaultTransports = exports.defaultTransports = [
在这个配置项里面添加一项：
  , 'flashsocket'
重启服务器，搞定！
