### ISSUE TITLE
对于channelService的问题

### ISSUE THREAD

**Issue by jianfengye** [NetEase/pomelo-cn#85]
以chatofpelome为例，比如开启了三个chat服务进程A，B，C，然后甲用户创建了聊天室chat1，这个chat1是会创建一个channelService的对吧（是从ChannelService.getChannel()这里创建的）

如何确定这个channelService是创建在哪个进程中呢？（我看代码的理解是发送chat的进程在哪个上就在那个进程中new channel）

**Comment by jianfengye** [comment]
补充提问个：

一个聊天室的channelService是否是会分布在多个chat进程上？

**Comment by py8765** [comment]
每一个进程里面只有一个ChannelService，例如一个chat进程就只有一个ChannelService。所以不会有一个聊天室的ChannelService分布在多个chat进程上。同时，一个聊天室只能在一个chat进程中，这样也不会出现同一个聊天室的聊天出现跨进程通信的情况。

**Comment by jianfengye** [comment]
问个代码方面的问题：
chatofpomelo/game-server/app/servers/connector/handler/entryHandler.js

里面的
handler.entry 函数的这句：
self.app.rpc.chat.chatRemote.add(session, uid, self.app.get('serverId'), rid, true, function(users){
        next(null, {
            users:users
        });
    });

怎么理解
1 self.app.rpc 这里的application实例是有rpc这个属性的么
2 chatRemote.add的参数怎么比servers/chat/remote/chatRemote.js里面多？

**Comment by py8765** [comment]
1.嗯，是有的，这样方便rpc调用。
2.因为是rpc调用，session参数是必须的，因为需要知道调用所在的前端服务器；每一个rpc调用的都需要有session参数，只是底层把这个屏蔽了，所以在写rpc方法的时候就不需要全部都带上session参数。

**Comment by jianfengye** [comment]
这个application.rpc属性的设置是在哪里设置的? 我找了找pomelo/application.js没看到

**Comment by py8765** [comment]
pomelo/components/proxy.js

**Comment by jianfengye** [comment]
谢谢耐心帮助，终于看通了，一通百通

个人有个看法，这样一个channelService只在一个进程中（聊天室或场景）。那万一有什么活动，导致某个聊天室人数非常多，这样这个chat进程的压力就会非常大了，而且没法临时扩展了。。。

**Comment by py8765** [comment]
但是如果跨进程就代价就非常高，消息发送就需要跨进程通信。

**Comment by jianfengye** [comment]
哦。。。是的，但是对游戏来说，这个需求是有的，而且是很普遍的。

我的意思是一个channel可以在多个chat进程上，然后connector发送消息的时候往多个chat进程同时发送rpc，如果是单播消息，就只有一个chat进程会反映，如果是多播消息，就会有多个chat进程反映

现在消息发送就是发送一条rpc，这样的消耗就是多了几条rpc，但是不会导致一个进程压力很大，但另一个进程压力小的情况了。

btw，当然知道这样的实现还是复杂的，only想法
