### ISSUE TITLE
还是java客户端的问题，我是用你们的chat本地搭的

### ISSUE THREAD

**Issue by fangzehua** [NetEase/pomelo-cn#86]
还是错误。第一次init成功后返回分配的IP 端口后 最后就一直报错 啥类型错误

找不到转发信息方法等，可否提供个可运行的demo。你们估计几分钟就搞定了。

现在出了这样的错误除了看你们源码外就没办法可解。

**Comment by fangzehua** [comment]
写个可用的吧，不要再建议了。一个chat10个人下载 5个人会跑不起来的  一样的操作。。。  我哭啊

**Comment by fangzehua** [comment]
好了解决了。是我的问题。 下面是我的代码吧网上下来的包丢到项目里面去 然后复制下面的代码 就可以跑了

服务器是chat聊天那个 希望害下跟我一样懒的菜鸟

package com.netease.test;

import org.json.JSONException;
import org.json.JSONObject;

import com.netease.pomelo.DataCallBack;
import com.netease.pomelo.PomeloClient;
public class Pomelotest {
    public PomeloClient client;
    JSONObject json;
    String username="2013";
    //"connector.entryHandler.enter"
    public Pomelotest() throws JSONException {
        client = new PomeloClient("127.0.0.1",3014);
        client.init();
        json = new  JSONObject();
        json.put("uid", "2013");
        json.put("username",username);
        json.put("rid", "2013"); // connector.entryHandler.enter"
        json.put("content", "测试");
        json.put("from", username);
        json.put("target","*" );
        client.request("gate.gateHandler.queryEntry",json, new DataCallBack(){//连接gete服务器
            @Override
            public void responseData(JSONObject message) { 
                client.disconnect();//连接成功后断开
             try {
                client = new PomeloClient(message.get("host").toString(),Integer.parseInt(message.get("port").toString()));//更具分配的ip 端口重新连接
                client.init();
                client.request("connector.entryHandler.enter",json, new DataCallBack(){//注册信息
                    @Override
                    public void responseData(JSONObject message) {
                        //发送信息
                        client.request("chat.chatHandler.send",json, new DataCallBack(){//发送信息

```
                        @Override
                        public void responseData(JSONObject message) {
                            System.out.println(message.toString());
                        }

                    });

                }

            });

         } catch (Exception e) {
            e.printStackTrace();
        }

        }

        });







}

public static void main(String[] args) throws JSONException {
    new Pomelotest();

}
```

}

**Comment by py8765** [comment]
问题解决了就好:)
