### ISSUE TITLE
charofpomelo项目有点问题

### ISSUE THREAD

**Issue by juliguo** [NetEase/pomelo-cn#88]
再服务器端上访问正常，但是在其他的机器上通过Ip访问是有问题的。

修改了js/client.js中的 queryEntry的  callback(data.host, data.port); 为 callback(window.location.hostname,data.port);就可以，不知道是服务端config/servers.json应该修改host呢？还是这里有bug。请指教。

**Comment by py8765** [comment]
queryEntry中获取的host和port是gate服务器从config/servers.json中读取的，所以就需要确保config/servers.json中的connector的host和port的配置是正确的。
