### ISSUE TITLE
關於pomelo的一點疑惑

### ISSUE THREAD

**Issue by mudoser** [NetEase/pomelo-cn#89]
1、用pomelo開發遊戲，有無心跳包的概念，就是讓服務端知道該客戶端在線。
2、l另外，我看了下chat的代碼，客戶端發起連接。
pomelo.request('connector.entryHandler.enter', {username: username}, function(){
}); 

以上请求字符串’connector.entryHandler.enter’分别代表了服务器类型、服务端相应的文件名及对应的方法名。
connector是服務類型名，就是server目錄下有個目錄叫connector
entryHandler只說connector目錄下有entryHandler.js文件，是吧
這麼搞我有點覺得怪怪的，有無安全問題哦？

**Comment by py8765** [comment]
1.因为是长连接，所以pomelo是有心跳包的，早期的pomelo底层是socket.io，本身就有心跳；在后面的版本我们在socket上也有心跳的设计。
2.这样设计的原因是为了更方便开发者使用，至于安全问题我们可能还没有遇到，如果你遇到了，可以提出来跟我们一起交流。

**Comment by xiecc** [comment]
暴露服务端的路径和方法不会有安全问题， rails也是这么设计的。
真正要注意的安全问题的措施有:
1、所有业务逻辑都在服务端完成，做好服务端校验
2、防止脚本殖入，避免客户端有嵌入脚本的机会， sql injection和跨站脚本都是因为给用户提供了殖入脚本的机会

2013/2/24 py notifications@github.com
