### ISSUE TITLE
lordofpomelo Demo中地图问题

### ISSUE THREAD

**Issue by gongxinheng** [NetEase/pomelo-cn#9]
我从Demo中拿过来部分代码放到自己工程里调试发现加上地图后，地图服务器启动失败。因为我是自己编辑的地图，里面没有collision属性，初始化的时候就失败了。能不能简单给介绍下lordofpomelo中使用的地图需要在tiled编辑器中设置一些什么属性和一些要注意的事项呢？非常感谢！

**Comment by py8765** [comment]
对于地图来说，地图本身是一个图层，其它的障碍物、npc、怪物出生点和人物出生点都属于对象层。障碍物只需要在地图上勾画出对应多边形即可，其它出生点等都可以是普通的矩形。具体每种对象的属性可以参考game-server/config/map下面的json文件，在tiled中画好并标注属性后直接导出json数据即可。

**Comment by gongxinheng** [comment]
好的！了解！谢谢！
