### ISSUE TITLE
fail to send message by uid for session not exist

### ISSUE THREAD

**Issue by innobeanslong** [NetEase/pomelo-cn#90]
fail to send message by uid for session not exist，session不存在，这个不应该啊，刚登陆的。实现的功能是大世界聊天，客户端发送聊天消息，服务器进行广播的时候，出现这个提示，另外服务器只有一个人。求大神帮忙解答

**Comment by changchang** [comment]
你的服务器分布是什么样子的？
是通过`ChannelService.pushMessageByUids`还是`channel.pushMessage`来进行消息推送的呢？
登录后有没有成功的调用session.bind方法来将uid和session绑定？

**Comment by innobeanslong** [comment]
通过ChannelService.pushMessageByUids 发送的，已经bind过了，uidMap中也有该信息

**Comment by innobeanslong** [comment]
![ ](https://f.cloud.github.com/assets/3387449/194903/aa3f793c-7fc5-11e2-9e37-2d373e33c6ea.jpg)
这个是sessionService的调试信息

**Comment by innobeanslong** [comment]
大概知道什么原因了，是我bind的时候把uid改成object了，倒是uidMap无法根据字符串类型查找到相应的session，自己吭自己了
