### ISSUE TITLE
请问使用pomelo需要什么其它方面的知识，完全没开发过服务器端？

### ISSUE THREAD

**Issue by liketo** [NetEase/pomelo-cn#91]
请问使用pomelo需要什么其它方面的知识？ 完全没开发过服务器端，写过js客户端。

**Comment by py8765** [comment]
先熟悉一下node.js，最好是对服务端有一定了解，这样看源码可能会更容易理解。

**Comment by mudoser** [comment]
先熟悉pomelo的运行机理，然后看下demo
