### ISSUE TITLE
运行chatofpomelo时出错

### ISSUE THREAD

**Issue by nickwong** [NetEase/pomelo-cn#94]
附上出错提示和出错行的代码，通过调试工具查看self.app.rpc为undefined。
------------------------------出错提示---------------------------------------------
[2013-03-03 06:03:47.086] [ERROR] console -  Caught exception: TypeError: Cannot read property 'chat' of undefined
    at Handler.entry (/Users/zz/workspace/node/chatofpomelo/game-server/app/servers/connector/handler/entryHandler.js:42:14)
---------------------42行代码，self.app.rpc为undefined---------
self.app.rpc.chat.chatRemote.add(session,session.uid,app.get('serverId'),session.get('rid'),true, function(users) {
        next(null, {
            users:users
        });

**Comment by py8765** [comment]
这个问题可能是服务器还没有完全启动，你可以先把pomelo的版本更新到0.2.5，然后开启服务器后等待10s左右再点击登录。

**Comment by nickwong** [comment]
你好，非常感谢你的答复。
我更新到0.2.5，10s之后再点击登陆，但还是遇到同样的问题。我的系统是Mac 10.6.8，不知道是不是系统的问题？

**Comment by changchang** [comment]
应该不是系统的问题。这个问题是每次一定会出现还是偶尔会出现呢？chatofpomelo的例子，我在mac 10.8.2下用pomelo 0.2.5版本是可以正常运行的。

方便的话能否把你的项目打个包发到我的邮箱changchang005@gmail.com，我定位一下原因。谢谢：）

**Comment by nickwong** [comment]
非常感谢你的答复。这个问题是每次都会出现的，我晚些就把代码打包发你邮箱，现在外面无线不是很稳定。

**Comment by nickwong** [comment]
你好，是我这边的问题，升级到0.2.5之后没有问题了～，0.2.4存在这个问题。
