### ISSUE TITLE
关于Pomelo自带日志的几个问题

### ISSUE THREAD

**Issue by agreatfool** [NetEase/pomelo-cn#95]
上周在看pomelo的pomelo-admin-web的时候，发现，rpc和forward的监控页面一直都是白板，稍微读了下代码后，发现，系统logs文件夹下的rpc-...和forward-...日志都是白板，所以监控页面上输出的当然也就是白板了。
仔细看了下pomelo-logger之后，调整了下game-server/config/log4js.json里的"levels"，将rpc和forward都调成"DEBUG"，forward日志就出来了（rpc日志还是没出来，后面说，这里有个bug）。
## 建议丰富下pomelo-admin-web的文档，方便读者配置服务器来使用admin-web。

rpc的日志还有个问题，是在node_modules/pomelo/lib/components/proxy.js:54
"if(this.opts.enableRpcLog) {"
而proxy初始化是在node_modules/pomelo/lib/applications.js:139
"this.load(pomelo.proxy, this.get('proxyConfig'));"
这里this.get('proxyConfig')拿出来是undefined，所以proxy.js里的判断条件永远是非，那么rpc日志就永远不会出现。
请修正这个bug。

**Comment by agreatfool** [comment]
为啥当中那行是b的啊。。。我没改过样式，也不知道样式怎么改，囧。哦不对，还是h2的，囧

**Comment by xiecc** [comment]
Yeah, we will improve these documents after 0.3 version
