### ISSUE TITLE
还是关于断开链接的问题

### ISSUE THREAD

**Issue by totollo** [NetEase/pomelo-cn#98]
之前问过类似的问题。也找过文档。如果用KICK来断开链接的话，必须要先有一个绑定了的UID才行。但如果UID还没绑定SESSION呢？要怎么操作。如果先绑一下再KICK。一个合法用户的链接会被另一个尝试链接的非法用户KICK出来。所以，有没有直接点的方法让我断开客户端和服务器的SOCKET链接呢？

**Comment by halfblood369** [comment]
你的这个问题很好，目前已经提供了kickBySessionId 这个函数，不需要绑定uid，直接通过session的id就能断开连接。不过好像还没有发布到master分支上，你稍等两天，很快会有答复的……

**Comment by changchang** [comment]
在[0.3.x-push](https://github.com/NetEase/pomelo/tree/0.3.x-push)分支上有提供[SessionService.kickBySessionId](https://github.com/NetEase/pomelo/blob/0.3.x-push/lib/common/service/sessionService.js#L179)和[LocalSessionService.kickBySid](https://github.com/NetEase/pomelo/blob/0.3.x-push/lib/common/service/localSessionService.js#L83)接口，可以方便地根据session id踢掉指定的连接。但是这两个接口还没有合到master分支上。

目前的处理办法可以通过[SessionService.get](https://github.com/NetEase/pomelo/blob/master/lib/common/service/sessionService.js#L79)方法获取到对应的global session实例，然后调用[session.closed](https://github.com/NetEase/pomelo/blob/master/lib/common/service/sessionService.js#L356)方法主动断开与客户端的连接。
